// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_China.json
// Cloud        : China
// Service tag  : MicrosoftContainerRegistry.ChinaNorth
metadata name = 'MicrosoftContainerRegistry.ChinaNorth'
metadata description = 'This module contains all the service tag IP addresses of MicrosoftContainerRegistry.ChinaNorth for China.'
metadata author = ''
metadata author = ''

@description('MicrosoftContainerRegistry.ChinaNorth service tag IP addresses for China')
@export()
var MicrosoftContainerRegistry_ChinaNorth = [
  '139.217.48.96/29'
  '2404:7940:1:402::88/125'
]
