// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_China.json
// Cloud        : China
// Change number: 392
// Service tag  : MicrosoftContainerRegistry.ChinaNorth

var MicrosoftContainerRegistry_ChinaNorth = [
  '139.217.48.96/29'
  '2404:7940:1:402::88/125'
]
