// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-21
// Source file  : ServiceTags_AzureGermany.json
// Cloud        : AzureGermany
// Change number: 193
// Service tag  : AzureMachineLearning

var AzureMachineLearning = [
  '51.8.235.240/28'
  '51.8.242.16/28'
  '51.8.250.16/28'
]
