// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_China.json
// Cloud        : China
// Change number: 392
// Service tag  : ActionGroup.ChinaNorth2

var ActionGroup_ChinaNorth2 = [
  '2404:7940:101:2::394/126'
  '2404:7940:101:402::978/125'
]
