// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_AzureGovernment.json
// Cloud        : AzureGovernment
// Service tag  : AzureMachineLearning.USGovVirginia
metadata name = 'AzureMachineLearning.USGovVirginia'
metadata description = 'This module contains all the service tag IP addresses of AzureMachineLearning.USGovVirginia for AzureGovernment.'
metadata author = ''
metadata author = ''

@description('AzureMachineLearning.USGovVirginia service tag IP addresses for AzureGovernment')
@export()
var AzureMachineLearning_USGovVirginia = [
  '20.140.91.64/28'
  '20.140.130.224/28'
  '20.159.5.112/28'
  '51.55.23.73/32'
  '51.55.23.74/31'
  '51.55.23.108/30'
  '51.55.23.144/28'
  '51.55.23.160/27'
  '52.127.42.176/28'
  '52.127.48.80/28'
  '2001:489a:3103::2c0/122'
  '2001:489a:3103:8::39/128'
  '2001:489a:3103:8::3a/127'
  '2001:489a:3103:8::45c/126'
  '2001:489a:3103:8::480/123'
  '2001:489a:3103:8::4a0/124'
]
