// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_AzureGovernment.json
// Cloud        : AzureGovernment
// Service tag  : MicrosoftDefenderForEndpoint
metadata name = 'MicrosoftDefenderForEndpoint'
metadata description = 'This module contains all the service tag IP addresses of MicrosoftDefenderForEndpoint for AzureGovernment.'
metadata author = ''
metadata author = ''

@description('MicrosoftDefenderForEndpoint service tag IP addresses for AzureGovernment')
@export()
var MicrosoftDefenderForEndpoint = [
  '20.141.20.80/28'
  '20.141.167.16/28'
  '20.141.167.32/28'
  '20.159.6.128/28'
  '20.159.104.208/28'
  '52.243.242.16/28'
  '52.243.242.32/28'
  '52.245.156.80/28'
]
