// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-10
// Source file  : ServiceTags_AzureGovernment.json
// Cloud        : AzureGovernment
// Service tag  : AzurePortal.AzureAppServiceUx

var AzurePortal_AzureAppServiceUx = [
  '52.245.146.0/32'
]
