// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_AzureGovernment.json
// Cloud        : AzureGovernment
// Change number: 390
// Service tag  : AzureBotService.USDoDEast

var AzureBotService_USDoDEast = [
  '20.140.64.64/30'
  '52.126.202.172/30'
  '2001:489a:3303::20/123'
]
