// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-21
// Source file  : ServiceTags_China.json
// Cloud        : China
// Change number: 391
// Service tag  : StorageSyncService.ChinaNorth3

var StorageSyncService_ChinaNorth3 = [
  '40.162.75.40/29'
  '40.162.75.64/29'
  '52.131.29.176/29'
  '2406:e500:2602:400::3a0/123'
]
