// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_China.json
// Cloud        : China
// Service tag  : AzureSignalR.ChinaEast2
metadata name = 'AzureSignalR.ChinaEast2'
metadata description = 'This module contains all the service tag IP addresses of AzureSignalR.ChinaEast2 for China.'
metadata author = ''
metadata author = ''

@description('AzureSignalR.ChinaEast2 service tag IP addresses for China')
@export()
var AzureSignalR_ChinaEast2 = [
  '40.73.172.192/27'
  '52.130.7.160/27'
  '2404:7940:301:2::/120'
]
