// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_China.json
// Cloud        : China
// Service tag  : AzureSignalR.ChinaNorth

@export()
var AzureSignalR_ChinaNorth = [
  '40.72.79.160/27'
  '52.130.128.160/27'
  '2404:7940:1:2::/120'
]
