// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : Sql.BelgiumCentral

var Sql_BelgiumCentral = [
  '9.160.56.96/27'
  '9.160.56.128/26'
  '9.160.58.160/27'
  '9.160.82.136/29'
  '9.160.82.160/27'
  '9.160.88.48/29'
  '9.160.88.224/27'
  '9.160.112.48/29'
  '9.160.112.224/27'
  '2603:1020:1502:2::620/123'
  '2603:1020:1502:2::680/121'
]
