// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : Sql.SouthCentralUSSTG

@export()
var Sql_SouthCentralUSSTG = [
  '20.44.0.0/27'
  '20.44.1.0/27'
]
