// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : Sql.MalaysiaWest

var Sql_MalaysiaWest = [
  '20.17.127.96/27'
  '20.17.127.128/26'
  '20.17.131.40/29'
  '20.17.131.64/27'
  '20.17.168.24/29'
  '20.17.168.224/27'
  '20.17.184.24/29'
  '20.17.184.224/27'
  '2603:1040:1602:2::680/123'
  '2603:1040:1602:2::700/121'
]
