// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : Sql.PolandCentral

var Sql_PolandCentral = [
  '20.215.13.0/27'
  '20.215.13.64/26'
  '20.215.16.64/27'
  '20.215.17.64/27'
  '20.215.19.192/29'
  '20.215.24.64/27'
  '20.215.25.64/27'
  '20.215.27.192/29'
  '20.215.152.64/27'
  '20.215.153.64/27'
  '20.215.155.248/29'
  '20.215.171.128/25'
  '2603:1020:1302:2::100/123'
  '2603:1020:1302:2::180/121'
  '2603:1020:1302:2::780/121'
]
