// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : Sql.DenmarkEast

var Sql_DenmarkEast = [
  '9.205.48.96/27'
  '9.205.48.128/26'
  '9.205.50.96/27'
  '9.205.72.48/29'
  '9.205.72.224/27'
  '9.205.96.48/29'
  '9.205.96.224/27'
  '9.205.112.48/29'
  '9.205.112.224/27'
  '2603:1020:1602:2::620/123'
  '2603:1020:1602:2::680/121'
]
