// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : Sql.SouthCentralUSSTG

var Sql_SouthCentralUSSTG = [
  '20.44.0.0/27'
  '20.44.1.0/27'
]
