// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-09
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 407
// Service tag  : Sql.NortheastUS5

var Sql_NortheastUS5 = [
  '172.194.84.96/27'
  '172.194.84.128/27'
  '172.194.84.192/26'
  '2603:1030:1602:3::380/123'
  '2603:1030:1602:3::400/121'
]
