// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-21
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 396
// Service tag  : AzureAttestation.EastUS2EUAP

var AzureAttestation_EastUS2EUAP = [
  '20.51.20.80/30'
  '40.89.121.168/30'
  '48.223.29.136/29'
]
