// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-21
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 396
// Service tag  : AzureAttestation.SwedenCentral

var AzureAttestation_SwedenCentral = [
  '4.223.182.184/29'
  '51.12.46.224/30'
  '2603:1020:1004:1::720/123'
]
