// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_AzureGermany.json
// Cloud        : AzureGermany
// Service tag  : BatchNodeManagement.GermanyNorthEast

@export()
var BatchNodeManagement_GermanyNorthEast = [
  '51.5.144.140/31'
]
