// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : GatewayManager.AustraliaSoutheast
metadata name = 'GatewayManager.AustraliaSoutheast'
metadata description = 'This module contains all the service tag IP addresses of GatewayManager.AustraliaSoutheast for Public.'
metadata author = ''
metadata author = ''

@description('GatewayManager.AustraliaSoutheast service tag IP addresses for Public')
@export()
var GatewayManager_AustraliaSoutheast = [
  '4.199.82.192/26'
  '13.77.50.88/29'
  '20.40.173.147/32'
  '20.42.224.72/29'
  '20.92.4.224/27'
  '52.147.44.33/32'
  '2603:1010:101::40/122'
]
