// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : GatewayManager.BelgiumCentral

var GatewayManager_BelgiumCentral = [
  '9.160.40.64/26'
  '9.160.171.112/28'
  '2603:1020:1502::40/122'
]
