// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : GatewayManager.SoutheastAsia
metadata name = 'GatewayManager.SoutheastAsia'
metadata description = 'This module contains all the service tag IP addresses of GatewayManager.SoutheastAsia for Public.'
metadata author = ''
metadata author = ''

@description('GatewayManager.SoutheastAsia service tag IP addresses for Public')
@export()
var GatewayManager_SoutheastAsia = [
  '4.145.21.64/27'
  '13.67.9.128/29'
  '20.43.128.72/29'
  '20.195.37.65/32'
  '20.195.38.22/32'
  '20.195.86.96/27'
  '40.90.186.21/32'
  '40.90.186.91/32'
  '2603:1040:5:1::40/122'
]
