// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : GatewayManager.SwedenCentral

var GatewayManager_SwedenCentral = [
  '4.166.32.64/28'
  '51.12.40.192/26'
  '2603:1020:1004::40/122'
]
