// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : GatewayManager.NewZealandNorth

var GatewayManager_NewZealandNorth = [
  '172.196.72.160/28'
  '172.204.152.64/26'
  '2603:1010:502::40/122'
]
