// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : GatewayManager.GermanyWestCentral

var GatewayManager_GermanyWestCentral = [
  '20.52.95.96/27'
  '48.201.167.160/27'
  '51.116.144.72/29'
  '51.116.155.96/29'
  '2603:1020:c04:1::40/122'
]
