// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : GatewayManager.TaiwanNorthwest

var GatewayManager_TaiwanNorthwest = [
  '51.53.168.64/26'
  '167.105.251.240/28'
  '2603:1040:1202::40/122'
]
