// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : GatewayManager.FranceSouth
metadata name = 'GatewayManager.FranceSouth'
metadata description = 'This module contains all the service tag IP addresses of GatewayManager.FranceSouth for Public.'
metadata author = ''
metadata author = ''

@description('GatewayManager.FranceSouth service tag IP addresses for Public')
@export()
var GatewayManager_FranceSouth = [
  '40.79.178.88/29'
  '40.80.105.224/27'
  '40.82.236.2/32'
  '40.82.236.13/32'
  '51.105.88.72/29'
  '52.136.191.96/27'
  '2603:1020:905::40/122'
]
