// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : GatewayManager.MexicoCentral

var GatewayManager_MexicoCentral = [
  '158.23.96.64/26'
  '172.195.113.144/28'
  '2603:1030:702::40/122'
]
