// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : GatewayManager.CentralUS

@export()
var GatewayManager_CentralUS = [
  '13.89.171.96/29'
  '20.37.152.72/29'
  '20.98.130.16/32'
  '20.118.195.160/27'
  '52.143.250.137/32'
  '52.143.251.22/32'
  '172.170.121.128/27'
  '2603:1030:10:1::40/122'
]
