// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : GatewayManager.NewZealandNorth
metadata name = 'GatewayManager.NewZealandNorth'
metadata description = 'This module contains all the service tag IP addresses of GatewayManager.NewZealandNorth for Public.'
metadata author = ''
metadata author = ''

@description('GatewayManager.NewZealandNorth service tag IP addresses for Public')
@export()
var GatewayManager_NewZealandNorth = [
  '172.196.72.160/28'
  '172.204.152.64/26'
  '2603:1010:502::40/122'
]
