// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-21
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 396
// Service tag  : GatewayManager.SwitzerlandWest

var GatewayManager_SwitzerlandWest = [
  '4.226.255.128/27'
  '20.199.200.128/27'
  '51.107.144.72/29'
  '51.107.155.32/29'
  '2603:1020:b04::40/122'
]
