// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : GatewayManager.SoutheastUS3

var GatewayManager_SoutheastUS3 = [
  '74.7.40.64/26'
  '74.7.67.192/28'
  '2603:1030:1302::40/122'
]
