// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : GatewayManager.WestEurope

var GatewayManager_WestEurope = [
  '13.69.64.224/29'
  '20.71.77.117/32'
  '20.71.77.160/32'
  '20.105.210.128/27'
  '40.74.24.72/29'
  '48.199.250.192/27'
  '2603:1020:206:1::40/122'
]
