// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-10
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : GatewayManager.EastAsia

var GatewayManager_EastAsia = [
  '13.75.36.8/29'
  '20.189.104.72/29'
  '20.195.78.0/26'
  '2603:1040:207::40/122'
]
