// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : GatewayManager.NorwayEast

var GatewayManager_NorwayEast = [
  '51.120.40.72/29'
  '51.120.98.168/29'
  '51.120.235.128/26'
  '2603:1020:e04:1::40/122'
]
