// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : GatewayManager.SouthCentralUS2

@export()
var GatewayManager_SouthCentralUS2 = [
  '48.216.16.64/26'
  '48.219.10.16/28'
  '2603:1030:1102::40/122'
]
