// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : GatewayManager.IndonesiaCentral

var GatewayManager_IndonesiaCentral = [
  '48.193.55.64/28'
  '70.153.152.64/26'
  '2603:1040:1802:2::700/122'
]
