// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-06-08
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 403
// Service tag  : GatewayManager.DenmarkEast

var GatewayManager_DenmarkEast = [
  '9.205.32.64/26'
  '9.205.67.96/28'
  '2603:1020:1602::40/122'
]
