// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-06-22
// Source file  : ServiceTags_AzureGovernment.json
// Cloud        : AzureGovernment
// Change number: 397
// Service tag  : AzureAttestation.USGovArizona

var AzureAttestation_USGovArizona = [
  '20.140.53.116/30'
  '51.54.231.96/29'
  '51.54.253.24/29'
  '51.54.253.32/30'
  '52.127.12.48/30'
  '2001:489a:3604:2::700/124'
]
