// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-09
// Source file  : ServiceTags_AzureGovernment.json
// Cloud        : AzureGovernment
// Change number: 399
// Service tag  : AzureAttestation.USDoDEast

var AzureAttestation_USDoDEast = [
  '20.140.68.180/30'
  '52.181.221.48/29'
  '52.181.221.56/30'
  '52.245.136.40/30'
]
