// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_AzureGovernment.json
// Cloud        : AzureGovernment
// Change number: 390
// Service tag  : AzureAttestation.USGovIowa

var AzureAttestation_USGovIowa = [
  '20.140.154.84/30'
  '52.127.29.128/30'
]
