// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_AzureGovernment.json
// Cloud        : AzureGovernment
// Service tag  : AzureAttestation.USGovVirginia
metadata name = 'AzureAttestation.USGovVirginia'
metadata description = 'This module contains all the service tag IP addresses of AzureAttestation.USGovVirginia for AzureGovernment.'
metadata author = ''
metadata author = ''

@description('AzureAttestation.USGovVirginia service tag IP addresses for AzureGovernment')
@export()
var AzureAttestation_USGovVirginia = [
  '20.140.94.140/30'
  '51.54.170.216/29'
  '51.55.174.44/30'
  '51.55.174.48/29'
  '52.127.55.156/30'
]
