// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : HDInsight.WestUS2

var HDInsight_WestUS2 = [
  '13.66.141.144/29'
  '40.64.134.160/29'
  '52.175.211.210/32'
  '52.175.222.222/32'
  '2603:1030:c06:400::b20/124'
]
