// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : HDInsight.PolandCentral

@export()
var HDInsight_PolandCentral = [
  '20.215.6.136/29'
  '2603:1020:1302:1::540/124'
]
