// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : HDInsight.JioIndiaWest

var HDInsight_JioIndiaWest = [
  '20.193.194.16/29'
  '20.193.203.200/29'
  '2603:1040:d04:1::1e0/124'
]
