// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : HDInsight.SouthCentralUSSTG

var HDInsight_SouthCentralUSSTG = [
  '20.44.4.64/29'
  '20.45.115.128/29'
]
