// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : HDInsight.SwitzerlandWest
metadata name = 'HDInsight.SwitzerlandWest'
metadata description = 'This module contains all the service tag IP addresses of HDInsight.SwitzerlandWest for Public.'
metadata author = ''
metadata author = ''

@description('HDInsight.SwitzerlandWest service tag IP addresses for Public')
@export()
var HDInsight_SwitzerlandWest = [
  '51.107.148.24/29'
  '51.107.156.56/29'
  '2603:1020:b04:5::350/124'
  '2603:1020:b04:402::320/124'
]
