// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : HDInsight.SouthAfricaNorth

var HDInsight_SouthAfricaNorth = [
  '102.133.124.0/29'
  '102.133.219.176/29'
  '2603:1000:104:402::320/124'
]
