// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : HDInsight.WestUS3

var HDInsight_WestUS3 = [
  '20.150.167.176/29'
  '20.150.172.232/29'
  '172.182.175.168/29'
  '2603:1030:504::1e0/124'
]
