// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : HDInsight.KoreaSouth

var HDInsight_KoreaSouth = [
  '40.80.172.120/29'
  '52.231.147.24/29'
  '52.231.203.16/32'
  '52.231.205.214/32'
  '2603:1040:e05:5::4b0/124'
]
