// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-10
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : HDInsight.SwedenCentral

var HDInsight_SwedenCentral = [
  '51.12.25.48/29'
  '2603:1020:1004:1::1e0/124'
]
