// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : HDInsight.IndonesiaCentral

@export()
var HDInsight_IndonesiaCentral = [
  '70.153.160.24/29'
  '2603:1040:1802:1::110/124'
]
