// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-21
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 396
// Service tag  : HDInsight.WestIndia

var HDInsight_WestIndia = [
  '52.136.52.40/29'
  '2603:1040:806:3::600/124'
  '2603:1040:806:402::320/124'
]
