// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : HDInsight.EastUS2EUAP
metadata name = 'HDInsight.EastUS2EUAP'
metadata description = 'This module contains all the service tag IP addresses of HDInsight.EastUS2EUAP for Public.'
metadata author = ''
metadata author = ''

@description('HDInsight.EastUS2EUAP service tag IP addresses for Public')
@export()
var HDInsight_EastUS2EUAP = [
  '20.39.15.48/29'
  '40.74.146.88/29'
  '40.89.65.220/32'
  '40.89.68.134/32'
  '68.220.123.200/29'
  '2603:1030:40b:400::b20/124'
]
