// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : HDInsight.ItalyNorth

var HDInsight_ItalyNorth = [
  '4.232.30.208/29'
  '2603:1020:1204:1::290/124'
]
