// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : HDInsight.AustraliaCentral2

var HDInsight_AustraliaCentral2 = [
  '20.36.123.88/29'
  '2603:1010:404:5::1f0/124'
  '2603:1010:404:402::320/124'
]
