// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : HDInsight.EastUS3

var HDInsight_EastUS3 = [
  '134.138.73.152/29'
  '2603:1030:1402:1::490/124'
]
