// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : HDInsight.ChileCentral

var HDInsight_ChileCentral = [
  '68.211.7.80/29'
  '2603:1050:301:1::360/124'
]
