// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_AzureGovernment.json
// Cloud        : AzureGovernment
// Change number: 390
// Service tag  : HDInsight.USGovTexas

var HDInsight_USGovTexas = [
  '20.140.59.56/29'
  '52.127.34.200/29'
  '52.238.112.86/32'
  '52.238.116.212/32'
  '2001:489a:3403:1::300/124'
  '2001:489a:3403:402::320/124'
]
