// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_China.json
// Cloud        : China
// Change number: 393
// Service tag  : AppServiceManagement.ChinaNorth2

var AppServiceManagement_ChinaNorth2 = [
  '40.73.136.128/26'
  '52.131.66.64/28'
  '2404:7940:101:2::200/123'
  '2404:7940:101:402::900/122'
]
