// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_China.json
// Cloud        : China
// Service tag  : AppServiceManagement.ChinaNorth2
metadata name = 'AppServiceManagement.ChinaNorth2'
metadata description = 'This module contains all the service tag IP addresses of AppServiceManagement.ChinaNorth2 for China.'
metadata author = ''
metadata author = ''

@description('AppServiceManagement.ChinaNorth2 service tag IP addresses for China')
@export()
var AppServiceManagement_ChinaNorth2 = [
  '40.73.136.128/26'
  '52.131.66.64/28'
  '2404:7940:101:2::200/123'
  '2404:7940:101:402::900/122'
]
