// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureDataLake.EastUS2

@export()
var AzureDataLake_EastUS2 = [
  '65.52.108.31/32'
  '65.52.108.38/32'
  '104.44.88.106/31'
  '104.44.88.112/31'
]
