// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : AzureDataLake.AustraliaSoutheast

var AzureDataLake_AustraliaSoutheast = [
  '40.90.138.133/32'
  '40.90.138.136/32'
]
