// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureDataLake.SoutheastAsia

var AzureDataLake_SoutheastAsia = [
  '104.44.89.39/32'
  '104.44.89.42/32'
  '104.44.90.128/27'
]
