// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : AzureDataLake.WestEurope

var AzureDataLake_WestEurope = [
  '40.90.141.167/32'
  '40.90.145.192/27'
  '104.44.90.194/31'
]
