// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureDataLake.CentralUS

var AzureDataLake_CentralUS = [
  '104.44.88.176/31'
  '104.44.88.184/29'
  '104.44.91.160/27'
]
