// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureDevSpaces.EastAsia

var AzureDevSpaces_EastAsia = [
  '20.189.108.32/28'
  '104.214.161.48/28'
]
