// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureDevSpaces.WestUS2
metadata name = 'AzureDevSpaces.WestUS2'
metadata description = 'This module contains all the service tag IP addresses of AzureDevSpaces.WestUS2 for Public.'
metadata author = ''
metadata author = ''

@description('AzureDevSpaces.WestUS2 service tag IP addresses for Public')
@export()
var AzureDevSpaces_WestUS2 = [
  '20.42.131.192/27'
  '40.78.251.224/27'
]
