// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 407
// Service tag  : AzureDevSpaces.CanadaEast

var AzureDevSpaces_CanadaEast = [
  '40.69.110.176/28'
  '40.89.17.192/28'
]
