// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : AzureDevSpaces.NorthEurope

var AzureDevSpaces_NorthEurope = [
  '13.74.111.128/28'
  '20.38.85.128/28'
]
