// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : AzureDevSpaces.WestUS2

var AzureDevSpaces_WestUS2 = [
  '20.42.131.192/27'
  '40.78.251.224/27'
]
