// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureDevSpaces.WestCentralUS

var AzureDevSpaces_WestCentralUS = [
  '13.71.199.96/28'
  '52.150.139.144/28'
]
