// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureDevSpaces.SouthCentralUS
metadata name = 'AzureDevSpaces.SouthCentralUS'
metadata description = 'This module contains all the service tag IP addresses of AzureDevSpaces.SouthCentralUS for Public.'
metadata author = ''
metadata author = ''

@description('AzureDevSpaces.SouthCentralUS service tag IP addresses for Public')
@export()
var AzureDevSpaces_SouthCentralUS = [
  '13.73.244.128/28'
  '40.119.9.240/28'
]
