// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-21
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 396
// Service tag  : AzureEventGrid.AustraliaSoutheast

var AzureEventGrid_AustraliaSoutheast = [
  '20.40.175.48/28'
  '20.40.175.64/28'
  '20.42.228.0/25'
  '2603:1010:101::380/121'
]
