// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureEventGrid.EastUS3

@export()
var AzureEventGrid_EastUS3 = [
  '51.57.182.0/23'
  '51.57.184.0/22'
  '51.57.188.0/23'
  '134.138.65.128/25'
  '2603:1030:1402::480/121'
]
