// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-06-15
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 404
// Service tag  : AzureEventGrid.SouthIndia

var AzureEventGrid_SouthIndia = [
  '20.41.195.0/25'
  '20.44.39.176/28'
  '20.44.39.192/28'
  '74.224.230.0/23'
  '74.224.232.0/22'
  '74.224.236.0/23'
  '2603:1040:c06::380/121'
]
