// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureEventGrid.NorthEurope
metadata name = 'AzureEventGrid.NorthEurope'
metadata description = 'This module contains all the service tag IP addresses of AzureEventGrid.NorthEurope for Public.'
metadata author = ''
metadata author = ''

@description('AzureEventGrid.NorthEurope service tag IP addresses for Public')
@export()
var AzureEventGrid_NorthEurope = [
  '4.209.102.128/25'
  '4.209.136.0/22'
  '4.209.140.0/23'
  '20.38.87.0/25'
  '20.191.59.128/28'
  '20.191.59.176/28'
  '40.127.155.192/28'
  '40.127.251.144/28'
  '68.219.195.0/24'
  '2603:1020:5:1::380/121'
]
