// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureEventGrid.SoutheastAsia

var AzureEventGrid_SoutheastAsia = [
  '20.43.131.128/25'
  '20.43.165.144/28'
  '20.43.172.128/27'
  '20.44.205.112/28'
  '57.155.33.0/25'
  '2603:1040:5:1::380/121'
]
