// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureEventGrid.PolandCentral
metadata name = 'AzureEventGrid.PolandCentral'
metadata description = 'This module contains all the service tag IP addresses of AzureEventGrid.PolandCentral for Public.'
metadata author = ''
metadata author = ''

@description('AzureEventGrid.PolandCentral service tag IP addresses for Public')
@export()
var AzureEventGrid_PolandCentral = [
  '20.215.1.128/25'
  '134.112.218.0/23'
  '134.112.220.0/22'
  '134.112.224.0/23'
  '2603:1020:1302::280/121'
]
