// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 407
// Service tag  : AzureEventGrid.CanadaCentral

var AzureEventGrid_CanadaCentral = [
  '4.173.28.0/22'
  '4.173.88.0/22'
  '52.139.9.80/28'
  '52.139.11.16/28'
  '52.228.83.0/25'
  '2603:1030:f05:1::380/121'
]
