// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureEventGrid.CanadaEast

var AzureEventGrid_CanadaEast = [
  '40.89.18.0/25'
  '52.139.85.16/28'
  '52.139.85.32/28'
  '2603:1030:1005::380/121'
]
