// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureEventGrid.BrazilSouth

var AzureEventGrid_BrazilSouth = [
  '191.235.126.0/28'
  '191.235.126.144/28'
  '191.235.227.0/25'
  '2603:1050:6:1::380/121'
]
