// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureEventGrid.SwedenSouth

var AzureEventGrid_SwedenSouth = [
  '51.12.199.0/25'
  '2603:1020:1104::280/121'
]
