// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-06-29
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 406
// Service tag  : AzureEventGrid.BrazilSouth

var AzureEventGrid_BrazilSouth = [
  '4.228.180.0/22'
  '4.228.240.0/22'
  '191.235.126.0/28'
  '191.235.126.144/28'
  '191.235.227.0/25'
  '2603:1050:6:1::380/121'
]
