// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 407
// Service tag  : AzureEventGrid.JapanWest

var AzureEventGrid_JapanWest = [
  '20.27.248.0/22'
  '20.27.252.0/23'
  '40.74.106.96/27'
  '40.80.58.0/25'
  '172.192.198.0/23'
  '2603:1040:606::380/121'
]
