// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureEventGrid.AustraliaCentral

var AzureEventGrid_AustraliaCentral = [
  '20.37.55.32/27'
  '20.37.225.0/25'
  '2603:1010:304::380/121'
]
