// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-06-29
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 406
// Service tag  : AzureEventGrid.CentralIndia

var AzureEventGrid_CentralIndia = [
  '4.188.34.0/23'
  '4.188.36.0/22'
  '4.188.48.0/23'
  '13.71.56.240/28'
  '13.71.57.0/28'
  '52.140.106.0/25'
  '2603:1040:a06:1::380/121'
]
