// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureEventGrid.UKWest

var AzureEventGrid_UKWest = [
  '51.137.142.32/28'
  '51.137.162.0/25'
  '52.142.152.144/28'
  '2603:1020:605::380/121'
]
