// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureEventGrid.SouthCentralUSSTG
metadata name = 'AzureEventGrid.SouthCentralUSSTG'
metadata description = 'This module contains all the service tag IP addresses of AzureEventGrid.SouthCentralUSSTG for Public.'
metadata author = ''
metadata author = ''

@description('AzureEventGrid.SouthCentralUSSTG service tag IP addresses for Public')
@export()
var AzureEventGrid_SouthCentralUSSTG = [
  '20.45.113.0/25'
  '57.152.162.0/23'
  '57.152.164.0/22'
  '57.152.168.0/23'
]
