// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureEventGrid.AustraliaCentral
metadata name = 'AzureEventGrid.AustraliaCentral'
metadata description = 'This module contains all the service tag IP addresses of AzureEventGrid.AustraliaCentral for Public.'
metadata author = ''
metadata author = ''

@description('AzureEventGrid.AustraliaCentral service tag IP addresses for Public')
@export()
var AzureEventGrid_AustraliaCentral = [
  '20.28.80.0/21'
  '20.37.55.32/27'
  '20.37.225.0/25'
  '2603:1010:304::380/121'
]
