// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-10
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureEventGrid.JioIndiaCentral

var AzureEventGrid_JioIndiaCentral = [
  '20.192.228.0/25'
  '20.207.28.0/22'
  '20.207.32.0/22'
  '2603:1040:1104::280/121'
]
