// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureEventGrid.WestUS3

var AzureEventGrid_WestUS3 = [
  '20.150.164.0/25'
  '2603:1030:504:1::380/121'
]
