// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureEventGrid.UAENorth

var AzureEventGrid_UAENorth = [
  '20.38.137.0/25'
  '20.46.152.112/28'
  '20.46.152.128/28'
  '2603:1040:904:1::380/121'
]
