// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureEventGrid.WestUS2

var AzureEventGrid_WestUS2 = [
  '40.64.128.0/25'
  '52.149.23.160/27'
  '52.149.48.80/28'
  '52.149.48.96/27'
  '52.156.103.192/28'
  '52.233.104.0/24'
  '52.250.28.176/28'
  '52.250.32.160/28'
  '2603:1030:c06:1::380/121'
]
