// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-10
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 407
// Service tag  : AzureEventGrid.JioIndiaWest

var AzureEventGrid_JioIndiaWest = [
  '4.187.32.0/23'
  '20.192.164.0/25'
  '20.244.226.0/23'
  '20.244.228.0/22'
  '2603:1040:d04::380/121'
]
