// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-21
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 396
// Service tag  : AzureEventGrid.KoreaSouth

var AzureEventGrid_KoreaSouth = [
  '40.80.170.0/25'
  '40.80.236.192/27'
  '2603:1040:e05:1::700/121'
]
