// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureEventGrid.MalaysiaSouth
metadata name = 'AzureEventGrid.MalaysiaSouth'
metadata description = 'This module contains all the service tag IP addresses of AzureEventGrid.MalaysiaSouth for Public.'
metadata author = ''
metadata author = ''

@description('AzureEventGrid.MalaysiaSouth service tag IP addresses for Public')
@export()
var AzureEventGrid_MalaysiaSouth = [
  '20.17.49.128/25'
  '172.197.34.0/23'
  '172.197.36.0/22'
  '172.197.40.0/23'
  '2603:1040:1503::280/121'
]
