// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : ApiManagement.IndonesiaCentral

var ApiManagement_IndonesiaCentral = [
  '70.153.154.240/28'
  '2603:1040:1802::2c0/124'
]
