// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : ApiManagement.WestCentralUS

@export()
var ApiManagement_WestCentralUS = [
  '13.71.194.116/31'
  '13.71.196.32/28'
  '52.253.135.58/32'
  '128.24.200.144/28'
  '2603:1030:b04:402::140/124'
]
