// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : ApiManagement.EastUS3

var ApiManagement_EastUS3 = [
  '134.138.70.16/28'
  '2603:1030:1402::740/124'
]
