// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : ApiManagement.ChileCentral
metadata name = 'ApiManagement.ChileCentral'
metadata description = 'This module contains all the service tag IP addresses of ApiManagement.ChileCentral for Public.'
metadata author = ''
metadata author = ''

@description('ApiManagement.ChileCentral service tag IP addresses for Public')
@export()
var ApiManagement_ChileCentral = [
  '68.211.4.48/28'
  '2603:1050:301::520/124'
]
