// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : ApiManagement.GermanyNorth
metadata name = 'ApiManagement.GermanyNorth'
metadata description = 'This module contains all the service tag IP addresses of ApiManagement.GermanyNorth for Public.'
metadata author = ''
metadata author = ''

@description('ApiManagement.GermanyNorth service tag IP addresses for Public')
@export()
var ApiManagement_GermanyNorth = [
  '20.113.251.240/28'
  '51.116.0.0/32'
  '51.116.59.0/28'
  '2603:1020:d04:2::630/124'
  '2603:1020:d04:402::140/124'
]
