// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : ApiManagement.TaiwanNorth

var ApiManagement_TaiwanNorth = [
  '51.53.27.224/28'
  '2603:1040:1302::560/124'
]
