// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : ApiManagement.ItalyNorth

@export()
var ApiManagement_ItalyNorth = [
  '4.232.28.0/28'
  '2603:1020:1204::5c0/124'
]
