// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : ApiManagement.SouthAfricaNorth
metadata name = 'ApiManagement.SouthAfricaNorth'
metadata description = 'This module contains all the service tag IP addresses of ApiManagement.SouthAfricaNorth for Public.'
metadata author = ''
metadata author = ''

@description('ApiManagement.SouthAfricaNorth service tag IP addresses for Public')
@export()
var ApiManagement_SouthAfricaNorth = [
  '102.37.166.220/31'
  '102.133.130.197/32'
  '102.133.154.4/31'
  '102.133.156.0/28'
  '172.209.191.124/31'
  '2603:1000:104:402::140/124'
]
