// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : ApiManagement.SpainCentral

@export()
var ApiManagement_SpainCentral = [
  '68.221.84.128/28'
  '2603:1020:1403::5c0/124'
]
