// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-10
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : ApiManagement.MalaysiaSouth

var ApiManagement_MalaysiaSouth = [
  '20.17.51.224/28'
  '2603:1040:1503::600/124'
]
