// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : ApiManagement.FranceSouth
metadata name = 'ApiManagement.FranceSouth'
metadata description = 'This module contains all the service tag IP addresses of ApiManagement.FranceSouth for Public.'
metadata author = ''
metadata author = ''

@description('ApiManagement.FranceSouth service tag IP addresses for Public')
@export()
var ApiManagement_FranceSouth = [
  '20.39.80.2/32'
  '20.111.111.0/28'
  '40.79.178.68/31'
  '40.79.179.192/28'
  '2603:1020:905:2::740/124'
  '2603:1020:905:402::140/124'
]
