// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : ApiManagement.JioIndiaCentral
metadata name = 'ApiManagement.JioIndiaCentral'
metadata description = 'This module contains all the service tag IP addresses of ApiManagement.JioIndiaCentral for Public.'
metadata author = ''
metadata author = ''

@description('ApiManagement.JioIndiaCentral service tag IP addresses for Public')
@export()
var ApiManagement_JioIndiaCentral = [
  '20.192.50.64/28'
  '20.192.234.160/28'
  '2603:1040:1104:1::400/124'
  '2603:1040:1104:400::140/124'
]
