// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : ApiManagement.SouthAfricaNorth

var ApiManagement_SouthAfricaNorth = [
  '102.37.166.220/31'
  '102.133.130.197/32'
  '102.133.154.4/31'
  '102.133.156.0/28'
  '172.209.191.124/31'
  '2603:1000:104:402::140/124'
]
