// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : ApiManagement.SwedenSouth

var ApiManagement_SwedenSouth = [
  '51.12.17.0/28'
  '51.12.202.224/28'
  '2603:1020:1104:1::3c0/124'
  '2603:1020:1104:400::140/124'
]
