// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-10
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : ApiManagement.SoutheastUS

var ApiManagement_SoutheastUS = [
  '57.151.210.240/28'
  '2603:1030:902::5a0/124'
]
