// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : MicrosoftContainerRegistry.BelgiumCentral

var MicrosoftContainerRegistry_BelgiumCentral = [
  '9.160.80.0/29'
  '9.160.88.0/29'
  '9.160.112.0/29'
  '2603:1020:1502:400::/125'
  '2603:1020:1502:800::/125'
  '2603:1020:1502:c00::/125'
]
