// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-10
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 408
// Service tag  : MicrosoftContainerRegistry.SoutheastUS

var MicrosoftContainerRegistry_SoutheastUS = [
  '68.154.136.0/29'
  '2603:1030:902:400::/125'
]
