// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-21
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 396
// Service tag  : MicrosoftContainerRegistry.TaiwanNorthwest

var MicrosoftContainerRegistry_TaiwanNorthwest = [
  '51.53.186.64/29'
  '2603:1040:1202:400::40/125'
]
