// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-06-08
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 403
// Service tag  : MicrosoftContainerRegistry.CanadaEast

var MicrosoftContainerRegistry_CanadaEast = [
  '40.69.106.72/29'
  '2603:1030:1005:402::88/125'
]
