// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : MicrosoftContainerRegistry.SoutheastUS3

var MicrosoftContainerRegistry_SoutheastUS3 = [
  '74.7.80.0/29'
  '2603:1030:1302:400::/125'
]
