// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-21
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 396
// Service tag  : MicrosoftContainerRegistry.SwitzerlandWest

var MicrosoftContainerRegistry_SwitzerlandWest = [
  '51.107.154.16/29'
  '2603:1020:b04:402::88/125'
]
