// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : MicrosoftContainerRegistry.GermanyNorth

var MicrosoftContainerRegistry_GermanyNorth = [
  '51.116.58.16/29'
  '2603:1020:d04:402::88/125'
]
