// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : MicrosoftContainerRegistry.WestUS3
metadata name = 'MicrosoftContainerRegistry.WestUS3'
metadata description = 'This module contains all the service tag IP addresses of MicrosoftContainerRegistry.WestUS3 for Public.'
metadata author = ''
metadata author = ''

@description('MicrosoftContainerRegistry.WestUS3 service tag IP addresses for Public')
@export()
var MicrosoftContainerRegistry_WestUS3 = [
  '4.236.112.0/29'
  '20.150.170.16/29'
  '20.150.178.136/29'
  '20.150.186.136/29'
  '2603:1030:504:402::88/125'
  '2603:1030:504:402::3b0/125'
  '2603:1030:504:802::148/125'
  '2603:1030:504:802::3e8/125'
  '2603:1030:504:c02::398/125'
  '2603:1030:504:1000::/125'
]
