// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-21
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 396
// Service tag  : MicrosoftContainerRegistry.SouthAfricaWest

var MicrosoftContainerRegistry_SouthAfricaWest = [
  '102.133.26.16/29'
  '2603:1000:4:402::88/125'
]
