// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : MicrosoftContainerRegistry.TaiwanNorth
metadata name = 'MicrosoftContainerRegistry.TaiwanNorth'
metadata description = 'This module contains all the service tag IP addresses of MicrosoftContainerRegistry.TaiwanNorth for Public.'
metadata author = ''
metadata author = ''

@description('MicrosoftContainerRegistry.TaiwanNorth service tag IP addresses for Public')
@export()
var MicrosoftContainerRegistry_TaiwanNorth = [
  '51.53.106.64/29'
  '70.157.88.0/29'
  '167.105.104.0/29'
  '2603:1040:1302:400::40/125'
  '2603:1040:1302:800::10/125'
  '2603:1040:1302:c00::10/125'
]
