// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : MicrosoftContainerRegistry.WestIndia

var MicrosoftContainerRegistry_WestIndia = [
  '104.211.146.72/29'
  '2603:1040:806:402::88/125'
]
