// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : MicrosoftContainerRegistry.DenmarkEast
metadata name = 'MicrosoftContainerRegistry.DenmarkEast'
metadata description = 'This module contains all the service tag IP addresses of MicrosoftContainerRegistry.DenmarkEast for Public.'
metadata author = ''
metadata author = ''

@description('MicrosoftContainerRegistry.DenmarkEast service tag IP addresses for Public')
@export()
var MicrosoftContainerRegistry_DenmarkEast = [
  '9.205.72.0/29'
  '9.205.96.0/29'
  '9.205.112.0/29'
  '2603:1020:1602:400::/125'
  '2603:1020:1602:800::/125'
  '2603:1020:1602:c00::/125'
]
