// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : MicrosoftContainerRegistry.NortheastUS5

@export()
var MicrosoftContainerRegistry_NortheastUS5 = [
  '172.194.86.160/29'
  '172.194.112.104/29'
  '2603:1030:1602:3::3b8/125'
  '2603:1030:1602:400::10/125'
]
