// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : MicrosoftContainerRegistry.CanadaEast
metadata name = 'MicrosoftContainerRegistry.CanadaEast'
metadata description = 'This module contains all the service tag IP addresses of MicrosoftContainerRegistry.CanadaEast for Public.'
metadata author = ''
metadata author = ''

@description('MicrosoftContainerRegistry.CanadaEast service tag IP addresses for Public')
@export()
var MicrosoftContainerRegistry_CanadaEast = [
  '40.69.106.72/29'
  '2603:1030:1005:402::88/125'
]
