// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : MicrosoftContainerRegistry.PolandCentral
metadata name = 'MicrosoftContainerRegistry.PolandCentral'
metadata description = 'This module contains all the service tag IP addresses of MicrosoftContainerRegistry.PolandCentral for Public.'
metadata author = ''
metadata author = ''

@description('MicrosoftContainerRegistry.PolandCentral service tag IP addresses for Public')
@export()
var MicrosoftContainerRegistry_PolandCentral = [
  '20.215.18.64/29'
  '20.215.26.64/29'
  '20.215.154.64/29'
  '2603:1020:1302:400::40/125'
  '2603:1020:1302:800::40/125'
  '2603:1020:1302:c00::40/125'
]
