// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : MicrosoftContainerRegistry.CanadaCentral
metadata name = 'MicrosoftContainerRegistry.CanadaCentral'
metadata description = 'This module contains all the service tag IP addresses of MicrosoftContainerRegistry.CanadaCentral for Public.'
metadata author = ''
metadata author = ''

@description('MicrosoftContainerRegistry.CanadaCentral service tag IP addresses for Public')
@export()
var MicrosoftContainerRegistry_CanadaCentral = [
  '13.71.170.48/29'
  '20.38.146.136/29'
  '52.246.154.136/29'
  '2603:1030:f05:402::88/125'
  '2603:1030:f05:802::88/125'
  '2603:1030:f05:c02::88/125'
]
