// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : MicrosoftContainerRegistry.CentralIndia
metadata name = 'MicrosoftContainerRegistry.CentralIndia'
metadata description = 'This module contains all the service tag IP addresses of MicrosoftContainerRegistry.CentralIndia for Public.'
metadata author = ''
metadata author = ''

@description('MicrosoftContainerRegistry.CentralIndia service tag IP addresses for Public')
@export()
var MicrosoftContainerRegistry_CentralIndia = [
  '20.192.98.136/29'
  '40.80.50.136/29'
  '104.211.81.128/29'
  '2603:1040:a06:402::88/125'
  '2603:1040:a06:802::88/125'
  '2603:1040:a06:c02::88/125'
]
