// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_AzureGovernment.json
// Cloud        : AzureGovernment
// Service tag  : PowerPlatformInfra.USDoDEast
metadata name = 'PowerPlatformInfra.USDoDEast'
metadata description = 'This module contains all the service tag IP addresses of PowerPlatformInfra.USDoDEast for AzureGovernment.'
metadata author = ''
metadata author = ''

@description('PowerPlatformInfra.USDoDEast service tag IP addresses for AzureGovernment')
@export()
var PowerPlatformInfra_USDoDEast = [
  '20.140.66.144/28'
  '20.140.66.160/28'
  '20.140.66.192/26'
  '20.140.68.152/29'
  '20.140.110.192/26'
  '52.181.33.3/32'
  '52.181.33.7/32'
  '52.181.67.0/25'
  '2001:489a:2102:1880::/58'
]
