// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_AzureGovernment.json
// Cloud        : AzureGovernment
// Service tag  : PowerPlatformInfra.USDoDCentral
metadata name = 'PowerPlatformInfra.USDoDCentral'
metadata description = 'This module contains all the service tag IP addresses of PowerPlatformInfra.USDoDCentral for AzureGovernment.'
metadata author = ''
metadata author = ''

@description('PowerPlatformInfra.USDoDCentral service tag IP addresses for AzureGovernment')
@export()
var PowerPlatformInfra_USDoDCentral = [
  '20.140.74.144/28'
  '20.140.74.160/28'
  '20.140.74.192/26'
  '20.140.76.160/29'
  '20.159.244.128/25'
  '52.126.254.192/26'
  '52.182.32.2/32'
  '52.182.32.218/32'
  '2001:489a:2102:1800::/58'
]
