// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_AzureGovernment.json
// Cloud        : AzureGovernment
// Service tag  : MicrosoftCloudAppSecurity.USDoDCentral
metadata name = 'MicrosoftCloudAppSecurity.USDoDCentral'
metadata description = 'This module contains all the service tag IP addresses of MicrosoftCloudAppSecurity.USDoDCentral for AzureGovernment.'
metadata author = ''
metadata author = ''

@description('MicrosoftCloudAppSecurity.USDoDCentral service tag IP addresses for AzureGovernment')
@export()
var MicrosoftCloudAppSecurity_USDoDCentral = [
  '20.158.152.128/31'
  '52.126.255.56/29'
  '52.182.52.21/32'
  '52.182.52.82/32'
  '52.182.52.187/32'
]
