// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_AzureGovernment.json
// Cloud        : AzureGovernment
// Service tag  : MicrosoftCloudAppSecurity.USDoDEast

@export()
var MicrosoftCloudAppSecurity_USDoDEast = [
  '20.140.105.4/31'
  '20.140.105.48/29'
  '20.140.106.12/31'
  '20.140.106.16/28'
  '20.140.106.32/27'
  '20.140.111.144/29'
  '20.140.111.152/31'
  '52.126.203.208/28'
]
