// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_AzureGovernment.json
// Cloud        : AzureGovernment
// Change number: 390
// Service tag  : GatewayManager.USGovTexas

var GatewayManager_USGovTexas = [
  '20.140.56.72/29'
  '20.140.147.224/27'
  '52.127.34.176/29'
  '62.11.87.0/26'
  '2001:489a:3403::40/122'
]
