// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-21
// Source file  : ServiceTags_China.json
// Cloud        : China
// Change number: 391
// Service tag  : AzureDigitalTwins.ChinaEast

var AzureDigitalTwins_ChinaEast = [
  '40.72.169.96/27'
  '40.72.169.128/29'
]
