// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-21
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 396
// Service tag  : AzureDigitalTwins.JioIndiaWest

var AzureDigitalTwins_JioIndiaWest = [
  '20.192.166.176/29'
  '20.192.167.128/27'
  '2603:1040:d04:1::540/122'
  '2603:1040:d04:2::80/121'
]
