// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-21
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 396
// Service tag  : AzureDigitalTwins.SouthIndia

var AzureDigitalTwins_SouthIndia = [
  '52.172.112.168/29'
  '52.172.113.0/27'
  '2603:1040:c06:3::300/121'
]
