// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-21
// Source file  : ServiceTags_AzureGermany.json
// Cloud        : AzureGermany
// Change number: 193
// Service tag  : ApiManagement.GermanyCentral

var ApiManagement_GermanyCentral = [
  '51.8.234.232/31'
  '51.8.235.160/28'
]
