// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_AzureGermany.json
// Cloud        : AzureGermany
// Service tag  : ApiManagement.GermanyNorthEast
metadata name = 'ApiManagement.GermanyNorthEast'
metadata description = 'This module contains all the service tag IP addresses of ApiManagement.GermanyNorthEast for AzureGermany.'
metadata author = ''
metadata author = ''

@description('ApiManagement.GermanyNorthEast service tag IP addresses for AzureGermany')
@export()
var ApiManagement_GermanyNorthEast = [
  '51.8.226.224/31'
  '51.8.227.160/28'
]
