// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_AzureGovernment.json
// Cloud        : AzureGovernment
// Service tag  : PowerBI.USGovTexas
metadata name = 'PowerBI.USGovTexas'
metadata description = 'This module contains all the service tag IP addresses of PowerBI.USGovTexas for AzureGovernment.'
metadata author = ''
metadata author = ''

@description('PowerBI.USGovTexas service tag IP addresses for AzureGovernment')
@export()
var PowerBI_USGovTexas = [
  '20.140.56.118/31'
  '20.140.56.144/28'
  '20.140.56.192/26'
  '51.54.53.96/28'
  '51.54.198.16/28'
  '51.54.198.48/28'
  '2001:489a:3403::620/123'
  '2001:489a:3403::640/122'
]
