// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-10
// Source file  : ServiceTags_China.json
// Cloud        : China
// Service tag  : AzureDigitalTwins.ChinaNorth2

var AzureDigitalTwins_ChinaNorth2 = [
  '52.131.66.104/29'
  '52.131.66.128/27'
]
