// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_China.json
// Cloud        : China
// Change number: 392
// Service tag  : AzureDigitalTwins.ChinaNorth3

var AzureDigitalTwins_ChinaNorth3 = [
  '52.131.20.64/27'
  '2406:e500:2602:1::100/121'
]
