// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_China.json
// Cloud        : China
// Change number: 393
// Service tag  : AzureDigitalTwins.ChinaEast3

var AzureDigitalTwins_ChinaEast3 = [
  '52.131.148.64/27'
  '2406:e500:2402:1::100/121'
]
