// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_China.json
// Cloud        : China
// Change number: 393
// Service tag  : PowerPlatformPlex.ChinaEast2

var PowerPlatformPlex_ChinaEast2 = [
  '52.131.194.252/30'
  '52.131.245.128/26'
  '163.228.216.88/29'
  '2406:e500:5501:1080::/58'
]
