// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_China.json
// Cloud        : China
// Change number: 393
// Service tag  : AzureDatabricks

var AzureDatabricks = [
  '52.130.1.64/29'
  '52.130.2.232/29'
  '52.130.16.112/29'
  '52.130.224.0/27'
  '52.131.16.32/29'
  '52.131.30.176/29'
  '52.131.144.32/29'
  '139.217.120.0/26'
  '159.27.198.24/29'
  '159.27.205.240/29'
  '163.228.32.0/26'
  '163.228.200.0/26'
  '2404:7940:101::160/123'
  '2404:7940:301::160/123'
  '2406:e500:2402::520/123'
  '2406:e500:2602::520/123'
]
