// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_AzureGermany.json
// Cloud        : AzureGermany
// Service tag  : HDInsight
metadata name = 'HDInsight'
metadata description = 'This module contains all the service tag IP addresses of HDInsight for AzureGermany.'
metadata author = ''
metadata author = ''

@description('HDInsight service tag IP addresses for AzureGermany')
@export()
var HDInsight = [
  '51.4.146.68/32'
  '51.4.146.80/32'
  '51.5.144.101/32'
  '51.5.150.132/32'
  '51.8.226.232/29'
  '51.8.234.248/29'
]
