// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_AzureGovernment.json
// Cloud        : AzureGovernment
// Change number: 390
// Service tag  : AzureBackup.USDoDEast

var AzureBackup_USDoDEast = [
  '20.140.69.128/26'
  '52.126.202.192/26'
  '52.126.203.0/27'
  '2001:489a:3303:402::200/121'
  '2001:489a:3303:802::180/121'
  '2001:489a:3303:c02::100/121'
]
