// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_AzureGovernment.json
// Cloud        : AzureGovernment
// Change number: 390
// Service tag  : AzureBackup.USGovArizona

var AzureBackup_USGovArizona = [
  '20.140.53.240/28'
  '51.54.224.0/27'
  '51.54.224.32/28'
  '52.127.3.0/26'
  '52.127.3.64/27'
  '52.127.15.128/26'
  '52.127.23.128/26'
  '2001:489a:3604:2::780/121'
  '2001:489a:3604:402::200/121'
  '2001:489a:3604:802::180/121'
  '2001:489a:3604:c02::100/121'
]
