// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-10
// Source file  : ServiceTags_AzureGovernment.json
// Cloud        : AzureGovernment
// Service tag  : WindowsVirtualDesktop.USDoDCentral

var WindowsVirtualDesktop_USDoDCentral = [
  '2001:489a:2104::/117'
]
