// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_AzureGovernment.json
// Cloud        : AzureGovernment
// Change number: 390
// Service tag  : WindowsVirtualDesktop.USGovVirginia

var WindowsVirtualDesktop_USGovVirginia = [
  '20.159.80.112/28'
  '20.159.80.176/28'
  '2001:489a:2104:5::/117'
]
