// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_AzureGovernment.json
// Cloud        : AzureGovernment
// Service tag  : WindowsVirtualDesktop.USGovArizona

@export()
var WindowsVirtualDesktop_USGovArizona = [
  '20.159.80.96/28'
  '20.159.80.160/28'
  '2001:489a:2104:2::/117'
]
