// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureResourceManager.MalaysiaWest
metadata name = 'AzureResourceManager.MalaysiaWest'
metadata description = 'This module contains all the service tag IP addresses of AzureResourceManager.MalaysiaWest for Public.'
metadata author = ''
metadata author = ''

@description('AzureResourceManager.MalaysiaWest service tag IP addresses for Public')
@export()
var AzureResourceManager_MalaysiaWest = [
  '20.17.122.0/23'
  '2603:1040:1602:1::400/120'
]
