// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureResourceManager.UKWest

var AzureResourceManager_UKWest = [
  '20.58.64.0/23'
  '51.11.96.0/24'
  '51.140.212.16/28'
  '51.140.214.0/24'
  '2603:1020:605::6c0/122'
  '2603:1020:605:3::700/120'
  '2603:1020:605:402::280/122'
]
