// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureResourceManager.SouthCentralUS

var AzureResourceManager_SouthCentralUS = [
  '13.73.240.224/28'
  '13.73.246.0/23'
  '20.65.128.0/23'
  '2603:1030:807::180/122'
  '2603:1030:807:402::280/122'
]
