// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureResourceManager.EastUSSTG
metadata name = 'AzureResourceManager.EastUSSTG'
metadata description = 'This module contains all the service tag IP addresses of AzureResourceManager.EastUSSTG for Public.'
metadata author = ''
metadata author = ''

@description('AzureResourceManager.EastUSSTG service tag IP addresses for Public')
@export()
var AzureResourceManager_EastUSSTG = [
  '40.67.54.0/23'
  '40.67.59.208/28'
  '40.67.62.0/23'
  '2603:1030:104::180/122'
  '2603:1030:104:402::280/122'
]
