// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureResourceManager.TaiwanNorthwest

@export()
var AzureResourceManager_TaiwanNorthwest = [
  '51.53.180.0/23'
  '51.53.188.0/26'
  '2603:1040:1202:1::500/120'
  '2603:1040:1202:400::1c0/122'
]
