// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureResourceManager.BelgiumCentral

var AzureResourceManager_BelgiumCentral = [
  '9.160.48.0/23'
  '2603:1020:1502:1::300/120'
]
