// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureResourceManager.SwedenCentral
metadata name = 'AzureResourceManager.SwedenCentral'
metadata description = 'This module contains all the service tag IP addresses of AzureResourceManager.SwedenCentral for Public.'
metadata author = ''
metadata author = ''

@description('AzureResourceManager.SwedenCentral service tag IP addresses for Public')
@export()
var AzureResourceManager_SwedenCentral = [
  '51.12.44.0/23'
  '51.12.101.64/26'
  '2603:1020:1004:1::400/120'
  '2603:1020:1004:400::180/122'
]
