// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureResourceManager.JapanWest

var AzureResourceManager_JapanWest = [
  '20.189.226.0/23'
  '40.74.102.0/28'
  '40.80.178.0/23'
  '2603:1040:606::6c0/122'
  '2603:1040:606:3::400/120'
  '2603:1040:606:402::280/122'
]
