// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-10
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 407
// Service tag  : AzureResourceManager.JioIndiaCentral

var AzureResourceManager_JioIndiaCentral = [
  '20.192.32.128/26'
  '20.192.52.0/23'
  '2603:1040:1104:1::/120'
  '2603:1040:1104:400::280/122'
]
