// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : AzureResourceManager.AustraliaEast

var AzureResourceManager_AustraliaEast = [
  '13.70.74.64/28'
  '13.70.76.0/23'
  '20.53.42.0/23'
  '2603:1010:6::180/122'
  '2603:1010:6:402::280/122'
]
