// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureResourceManager.UKSouth

var AzureResourceManager_UKSouth = [
  '51.104.8.224/28'
  '51.105.78.0/23'
  '51.143.210.0/23'
  '2603:1020:705::180/122'
  '2603:1020:705:402::280/122'
]
