// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureResourceManager.MalaysiaSouth

var AzureResourceManager_MalaysiaSouth = [
  '20.17.60.0/23'
  '20.17.68.0/26'
  '2603:1040:1503:1::600/120'
  '2603:1040:1503:400::1c0/122'
]
