// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureResourceManager.SouthCentralUSSTG

var AzureResourceManager_SouthCentralUSSTG = [
  '20.44.3.240/28'
  '20.44.6.0/23'
  '20.45.118.0/23'
]
