// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-10
// Source file  : ServiceTags_China.json
// Cloud        : China
// Service tag  : AzureBackup.ChinaEast

var AzureBackup_ChinaEast = [
  '52.130.15.0/26'
  '139.217.171.32/27'
  '139.217.171.64/26'
  '2404:7940:201:402::200/121'
]
