// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : AzureIoTHub.MalaysiaSouth

var AzureIoTHub_MalaysiaSouth = [
  '20.17.68.96/27'
  '2603:1040:1503:400::220/123'
]
