// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 407
// Service tag  : AzureIoTHub.SouthIndia

var AzureIoTHub_SouthIndia = [
  '13.71.84.34/32'
  '13.71.113.127/32'
  '20.41.197.64/27'
  '20.41.197.128/25'
  '40.78.196.96/27'
  '74.225.50.224/27'
  '74.225.54.0/26'
  '74.225.54.64/30'
  '104.211.210.195/32'
  '2603:1040:c06:c::788/126'
  '2603:1040:c06:d::200/122'
  '2603:1040:c06:d::240/123'
  '2603:1040:c06:402::300/123'
]
