// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureIoTHub.SwedenSouth
metadata name = 'AzureIoTHub.SwedenSouth'
metadata description = 'This module contains all the service tag IP addresses of AzureIoTHub.SwedenSouth for Public.'
metadata author = ''
metadata author = ''

@description('AzureIoTHub.SwedenSouth service tag IP addresses for Public')
@export()
var AzureIoTHub_SwedenSouth = [
  '51.12.194.32/27'
  '51.12.194.128/25'
  '51.12.204.64/27'
  '2603:1020:1104:400::300/123'
]
