// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : AzureIoTHub.AustraliaSoutheast

var AzureIoTHub_AustraliaSoutheast = [
  '13.70.182.204/32'
  '13.70.182.210/32'
  '13.73.115.51/32'
  '13.77.53.128/27'
  '20.42.230.160/27'
  '20.42.231.0/25'
  '2603:1010:101:402::300/123'
]
