// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureIoTHub.NorthCentralUS

var AzureIoTHub_NorthCentralUS = [
  '20.49.113.32/27'
  '20.49.113.128/25'
  '20.125.171.160/27'
  '20.125.203.160/27'
  '23.96.222.45/32'
  '23.96.223.89/32'
  '52.162.111.64/27'
  '157.55.253.43/32'
  '2603:1030:608:402::300/123'
  '2603:1030:608:800::e0/123'
  '2603:1030:608:c00::e0/123'
]
