// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 407
// Service tag  : AzureIoTHub.SouthCentralUSSTG

var AzureIoTHub_SouthCentralUSSTG = [
  '20.44.4.128/27'
  '20.45.114.224/27'
  '20.45.115.0/25'
]
