// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 407
// Service tag  : AzureIoTHub.WestUS3

var AzureIoTHub_WestUS3 = [
  '20.150.165.192/27'
  '20.150.166.0/25'
  '20.150.172.192/27'
  '20.150.179.224/27'
  '20.150.187.224/27'
  '172.180.56.128/25'
  '172.180.57.0/26'
  '172.180.57.64/29'
  '2603:1030:504:17::418/125'
  '2603:1030:504:17::480/121'
  '2603:1030:504:19::/122'
  '2603:1030:504:402::460/123'
  '2603:1030:504:802::100/123'
  '2603:1030:504:c02::2a0/123'
]
