// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureIoTHub.ItalyNorth
metadata name = 'AzureIoTHub.ItalyNorth'
metadata description = 'This module contains all the service tag IP addresses of AzureIoTHub.ItalyNorth for Public.'
metadata author = ''
metadata author = ''

@description('AzureIoTHub.ItalyNorth service tag IP addresses for Public')
@export()
var AzureIoTHub_ItalyNorth = [
  '4.232.108.32/27'
  '4.232.123.160/27'
  '4.232.195.160/27'
  '2603:1020:1204:400::1e0/123'
  '2603:1020:1204:800::120/123'
  '2603:1020:1204:c00::120/123'
]
