// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureIoTHub.NorwayWest

var AzureIoTHub_NorwayWest = [
  '51.13.129.224/27'
  '51.120.227.128/25'
  '51.120.228.0/27'
  '2603:1020:f04:402::300/123'
]
