// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_China.json
// Cloud        : China
// Service tag  : AzureEventGrid.ChinaEast

@export()
var AzureEventGrid_ChinaEast = [
  '52.130.8.192/26'
  '139.219.248.64/27'
  '2404:7940:201::280/121'
]
