// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-21
// Source file  : ServiceTags_AzureGovernment.json
// Cloud        : AzureGovernment
// Change number: 390
// Service tag  : AzureDataExplorerManagement.USGovTexas

var AzureDataExplorerManagement_USGovTexas = [
  '52.127.35.144/28'
  '52.243.157.34/32'
  '62.11.92.208/28'
  '2001:489a:3403:1::580/121'
  '2001:489a:3403:402::150/124'
]
