// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_AzureGovernment.json
// Cloud        : AzureGovernment
// Service tag  : AzureDataExplorerManagement.USGovArizona
metadata name = 'AzureDataExplorerManagement.USGovArizona'
metadata description = 'This module contains all the service tag IP addresses of AzureDataExplorerManagement.USGovArizona for AzureGovernment.'
metadata author = ''
metadata author = ''

@description('AzureDataExplorerManagement.USGovArizona service tag IP addresses for AzureGovernment')
@export()
var AzureDataExplorerManagement_USGovArizona = [
  '20.141.13.144/28'
  '52.127.3.192/28'
  '52.244.33.193/32'
  '2001:489a:3604:3::60/123'
  '2001:489a:3604:402::150/124'
]
