// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_AzureGovernment.json
// Cloud        : AzureGovernment
// Service tag  : AzureDataExplorerManagement.USDoDCentral
metadata name = 'AzureDataExplorerManagement.USDoDCentral'
metadata description = 'This module contains all the service tag IP addresses of AzureDataExplorerManagement.USDoDCentral for AzureGovernment.'
metadata author = ''
metadata author = ''

@description('AzureDataExplorerManagement.USDoDCentral service tag IP addresses for AzureGovernment')
@export()
var AzureDataExplorerManagement_USDoDCentral = [
  '20.158.154.96/28'
  '52.127.59.144/28'
  '52.182.33.66/32'
  '2001:489a:3203:1::580/121'
  '2001:489a:3203:402::150/124'
]
