// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-06-01
// Source file  : ServiceTags_AzureGovernment.json
// Cloud        : AzureGovernment
// Change number: 394
// Service tag  : Dynamics365ForMarketingEmail

var Dynamics365ForMarketingEmail = [
  '51.55.171.224/27'
  '52.243.4.160/27'
]
