// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_China.json
// Cloud        : China
// Service tag  : SCCservice.ChinaEast3

@export()
var SCCservice_ChinaEast3 = [
  '40.162.59.0/27'
]
