// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_China.json
// Cloud        : China
// Change number: 392
// Service tag  : AzureBotService.ChinaEast3

var AzureBotService_ChinaEast3 = [
  '52.131.144.16/30'
  '2406:e500:2402::1a0/123'
]
