// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_China.json
// Cloud        : China
// Service tag  : AzureBotService.ChinaEast2

@export()
var AzureBotService_ChinaEast2 = [
  '52.130.0.64/30'
  '2404:7940:301::20/123'
]
