// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-21
// Source file  : ServiceTags_China.json
// Cloud        : China
// Change number: 391
// Service tag  : AzureBotService.ChinaNorth

var AzureBotService_ChinaNorth = [
  '40.72.72.64/30'
  '2404:7940:1::20/123'
]
