// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_AzureGovernment.json
// Cloud        : AzureGovernment
// Change number: 390
// Service tag  : AzureDigitalTwins.USGovTexas

var AzureDigitalTwins_USGovTexas = [
  '62.11.90.216/29'
  '62.11.90.224/27'
  '2001:489a:3403:5::700/121'
]
