// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_AzureGermany.json
// Cloud        : AzureGermany
// Change number: 193
// Service tag  : ServiceFabric.GermanyNorthEast

var ServiceFabric_GermanyNorthEast = [
  '51.5.144.120/32'
  '51.8.226.216/29'
]
