// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureCosmosDB.ItalyNorth
metadata name = 'AzureCosmosDB.ItalyNorth'
metadata description = 'This module contains all the service tag IP addresses of AzureCosmosDB.ItalyNorth for Public.'
metadata author = ''
metadata author = ''

@description('AzureCosmosDB.ItalyNorth service tag IP addresses for Public')
@export()
var AzureCosmosDB_ItalyNorth = [
  '4.232.26.64/27'
  '4.232.42.64/26'
  '2603:1020:1204::1e0/123'
]
