// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureCosmosDB.SouthCentralUSSTG
metadata name = 'AzureCosmosDB.SouthCentralUSSTG'
metadata description = 'This module contains all the service tag IP addresses of AzureCosmosDB.SouthCentralUSSTG for Public.'
metadata author = ''
metadata author = ''

@description('AzureCosmosDB.SouthCentralUSSTG service tag IP addresses for Public')
@export()
var AzureCosmosDB_SouthCentralUSSTG = [
  '20.44.2.64/26'
  '20.45.115.160/27'
]
