// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureCosmosDB.MalaysiaSouth

var AzureCosmosDB_MalaysiaSouth = [
  '20.17.8.192/32'
  '20.17.8.210/32'
  '20.17.24.64/26'
  '20.17.51.0/27'
  '20.17.66.0/26'
  '2603:1040:1503::1e0/123'
  '2603:1040:1503:400::/122'
]
