// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureCosmosDB.IndiaSouthCentral

@export()
var AzureCosmosDB_IndiaSouthCentral = [
  '172.198.84.32/27'
  '172.198.84.64/26'
  '2603:1040:1904::5c0/123'
]
