// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureCosmosDB.BelgiumCentral
metadata name = 'AzureCosmosDB.BelgiumCentral'
metadata description = 'This module contains all the service tag IP addresses of AzureCosmosDB.BelgiumCentral for Public.'
metadata author = ''
metadata author = ''

@description('AzureCosmosDB.BelgiumCentral service tag IP addresses for Public')
@export()
var AzureCosmosDB_BelgiumCentral = [
  '9.160.43.0/26'
  '9.160.58.64/27'
  '2603:1020:1502::1e0/123'
]
