// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureCosmosDB.MexicoCentral

@export()
var AzureCosmosDB_MexicoCentral = [
  '158.23.113.192/26'
  '2603:1030:702::1e0/123'
]
