// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureCosmosDB.BelgiumCentral

@export()
var AzureCosmosDB_BelgiumCentral = [
  '9.160.43.0/26'
  '9.160.58.64/27'
  '2603:1020:1502::1e0/123'
]
