// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-10
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 407
// Service tag  : AzureCosmosDB.MalaysiaWest

var AzureCosmosDB_MalaysiaWest = [
  '20.17.114.64/26'
  '2603:1040:1602::1e0/123'
]
