// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : AzureCosmosDB.SouthCentralUSSTG

var AzureCosmosDB_SouthCentralUSSTG = [
  '20.44.2.64/26'
  '20.45.115.160/27'
]
