// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : BatchNodeManagement.NorthEurope
metadata name = 'BatchNodeManagement.NorthEurope'
metadata description = 'This module contains all the service tag IP addresses of BatchNodeManagement.NorthEurope for Public.'
metadata author = ''
metadata author = ''

@description('BatchNodeManagement.NorthEurope service tag IP addresses for Public')
@export()
var BatchNodeManagement_NorthEurope = [
  '13.69.229.32/27'
  '13.74.107.128/27'
  '13.79.172.125/32'
  '20.38.85.224/27'
  '52.138.226.128/27'
  '52.164.244.189/32'
  '52.164.245.81/32'
  '52.169.27.79/32'
  '52.169.30.175/32'
  '52.169.235.90/32'
  '52.178.149.188/32'
  '104.45.82.201/32'
  '104.45.88.181/32'
  '168.63.36.126/32'
  '2603:1020:5:1::340/122'
]
