// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-06-22
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 405
// Service tag  : BatchNodeManagement.MalaysiaSouth

var BatchNodeManagement_MalaysiaSouth = [
  '20.17.49.32/27'
  '2603:1040:1503::240/122'
]
