// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : BatchNodeManagement.NorwayWest
metadata name = 'BatchNodeManagement.NorwayWest'
metadata description = 'This module contains all the service tag IP addresses of BatchNodeManagement.NorwayWest for Public.'
metadata author = ''
metadata author = ''

@description('BatchNodeManagement.NorwayWest service tag IP addresses for Public')
@export()
var BatchNodeManagement_NorwayWest = [
  '51.120.220.0/27'
  '51.120.225.160/27'
  '2603:1020:f04::400/122'
]
