// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 407
// Service tag  : BatchNodeManagement.TaiwanNorthwest

var BatchNodeManagement_TaiwanNorthwest = [
  '51.53.169.32/27'
  '2603:1040:1202::240/122'
]
