// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : BatchNodeManagement.WestIndia

@export()
var BatchNodeManagement_WestIndia = [
  '52.136.49.192/27'
  '104.211.147.96/27'
  '104.211.160.72/32'
  '104.211.160.74/31'
  '2603:1040:806::400/122'
]
