// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-10
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : BatchNodeManagement.MexicoCentral

var BatchNodeManagement_MexicoCentral = [
  '158.23.97.64/27'
  '2603:1030:702::300/122'
]
