// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-10
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : BatchNodeManagement.SwedenCentral

var BatchNodeManagement_SwedenCentral = [
  '51.12.41.192/27'
  '51.12.100.0/27'
  '51.12.227.96/27'
  '51.12.235.96/27'
  '2603:1020:1004::340/122'
]
