// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : BatchNodeManagement.TaiwanNorth

@export()
var BatchNodeManagement_TaiwanNorth = [
  '51.53.25.32/27'
  '2603:1040:1302::240/122'
]
