// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : BatchNodeManagement.CentralIndia

var BatchNodeManagement_CentralIndia = [
  '20.192.99.96/27'
  '40.80.50.224/27'
  '52.140.106.128/27'
  '104.211.82.96/27'
  '104.211.96.142/32'
  '104.211.96.144/31'
  '2603:1040:a06:1::340/122'
]
