// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : BatchNodeManagement.SouthCentralUS2

var BatchNodeManagement_SouthCentralUS2 = [
  '48.216.17.64/27'
  '2603:1030:1102::300/122'
]
