// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : BatchNodeManagement.SouthCentralUSSTG
metadata name = 'BatchNodeManagement.SouthCentralUSSTG'
metadata description = 'This module contains all the service tag IP addresses of BatchNodeManagement.SouthCentralUSSTG for Public.'
metadata author = ''
metadata author = ''

@description('BatchNodeManagement.SouthCentralUSSTG service tag IP addresses for Public')
@export()
var BatchNodeManagement_SouthCentralUSSTG = [
  '20.44.4.112/29'
  '20.45.113.160/27'
]
