// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-10
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 407
// Service tag  : BatchNodeManagement.BelgiumCentral

var BatchNodeManagement_BelgiumCentral = [
  '9.160.41.64/27'
  '2603:1020:1502::300/122'
]
