// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-10
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 407
// Service tag  : BatchNodeManagement.IsraelCentral

var BatchNodeManagement_IsraelCentral = [
  '20.217.41.32/27'
  '2603:1040:1402::240/122'
]
