// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : BatchNodeManagement.CanadaEast

var BatchNodeManagement_CanadaEast = [
  '40.69.107.128/27'
  '40.86.224.98/32'
  '40.86.224.104/32'
  '40.89.18.192/27'
  '52.235.41.66/32'
  '52.242.22.129/32'
  '52.242.33.105/32'
  '2603:1030:1005::400/122'
]
