// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : BatchNodeManagement.JapanEast
metadata name = 'BatchNodeManagement.JapanEast'
metadata description = 'This module contains all the service tag IP addresses of BatchNodeManagement.JapanEast for Public.'
metadata author = ''
metadata author = ''

@description('BatchNodeManagement.JapanEast service tag IP addresses for Public')
@export()
var BatchNodeManagement_JapanEast = [
  '13.71.144.135/32'
  '13.78.108.128/27'
  '20.43.66.96/27'
  '23.100.100.145/32'
  '23.100.103.112/32'
  '40.79.186.128/27'
  '40.79.194.32/27'
  '138.91.1.114/32'
  '2603:1040:407:1::340/122'
]
