// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : WindowsVirtualDesktop.IsraelCentral

var WindowsVirtualDesktop_IsraelCentral = [
  '40.64.144.248/29'
  '40.64.152.128/27'
  '2603:1061:2010:37::/117'
]
