// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : WindowsVirtualDesktop.AustraliaCentral2
metadata name = 'WindowsVirtualDesktop.AustraliaCentral2'
metadata description = 'This module contains all the service tag IP addresses of WindowsVirtualDesktop.AustraliaCentral2 for Public.'
metadata author = ''
metadata author = ''

@description('WindowsVirtualDesktop.AustraliaCentral2 service tag IP addresses for Public')
@export()
var WindowsVirtualDesktop_AustraliaCentral2 = [
  '2603:1061:2010:21::/117'
]
