// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : WindowsVirtualDesktop.SouthAfricaWest

var WindowsVirtualDesktop_SouthAfricaWest = [
  '40.64.146.128/28'
  '40.64.151.0/27'
  '2603:1061:2010:1f::/117'
]
