// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-09
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 407
// Service tag  : WindowsVirtualDesktop.IndiaSouthCentral

var WindowsVirtualDesktop_IndiaSouthCentral = [
  '2603:1061:2010:41::/117'
]
