// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : WindowsVirtualDesktop.UKSouth

var WindowsVirtualDesktop_UKSouth = [
  '40.64.144.200/29'
  '40.64.145.16/28'
  '40.64.148.64/27'
  '2603:1061:2010:16::/117'
]
