// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : WindowsVirtualDesktop.BelgiumCentral
metadata name = 'WindowsVirtualDesktop.BelgiumCentral'
metadata description = 'This module contains all the service tag IP addresses of WindowsVirtualDesktop.BelgiumCentral for Public.'
metadata author = ''
metadata author = ''

@description('WindowsVirtualDesktop.BelgiumCentral service tag IP addresses for Public')
@export()
var WindowsVirtualDesktop_BelgiumCentral = [
  '2603:1061:2010:3f::/117'
]
