// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-21
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 396
// Service tag  : WindowsVirtualDesktop.DenmarkEast

var WindowsVirtualDesktop_DenmarkEast = [
  '2603:1061:2010:45::/117'
]
