// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : WindowsVirtualDesktop.EastUS2EUAP

var WindowsVirtualDesktop_EastUS2EUAP = [
  '40.64.147.160/30'
  '2603:1061:2010:1d::/117'
]
