// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : WindowsVirtualDesktop.AustraliaSoutheast
metadata name = 'WindowsVirtualDesktop.AustraliaSoutheast'
metadata description = 'This module contains all the service tag IP addresses of WindowsVirtualDesktop.AustraliaSoutheast for Public.'
metadata author = ''
metadata author = ''

@description('WindowsVirtualDesktop.AustraliaSoutheast service tag IP addresses for Public')
@export()
var WindowsVirtualDesktop_AustraliaSoutheast = [
  '40.64.146.64/28'
  '40.64.150.128/27'
  '2603:1061:2010:1::/117'
]
