// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : WindowsVirtualDesktop.MexicoCentral
metadata name = 'WindowsVirtualDesktop.MexicoCentral'
metadata description = 'This module contains all the service tag IP addresses of WindowsVirtualDesktop.MexicoCentral for Public.'
metadata author = ''
metadata author = ''

@description('WindowsVirtualDesktop.MexicoCentral service tag IP addresses for Public')
@export()
var WindowsVirtualDesktop_MexicoCentral = [
  '40.64.144.184/29'
  '40.64.152.160/27'
  '2603:1061:2010:36::/117'
]
