// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : WindowsVirtualDesktop.CanadaCentral

var WindowsVirtualDesktop_CanadaCentral = [
  '40.64.145.208/28'
  '40.64.149.160/27'
  '2603:1061:2010:3::/117'
]
