// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : WindowsVirtualDesktop.AustraliaCentral2

var WindowsVirtualDesktop_AustraliaCentral2 = [
  '2603:1061:2010:21::/117'
]
