// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : WindowsVirtualDesktop.EastUS2
metadata name = 'WindowsVirtualDesktop.EastUS2'
metadata description = 'This module contains all the service tag IP addresses of WindowsVirtualDesktop.EastUS2 for Public.'
metadata author = ''
metadata author = ''

@description('WindowsVirtualDesktop.EastUS2 service tag IP addresses for Public')
@export()
var WindowsVirtualDesktop_EastUS2 = [
  '40.64.144.192/29'
  '40.64.145.0/28'
  '40.64.148.32/27'
  '2603:1061:2010:a::/117'
]
