// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-10
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 407
// Service tag  : WindowsVirtualDesktop.CentralUS

var WindowsVirtualDesktop_CentralUS = [
  '40.64.145.176/28'
  '40.64.149.96/27'
  '2603:1061:2010:6::/117'
]
