// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 407
// Service tag  : WindowsVirtualDesktop.CentralIndia

var WindowsVirtualDesktop_CentralIndia = [
  '40.64.144.232/29'
  '40.64.145.80/28'
  '40.64.148.192/27'
  '2603:1061:2010:5::/117'
]
