// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 407
// Service tag  : WindowsVirtualDesktop.JioIndiaCentral

var WindowsVirtualDesktop_JioIndiaCentral = [
  '2603:1061:2010:31::/117'
]
