// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : WindowsVirtualDesktop.JapanEast

var WindowsVirtualDesktop_JapanEast = [
  '40.64.146.32/28'
  '40.64.150.64/27'
  '2603:1061:2010:d::/117'
]
