// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : WindowsVirtualDesktop.GermanyNorth
metadata name = 'WindowsVirtualDesktop.GermanyNorth'
metadata description = 'This module contains all the service tag IP addresses of WindowsVirtualDesktop.GermanyNorth for Public.'
metadata author = ''
metadata author = ''

@description('WindowsVirtualDesktop.GermanyNorth service tag IP addresses for Public')
@export()
var WindowsVirtualDesktop_GermanyNorth = [
  '40.64.147.200/29'
  '40.64.148.0/27'
  '2603:1061:2010:2c::/117'
]
