// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : WindowsVirtualDesktop.NorwayWest

@export()
var WindowsVirtualDesktop_NorwayWest = [
  '40.64.147.216/29'
  '40.64.153.192/27'
  '2603:1061:2010:2b::/117'
]
