// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : WindowsVirtualDesktop.UAENorth
metadata name = 'WindowsVirtualDesktop.UAENorth'
metadata description = 'This module contains all the service tag IP addresses of WindowsVirtualDesktop.UAENorth for Public.'
metadata author = ''
metadata author = ''

@description('WindowsVirtualDesktop.UAENorth service tag IP addresses for Public')
@export()
var WindowsVirtualDesktop_UAENorth = [
  '40.64.145.112/28'
  '40.64.149.0/27'
  '2603:1061:2010:22::/117'
]
