// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : WindowsVirtualDesktop.MexicoCentral

var WindowsVirtualDesktop_MexicoCentral = [
  '40.64.144.184/29'
  '40.64.152.160/27'
  '2603:1061:2010:36::/117'
]
