// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : WindowsVirtualDesktop.PolandCentral
metadata name = 'WindowsVirtualDesktop.PolandCentral'
metadata description = 'This module contains all the service tag IP addresses of WindowsVirtualDesktop.PolandCentral for Public.'
metadata author = ''
metadata author = ''

@description('WindowsVirtualDesktop.PolandCentral service tag IP addresses for Public')
@export()
var WindowsVirtualDesktop_PolandCentral = [
  '40.64.147.240/29'
  '40.64.154.0/27'
  '2603:1061:2010:35::/117'
]
