// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : WindowsVirtualDesktop.SwedenCentral

var WindowsVirtualDesktop_SwedenCentral = [
  '40.64.144.136/29'
  '40.64.153.64/27'
  '2603:1061:2010:2e::/117'
]
