// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : WindowsVirtualDesktop.NorthCentralUS

var WindowsVirtualDesktop_NorthCentralUS = [
  '40.64.146.96/28'
  '40.64.150.192/27'
  '2603:1061:2010:11::/117'
]
