// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : WindowsVirtualDesktop.PolandCentral

var WindowsVirtualDesktop_PolandCentral = [
  '40.64.147.240/29'
  '40.64.154.0/27'
  '2603:1061:2010:35::/117'
]
