// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-10
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 408
// Service tag  : WindowsVirtualDesktop.MalaysiaWest

var WindowsVirtualDesktop_MalaysiaWest = [
  '2603:1061:2010:3a::/117'
]
