// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : WindowsVirtualDesktop.EastAsia

var WindowsVirtualDesktop_EastAsia = [
  '40.64.145.192/28'
  '40.64.149.128/27'
  '2603:1061:2010:8::/117'
]
