// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : WindowsVirtualDesktop.AustraliaEast
metadata name = 'WindowsVirtualDesktop.AustraliaEast'
metadata description = 'This module contains all the service tag IP addresses of WindowsVirtualDesktop.AustraliaEast for Public.'
metadata author = ''
metadata author = ''

@description('WindowsVirtualDesktop.AustraliaEast service tag IP addresses for Public')
@export()
var WindowsVirtualDesktop_AustraliaEast = [
  '40.64.146.16/28'
  '40.64.150.32/27'
  '2603:1061:2010::/117'
]
