// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : AzureCloud.brazilne

var AzureCloud_brazilne = [
  '23.97.112.224/27'
  '2603:1050:100::/40'
  '2603:1056:1402::/48'
  '2603:1061:1315::/54'
]
