// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_AzureGovernment.json
// Cloud        : AzureGovernment
// Change number: 390
// Service tag  : AzureKeyVault.USGovIowa

var AzureKeyVault_USGovIowa = [
  '20.140.154.160/29'
  '20.140.154.168/30'
]
