// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_China.json
// Cloud        : China
// Service tag  : SystemServiceAzureSpringAppsResourceProvider

@export()
var SystemServiceAzureSpringAppsResourceProvider = [
  '40.162.5.160/27'
  '40.162.161.224/27'
  '143.64.198.160/27'
]
