// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_AzureGermany.json
// Cloud        : AzureGermany
// Change number: 193
// Service tag  : AzureKeyVault.GermanyNorthEast

var AzureKeyVault_GermanyNorthEast = [
  '51.5.144.216/32'
  '51.5.144.237/32'
]
