// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : ServiceFabric.NorwayWest
metadata name = 'ServiceFabric.NorwayWest'
metadata description = 'This module contains all the service tag IP addresses of ServiceFabric.NorwayWest for Public.'
metadata author = ''
metadata author = ''

@description('ServiceFabric.NorwayWest service tag IP addresses for Public')
@export()
var ServiceFabric_NorwayWest = [
  '51.120.164.23/32'
  '51.120.219.72/29'
  '2603:1020:f04:402::98/125'
]
