// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : ServiceFabric.SoutheastUS

var ServiceFabric_SoutheastUS = [
  '68.154.136.12/30'
  '2603:1030:902:400::18/125'
]
