// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-06-01
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 402
// Service tag  : ServiceFabric.IndiaSouthCentral

var ServiceFabric_IndiaSouthCentral = [
  '172.198.112.8/30'
  '172.198.144.8/30'
  '172.198.168.8/30'
  '2603:1040:1904:400::10/125'
  '2603:1040:1904:800::10/125'
  '2603:1040:1904:c00::10/125'
]
