// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : ServiceFabric.SoutheastUS3

var ServiceFabric_SoutheastUS3 = [
  '74.7.80.12/30'
  '2603:1030:1302:400::18/125'
]
