// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : ServiceFabric.FranceSouth

var ServiceFabric_FranceSouth = [
  '40.79.179.0/29'
  '52.136.136.27/32'
  '2603:1020:905:402::98/125'
]
