// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-10
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : ServiceFabric.UKWest

var ServiceFabric_UKWest = [
  '51.140.211.16/29'
  '51.141.8.30/32'
  '2603:1020:605:402::98/125'
]
