// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : ServiceFabric.JioIndiaCentral
metadata name = 'ServiceFabric.JioIndiaCentral'
metadata description = 'This module contains all the service tag IP addresses of ServiceFabric.JioIndiaCentral for Public.'
metadata author = ''
metadata author = ''

@description('ServiceFabric.JioIndiaCentral service tag IP addresses for Public')
@export()
var ServiceFabric_JioIndiaCentral = [
  '20.192.32.224/30'
  '20.192.235.0/29'
  '2603:1040:1104:400::98/125'
]
