// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : ServiceFabric.SwedenCentral
metadata name = 'ServiceFabric.SwedenCentral'
metadata description = 'This module contains all the service tag IP addresses of ServiceFabric.SwedenCentral for Public.'
metadata author = ''
metadata author = ''

@description('ServiceFabric.SwedenCentral service tag IP addresses for Public')
@export()
var ServiceFabric_SwedenCentral = [
  '51.12.99.64/29'
  '51.12.101.168/30'
  '51.12.229.28/30'
  '51.12.237.28/30'
  '2603:1020:1004:400::98/125'
  '2603:1020:1004:800::158/125'
  '2603:1020:1004:800::350/125'
  '2603:1020:1004:c02::1b8/125'
]
