// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-10
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 407
// Service tag  : ServiceFabric.SouthCentralUSSTG

var ServiceFabric_SouthCentralUSSTG = [
  '20.44.3.24/29'
  '23.100.199.230/32'
]
