// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : ServiceFabric.NorwayWest

var ServiceFabric_NorwayWest = [
  '51.120.164.23/32'
  '51.120.219.72/29'
  '2603:1020:f04:402::98/125'
]
