// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : ServiceFabric.CentralUSEUAP

var ServiceFabric_CentralUSEUAP = [
  '40.78.202.120/29'
  '52.180.176.84/32'
  '168.61.142.48/30'
  '2603:1030:f:400::898/125'
]
