// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : ServiceFabric.KoreaSouth
metadata name = 'ServiceFabric.KoreaSouth'
metadata description = 'This module contains all the service tag IP addresses of ServiceFabric.KoreaSouth for Public.'
metadata author = ''
metadata author = ''

@description('ServiceFabric.KoreaSouth service tag IP addresses for Public')
@export()
var ServiceFabric_KoreaSouth = [
  '52.231.147.16/29'
  '52.231.200.124/32'
  '2603:1040:e05:402::158/125'
]
