// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : ServiceFabric.JioIndiaWest
metadata name = 'ServiceFabric.JioIndiaWest'
metadata description = 'This module contains all the service tag IP addresses of ServiceFabric.JioIndiaWest for Public.'
metadata author = ''
metadata author = ''

@description('ServiceFabric.JioIndiaWest service tag IP addresses for Public')
@export()
var ServiceFabric_JioIndiaWest = [
  '20.193.202.24/29'
  '20.193.204.100/30'
  '2603:1040:d04:400::98/125'
  '2603:1040:d04:800::158/125'
  '2603:1040:d04:800::350/125'
]
