// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-21
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 396
// Service tag  : ServiceFabric.EastUS3

var ServiceFabric_EastUS3 = [
  '51.57.136.216/29'
  '134.138.96.8/30'
  '2603:1030:1402:4::780/125'
  '2603:1030:1402:400::18/125'
]
