// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-06
// Source file  : ServiceTags_AzureGovernment.json
// Cloud        : AzureGovernment
// Change number: 399
// Service tag  : EOPExternalPublishedIPs

var EOPExternalPublishedIPs = [
  '23.103.191.0/24'
  '23.103.199.0/24'
  '23.103.204.0/22'
  '23.103.208.0/22'
  '2001:489a:2202::/49'
  '2001:489a:2207::/61'
  '2001:489a:2400:10::/60'
  '2001:489a:2400:20::/60'
]
