// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_China.json
// Cloud        : China
// Change number: 393
// Service tag  : DataFactory.ChinaEast

var DataFactory_ChinaEast = [
  '52.130.11.160/28'
  '52.130.12.0/25'
  '52.130.12.128/26'
  '2404:7940:201::600/121'
  '2404:7940:201:402::4e0/124'
]
