// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-21
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 396
// Service tag  : AzureSignalR.EastAsia

var AzureSignalR_EastAsia = [
  '20.195.72.192/27'
  '2603:1040:207:2::600/120'
]
