// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : PowerPlatformPlex.NewZealandNorth

var PowerPlatformPlex_NewZealandNorth = [
  '172.204.242.128/26'
  '2603:1061:2004:b800::/57'
]
