// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-10
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 407
// Service tag  : PowerPlatformPlex.TaiwanNorth

var PowerPlatformPlex_TaiwanNorth = [
  '70.157.170.128/25'
]
