// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : PowerPlatformPlex.AustriaEast

@export()
var PowerPlatformPlex_AustriaEast = [
  '68.210.246.0/25'
]
