// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : PowerPlatformPlex.SwitzerlandNorth

var PowerPlatformPlex_SwitzerlandNorth = [
  '20.208.5.84/30'
  '20.208.7.120/30'
  '20.208.7.172/30'
  '20.208.7.184/30'
  '20.208.157.0/28'
  '20.250.175.0/28'
  '51.103.164.128/28'
  '74.161.173.192/26'
  '74.161.174.0/26'
  '74.242.188.32/29'
  '2603:1061:2004:5000::/57'
]
