// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_AzureGovernment.json
// Cloud        : AzureGovernment
// Service tag  : AzureConnectors.USDoDCentral
metadata name = 'AzureConnectors.USDoDCentral'
metadata description = 'This module contains all the service tag IP addresses of AzureConnectors.USDoDCentral for AzureGovernment.'
metadata author = ''
metadata author = ''

@description('AzureConnectors.USDoDCentral service tag IP addresses for AzureGovernment')
@export()
var AzureConnectors_USDoDCentral = [
  '52.127.58.160/28'
  '52.127.61.192/27'
  '52.182.48.97/32'
  '52.182.48.136/32'
  '52.245.153.80/28'
  '52.245.153.96/27'
  '2001:489a:3203:3::640/122'
  '2001:489a:3203:402::180/122'
]
