// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-21
// Source file  : ServiceTags_China.json
// Cloud        : China
// Change number: 391
// Service tag  : Storage.ChinaNorth2

var Storage_ChinaNorth2 = [
  '40.73.48.0/24'
  '52.130.96.0/24'
  '52.130.98.0/23'
  '2406:e500:2005::/48'
]
