// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_AzureGovernment.json
// Cloud        : AzureGovernment
// Service tag  : StorageSyncService.USGovArizona
metadata name = 'StorageSyncService.USGovArizona'
metadata description = 'This module contains all the service tag IP addresses of StorageSyncService.USGovArizona for AzureGovernment.'
metadata author = ''
metadata author = ''

@description('StorageSyncService.USGovArizona service tag IP addresses for AzureGovernment')
@export()
var StorageSyncService_USGovArizona = [
  '20.140.48.216/29'
  '2001:489a:3604::300/123'
  '2001:489a:3604:802::2a0/123'
]
