// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_AzureGovernment.json
// Cloud        : AzureGovernment
// Change number: 390
// Service tag  : StorageSyncService.USDoDCentral

var StorageSyncService_USDoDCentral = [
  '20.140.72.152/29'
  '2001:489a:3203::340/123'
  '2001:489a:3203:402::580/123'
]
