// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzurePortal.SwitzerlandNorth

var AzurePortal_SwitzerlandNorth = [
  '51.107.49.160/27'
  '51.107.50.60/30'
  '51.107.53.240/29'
  '2603:1020:a04::100/121'
  '2603:1020:a04:1::680/121'
]
