// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzurePortal.AustraliaSoutheast

var AzurePortal_AustraliaSoutheast = [
  '13.77.55.208/28'
  '20.42.227.192/27'
  '20.42.228.220/30'
  '20.42.228.224/27'
  '20.42.230.80/28'
  '104.46.178.96/29'
  '2603:1010:101::700/121'
]
