// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzurePortal.WestUS3
metadata name = 'AzurePortal.WestUS3'
metadata description = 'This module contains all the service tag IP addresses of AzurePortal.WestUS3 for Public.'
metadata author = ''
metadata author = ''

@description('AzurePortal.WestUS3 service tag IP addresses for Public')
@export()
var AzurePortal_WestUS3 = [
  '20.150.161.192/27'
  '20.150.165.144/30'
  '20.150.166.160/29'
  '2603:1030:504::100/121'
  '2603:1030:504:1::680/121'
]
