// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : AzurePortal.JapanWest

var AzurePortal_JapanWest = [
  '20.189.224.208/29'
  '40.80.58.128/27'
  '40.80.59.28/30'
  '40.80.59.32/27'
  '2603:1040:606::700/121'
]
