// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzurePortal.UAECentral

var AzurePortal_UAECentral = [
  '20.37.65.128/27'
  '20.37.66.56/30'
  '20.37.70.96/29'
  '2603:1040:b04::700/121'
]
