// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : AzurePortal.EastUS3

var AzurePortal_EastUS3 = [
  '134.138.82.8/30'
  '134.138.82.160/27'
  '2603:1030:1402:2::680/121'
]
