// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : AzurePortal.NorthCentralUS

var AzurePortal_NorthCentralUS = [
  '20.49.115.184/29'
  '40.80.190.160/27'
  '40.80.191.200/30'
  '135.224.40.0/27'
  '2603:1030:608::700/121'
]
