// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : AzurePortal.BelgiumCentral

var AzurePortal_BelgiumCentral = [
  '9.160.53.224/27'
  '9.160.58.128/30'
  '2603:1020:1502:2::400/121'
]
