// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzurePortal.CanadaEast
metadata name = 'AzurePortal.CanadaEast'
metadata description = 'This module contains all the service tag IP addresses of AzurePortal.CanadaEast for Public.'
metadata author = ''
metadata author = ''

@description('AzurePortal.CanadaEast service tag IP addresses for Public')
@export()
var AzurePortal_CanadaEast = [
  '40.89.18.160/27'
  '40.89.20.132/30'
  '40.89.23.232/29'
  '2603:1030:1005::700/121'
]
