// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : AzurePortal.WestUS

var AzurePortal_WestUS = [
  '20.49.120.0/27'
  '20.49.120.36/30'
  '20.49.126.156/30'
  '20.49.127.224/28'
  '40.82.253.224/27'
  '2603:1030:a07::700/121'
]
