// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzurePortal.TaiwanNorthwest

@export()
var AzurePortal_TaiwanNorthwest = [
  '51.53.178.32/27'
  '2603:1040:1202:1::480/121'
]
