// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzurePortal.DenmarkEast

var AzurePortal_DenmarkEast = [
  '9.205.45.224/27'
  '9.205.50.20/30'
  '2603:1020:1602:2::400/121'
]
