// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzurePortal.FranceSouth

var AzurePortal_FranceSouth = [
  '51.105.89.160/27'
  '51.105.90.152/30'
  '52.136.184.64/29'
  '2603:1020:905::700/121'
]
