// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : AzurePortal.SouthCentralUSSTG

var AzurePortal_SouthCentralUSSTG = [
  '20.45.112.124/30'
  '20.45.113.128/27'
  '20.45.116.64/29'
]
