// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzurePortal.MalaysiaSouth
metadata name = 'AzurePortal.MalaysiaSouth'
metadata description = 'This module contains all the service tag IP addresses of AzurePortal.MalaysiaSouth for Public.'
metadata author = ''
metadata author = ''

@description('AzurePortal.MalaysiaSouth service tag IP addresses for Public')
@export()
var AzurePortal_MalaysiaSouth = [
  '20.17.58.128/27'
  '2603:1040:1503:1::580/121'
]
