// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzurePortal.SouthAfricaWest
metadata name = 'AzurePortal.SouthAfricaWest'
metadata description = 'This module contains all the service tag IP addresses of AzurePortal.SouthAfricaWest for Public.'
metadata author = ''
metadata author = ''

@description('AzurePortal.SouthAfricaWest service tag IP addresses for Public')
@export()
var AzurePortal_SouthAfricaWest = [
  '102.133.56.160/27'
  '102.133.58.192/30'
  '102.133.61.176/29'
  '2603:1000:4::700/121'
]
