// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzurePortal.AustraliaCentral2
metadata name = 'AzurePortal.AustraliaCentral2'
metadata description = 'This module contains all the service tag IP addresses of AzurePortal.AustraliaCentral2 for Public.'
metadata author = ''
metadata author = ''

@description('AzurePortal.AustraliaCentral2 service tag IP addresses for Public')
@export()
var AzurePortal_AustraliaCentral2 = [
  '20.36.121.128/27'
  '20.36.122.56/30'
  '20.36.125.104/29'
  '2603:1010:404::700/121'
]
