// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzurePortal.EastUS2EUAP
metadata name = 'AzurePortal.EastUS2EUAP'
metadata description = 'This module contains all the service tag IP addresses of AzurePortal.EastUS2EUAP for Public.'
metadata author = ''
metadata author = ''

@description('AzurePortal.EastUS2EUAP service tag IP addresses for Public')
@export()
var AzurePortal_EastUS2EUAP = [
  '20.39.12.32/27'
  '20.39.12.232/30'
  '20.47.232.32/28'
  '20.51.16.120/29'
  '2603:1030:40b:1::680/121'
]
