// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-10
// Source file  : ServiceTags_AzureGovernment.json
// Cloud        : AzureGovernment
// Change number: 399
// Service tag  : AzureIoTHub.USGovArizona

var AzureIoTHub_USGovArizona = [
  '20.140.51.64/27'
  '20.140.51.128/25'
  '51.55.224.16/29'
  '51.55.224.64/26'
  '51.55.224.128/25'
  '52.127.5.32/27'
  '52.127.10.160/27'
  '52.127.18.128/27'
  '52.244.206.149/32'
  '2001:489a:3604:a::330/125'
  '2001:489a:3604:a::680/121'
  '2001:489a:3604:a::700/122'
  '2001:489a:3604:402::300/123'
  '2001:489a:3604:802::240/123'
  '2001:489a:3604:c02::1c0/123'
]
