// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : StorageSyncService.SouthCentralUS2
metadata name = 'StorageSyncService.SouthCentralUS2'
metadata description = 'This module contains all the service tag IP addresses of StorageSyncService.SouthCentralUS2 for Public.'
metadata author = ''
metadata author = ''

@description('StorageSyncService.SouthCentralUS2 service tag IP addresses for Public')
@export()
var StorageSyncService_SouthCentralUS2 = [
  '48.216.8.56/29'
  '48.216.36.248/29'
  '2603:1030:1102:3::6a0/123'
  '2603:1030:1102:400::120/123'
]
