// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : StorageSyncService.EastUS2EUAP

var StorageSyncService_EastUS2EUAP = [
  '20.39.11.96/29'
  '2603:1030:40b:1::300/123'
]
