// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : StorageSyncService.MexicoCentral

var StorageSyncService_MexicoCentral = [
  '158.23.11.176/29'
  '2603:1030:702:400::1e0/123'
]
