// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : StorageSyncService.PolandCentral
metadata name = 'StorageSyncService.PolandCentral'
metadata description = 'This module contains all the service tag IP addresses of StorageSyncService.PolandCentral for Public.'
metadata author = ''
metadata author = ''

@description('StorageSyncService.PolandCentral service tag IP addresses for Public')
@export()
var StorageSyncService_PolandCentral = [
  '74.248.175.152/29'
  '2603:1020:1302:400::240/123'
]
