// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : StorageSyncService.SouthAfricaNorth
metadata name = 'StorageSyncService.SouthAfricaNorth'
metadata description = 'This module contains all the service tag IP addresses of StorageSyncService.SouthAfricaNorth for Public.'
metadata author = ''
metadata author = ''

@description('StorageSyncService.SouthAfricaNorth service tag IP addresses for Public')
@export()
var StorageSyncService_SouthAfricaNorth = [
  '20.87.83.120/29'
  '2603:1000:104:1::300/123'
]
