// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : StorageSyncService.EastUS2

var StorageSyncService_EastUS2 = [
  '20.41.5.144/29'
  '2603:1030:40c:1::300/123'
]
