// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-10
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : StorageSyncService.FranceCentral

var StorageSyncService_FranceCentral = [
  '20.43.42.8/29'
  '2603:1020:805:1::300/123'
]
