// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : StorageSyncService.NorthCentralUS

@export()
var StorageSyncService_NorthCentralUS = [
  '40.80.188.24/29'
  '2603:1030:608::340/123'
  '2603:1030:608:402::5e0/123'
]
