// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : StorageSyncService.GermanyWestCentral
metadata name = 'StorageSyncService.GermanyWestCentral'
metadata description = 'This module contains all the service tag IP addresses of StorageSyncService.GermanyWestCentral for Public.'
metadata author = ''
metadata author = ''

@description('StorageSyncService.GermanyWestCentral service tag IP addresses for Public')
@export()
var StorageSyncService_GermanyWestCentral = [
  '20.79.108.120/29'
  '51.116.245.168/30'
  '2603:1020:c04:1::300/123'
]
