// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : StorageSyncService.CanadaEast

var StorageSyncService_CanadaEast = [
  '40.69.111.200/29'
  '40.89.17.232/29'
  '2603:1030:1005::340/123'
  '2603:1030:1005:402::5e0/123'
]
