// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : StorageSyncService.GermanyNorth
metadata name = 'StorageSyncService.GermanyNorth'
metadata description = 'This module contains all the service tag IP addresses of StorageSyncService.GermanyNorth for Public.'
metadata author = ''
metadata author = ''

@description('StorageSyncService.GermanyNorth service tag IP addresses for Public')
@export()
var StorageSyncService_GermanyNorth = [
  '51.116.60.244/30'
  '51.116.78.200/29'
  '2603:1020:d04::340/123'
]
