// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : StorageSyncService.SoutheastAsia

@export()
var StorageSyncService_SoutheastAsia = [
  '20.43.131.40/29'
  '2603:1040:5:1::300/123'
]
