// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : StorageSyncService.MalaysiaSouth

var StorageSyncService_MalaysiaSouth = [
  '20.17.67.240/29'
  '85.211.78.80/29'
  '2603:1040:1503:5::700/123'
  '2603:1040:1503:400::260/123'
]
