// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : StorageSyncService.SwedenCentral

var StorageSyncService_SwedenCentral = [
  '20.91.146.0/29'
  '51.12.101.240/29'
  '2603:1020:1004::300/123'
  '2603:1020:1004:800::120/123'
]
