// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : StorageSyncService.JapanWest

var StorageSyncService_JapanWest = [
  '40.74.99.32/29'
  '40.80.57.192/29'
  '2603:1040:606::340/123'
  '2603:1040:606:402::680/123'
]
