// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : StorageSyncService.TaiwanNorth

var StorageSyncService_TaiwanNorth = [
  '51.53.107.240/29'
  '70.157.11.144/29'
  '2603:1040:1302:5::320/123'
  '2603:1040:1302:400::260/123'
]
