// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : StorageSyncService.SwedenSouth
metadata name = 'StorageSyncService.SwedenSouth'
metadata description = 'This module contains all the service tag IP addresses of StorageSyncService.SwedenSouth for Public.'
metadata author = ''
metadata author = ''

@description('StorageSyncService.SwedenSouth service tag IP addresses for Public')
@export()
var StorageSyncService_SwedenSouth = [
  '20.91.11.144/29'
  '51.12.204.248/29'
  '2603:1020:1104:400::320/123'
]
