// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 407
// Service tag  : StorageSyncService.AustraliaSoutheast

var StorageSyncService_AustraliaSoutheast = [
  '20.42.227.128/29'
  '2603:1010:101::340/123'
]
