// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-21
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 396
// Service tag  : StorageSyncService.DenmarkEast

var StorageSyncService_DenmarkEast = [
  '9.205.52.88/29'
  '9.205.75.40/29'
  '2603:1020:1602:4::/123'
  '2603:1020:1602:400::220/123'
]
