// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : StorageSyncService.NorthEurope

var StorageSyncService_NorthEurope = [
  '20.38.85.152/29'
  '2603:1020:5:1::300/123'
]
