// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : Storage.MalaysiaSouth
metadata name = 'Storage.MalaysiaSouth'
metadata description = 'This module contains all the service tag IP addresses of Storage.MalaysiaSouth for Public.'
metadata author = ''
metadata author = ''

@description('Storage.MalaysiaSouth service tag IP addresses for Public')
@export()
var Storage_MalaysiaSouth = [
  '20.157.238.0/24'
  '20.157.254.0/24'
  '20.209.66.0/23'
  '20.209.78.0/23'
  '2603:1040:1504::/48'
]
