// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : Storage.NorwayEast
metadata name = 'Storage.NorwayEast'
metadata description = 'This module contains all the service tag IP addresses of Storage.NorwayEast for Public.'
metadata author = ''
metadata author = ''

@description('Storage.NorwayEast service tag IP addresses for Public')
@export()
var Storage_NorwayEast = [
  '20.33.194.0/24'
  '20.38.120.0/24'
  '20.47.48.0/24'
  '20.60.206.0/23'
  '20.150.53.0/24'
  '20.150.121.0/24'
  '20.153.16.0/24'
  '20.153.94.0/24'
  '20.157.165.0/24'
  '20.209.24.0/23'
  '20.209.252.0/23'
  '57.150.208.0/23'
  '135.130.82.0/23'
  '2603:1020:e05::/48'
]
