// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : Storage.MexicoCentral
metadata name = 'Storage.MexicoCentral'
metadata description = 'This module contains all the service tag IP addresses of Storage.MexicoCentral for Public.'
metadata author = ''
metadata author = ''

@description('Storage.MexicoCentral service tag IP addresses for Public')
@export()
var Storage_MexicoCentral = [
  '20.33.130.0/24'
  '20.33.179.0/24'
  '20.60.96.0/23'
  '20.60.110.0/23'
  '20.153.92.0/24'
  '20.157.241.0/24'
  '20.209.122.0/23'
  '20.209.222.0/23'
  '2603:1030:704::/48'
]
