// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : Storage.IndonesiaCentral
metadata name = 'Storage.IndonesiaCentral'
metadata description = 'This module contains all the service tag IP addresses of Storage.IndonesiaCentral for Public.'
metadata author = ''
metadata author = ''

@description('Storage.IndonesiaCentral service tag IP addresses for Public')
@export()
var Storage_IndonesiaCentral = [
  '20.33.210.0/24'
  '20.33.219.0/24'
  '20.60.123.0/24'
  '20.60.124.0/22'
  '20.153.52.0/24'
  '57.150.6.0/23'
  '2603:1040:1803::/48'
]
