// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : Storage.SpainCentral

var Storage_SpainCentral = [
  '20.33.131.0/24'
  '20.33.183.0/24'
  '20.60.98.0/23'
  '20.60.100.0/23'
  '20.60.109.0/24'
  '20.153.9.0/24'
  '20.157.243.0/24'
  '20.209.228.0/23'
  '135.130.58.0/23'
  '2603:1020:1404::/48'
]
