// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : Storage.NewZealandNorth

var Storage_NewZealandNorth = [
  '20.33.190.0/24'
  '20.33.196.0/24'
  '20.60.115.0/24'
  '20.60.116.0/23'
  '20.153.23.0/24'
  '20.209.246.0/23'
  '135.130.128.0/23'
  '2603:1010:503::/48'
]
