// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : Storage.GermanyNorth
metadata name = 'Storage.GermanyNorth'
metadata description = 'This module contains all the service tag IP addresses of Storage.GermanyNorth for Public.'
metadata author = ''
metadata author = ''

@description('Storage.GermanyNorth service tag IP addresses for Public')
@export()
var Storage_GermanyNorth = [
  '20.38.115.0/24'
  '20.47.45.0/24'
  '20.150.60.0/24'
  '20.150.112.0/24'
  '20.153.123.0/24'
  '20.157.229.0/24'
  '20.209.206.0/23'
  '57.150.216.0/23'
  '2603:1020:d05::/48'
]
