// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : Storage.JioIndiaCentral

var Storage_JioIndiaCentral = [
  '20.60.170.0/23'
  '20.150.64.0/24'
  '20.150.109.0/24'
  '20.153.43.0/24'
  '20.157.152.0/24'
  '20.157.233.0/24'
  '57.150.184.0/23'
  '135.130.44.0/23'
  '2603:1040:1100::/48'
]
