// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : Storage.MalaysiaWest

var Storage_MalaysiaWest = [
  '20.33.140.0/24'
  '20.33.235.0/24'
  '20.60.103.0/24'
  '20.60.104.0/24'
  '20.153.53.0/24'
  '20.209.140.0/23'
  '57.150.94.0/23'
  '57.150.100.0/24'
  '2603:1040:1603::/48'
]
