// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : MicrosoftCloudAppSecurity.GermanyWestCentral

var MicrosoftCloudAppSecurity_GermanyWestCentral = [
  '20.52.42.71/32'
  '20.52.42.88/32'
  '20.52.42.103/32'
  '20.52.48.3/32'
  '20.170.36.122/32'
  '20.170.36.209/32'
  '20.218.181.177/32'
  '20.218.182.135/32'
]
