// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-10
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 408
// Service tag  : MicrosoftCloudAppSecurity.EastUS2EUAP

var MicrosoftCloudAppSecurity_EastUS2EUAP = [
  '172.173.47.82/31'
  '172.173.47.88/29'
]
