// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : MicrosoftCloudAppSecurity.FranceSouth

@export()
var MicrosoftCloudAppSecurity_FranceSouth = [
  '4.251.224.184/29'
  '4.251.231.56/31'
  '4.251.231.80/28'
  '4.251.231.96/27'
  '20.111.79.110/31'
  '40.79.180.64/27'
]
