// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_AzureGovernment.json
// Cloud        : AzureGovernment
// Change number: 390
// Service tag  : ApiManagement.USDoDEast

var ApiManagement_USDoDEast = [
  '20.141.20.112/28'
  '52.181.32.192/32'
  '2001:489a:3303:402::140/124'
]
