// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-21
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 396
// Service tag  : Storage.SoutheastUS

var Storage_SoutheastUS = [
  '20.33.215.0/24'
  '20.153.26.0/24'
  '57.150.23.0/24'
  '57.150.24.0/23'
  '57.150.93.0/24'
  '2603:1030:903::/48'
]
