// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_China.json
// Cloud        : China
// Service tag  : MicrosoftCloudAppSecurity.ChinaNorth

@export()
var MicrosoftCloudAppSecurity_ChinaNorth = [
  '139.217.52.112/28'
]
