// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-21
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 396
// Service tag  : PowerQueryOnline.QatarCentral

var PowerQueryOnline_QatarCentral = [
  '20.21.32.20/31'
  '20.21.46.164/31'
  '20.21.55.160/29'
  '20.21.69.188/31'
  '20.21.77.206/31'
  '20.21.80.20/31'
  '2603:1040:1002::400/123'
  '2603:1040:1002:400::228/125'
  '2603:1040:1002:800::2c0/125'
]
