// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-21
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 396
// Service tag  : Dynamics365ForMarketingEmail.SwitzerlandNorth

var Dynamics365ForMarketingEmail_SwitzerlandNorth = [
  '51.107.129.64/27'
]
