// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureArcInfrastructure.IsraelNorthwest
metadata name = 'AzureArcInfrastructure.IsraelNorthwest'
metadata description = 'This module contains all the service tag IP addresses of AzureArcInfrastructure.IsraelNorthwest for Public.'
metadata author = ''
metadata author = ''

@description('AzureArcInfrastructure.IsraelNorthwest service tag IP addresses for Public')
@export()
var AzureArcInfrastructure_IsraelNorthwest = [
  '51.4.131.208/30'
  '51.4.147.195/32'
  '51.4.156.75/32'
  '51.4.160.56/32'
  '51.4.227.192/31'
  '2603:1040:1702:2::20/124'
  '2603:1040:1702:5::37a/127'
  '2603:1040:1702:5::37c/128'
]
