// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureArcInfrastructure.IndiaSouthCentral

@export()
var AzureArcInfrastructure_IndiaSouthCentral = [
  '172.198.94.164/30'
  '172.198.114.104/32'
  '2603:1040:1904:2::380/124'
]
