// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureArcInfrastructure.WestIndia
metadata name = 'AzureArcInfrastructure.WestIndia'
metadata description = 'This module contains all the service tag IP addresses of AzureArcInfrastructure.WestIndia for Public.'
metadata author = ''
metadata author = ''

@description('AzureArcInfrastructure.WestIndia service tag IP addresses for Public')
@export()
var AzureArcInfrastructure_WestIndia = [
  '20.207.175.32/29'
  '20.207.175.102/31'
  '52.136.51.68/30'
  '57.159.152.62/32'
  '57.159.152.100/30'
  '104.211.146.248/30'
  '2603:1040:806:3::7c0/124'
  '2603:1040:806:7::499/128'
  '2603:1040:806:7::49a/127'
]
