// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureArcInfrastructure.SoutheastUS

var AzureArcInfrastructure_SoutheastUS = [
  '57.151.220.212/30'
  '68.154.136.52/32'
  '68.154.147.29/32'
  '2603:1030:902:2::280/124'
]
