// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureArcInfrastructure.AustraliaCentral2
metadata name = 'AzureArcInfrastructure.AustraliaCentral2'
metadata description = 'This module contains all the service tag IP addresses of AzureArcInfrastructure.AustraliaCentral2 for Public.'
metadata author = ''
metadata author = ''

@description('AzureArcInfrastructure.AustraliaCentral2 service tag IP addresses for Public')
@export()
var AzureArcInfrastructure_AustraliaCentral2 = [
  '20.36.122.52/30'
  '20.167.131.114/31'
  '20.167.131.120/29'
  '20.193.96.16/30'
  '2603:1010:404:5::4d0/124'
]
