// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureArcInfrastructure.FranceSouth
metadata name = 'AzureArcInfrastructure.FranceSouth'
metadata description = 'This module contains all the service tag IP addresses of AzureArcInfrastructure.FranceSouth for Public.'
metadata author = ''
metadata author = ''

@description('AzureArcInfrastructure.FranceSouth service tag IP addresses for Public')
@export()
var AzureArcInfrastructure_FranceSouth = [
  '20.111.72.136/29'
  '40.80.103.250/31'
  '51.105.90.148/30'
  '51.138.160.92/30'
  '2603:1020:905:5::440/124'
]
