// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureArcInfrastructure.PolandCentral
metadata name = 'AzureArcInfrastructure.PolandCentral'
metadata description = 'This module contains all the service tag IP addresses of AzureArcInfrastructure.PolandCentral for Public.'
metadata author = ''
metadata author = ''

@description('AzureArcInfrastructure.PolandCentral service tag IP addresses for Public')
@export()
var AzureArcInfrastructure_PolandCentral = [
  '20.215.21.178/32'
  '20.215.170.104/30'
  '20.215.174.6/31'
  '20.215.174.24/29'
  '134.112.73.70/32'
  '134.112.73.72/30'
  '134.112.168.132/32'
  '2603:1020:1302:4::2ac/127'
  '2603:1020:1302:4::2ae/128'
  '2603:1020:1302:8::398/128'
]
