// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureArcInfrastructure.JapanWest
metadata name = 'AzureArcInfrastructure.JapanWest'
metadata description = 'This module contains all the service tag IP addresses of AzureArcInfrastructure.JapanWest for Public.'
metadata author = ''
metadata author = ''

@description('AzureArcInfrastructure.JapanWest service tag IP addresses for Public')
@export()
var AzureArcInfrastructure_JapanWest = [
  '4.190.132.42/31'
  '4.190.132.184/29'
  '40.74.102.16/30'
  '40.80.59.24/30'
  '172.192.187.112/32'
  '2603:1040:606:b::637/128'
]
