// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureArcInfrastructure.UKSouth
metadata name = 'AzureArcInfrastructure.UKSouth'
metadata description = 'This module contains all the service tag IP addresses of AzureArcInfrastructure.UKSouth for Public.'
metadata author = ''
metadata author = ''

@description('AzureArcInfrastructure.UKSouth service tag IP addresses for Public')
@export()
var AzureArcInfrastructure_UKSouth = [
  '51.104.15.254/32'
  '51.104.28.216/30'
  '51.104.31.172/30'
  '51.105.71.144/31'
  '51.105.77.50/31'
  '51.140.151.168/30'
  '74.177.105.18/32'
  '172.167.234.102/31'
  '172.167.236.56/29'
  '2603:1020:705:15::547/128'
]
