// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureArcInfrastructure.SouthAfricaWest

var AzureArcInfrastructure_SouthAfricaWest = [
  '40.117.28.40/29'
  '40.117.28.96/31'
  '102.37.64.160/30'
  '102.133.57.188/30'
]
