// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureArcInfrastructure.TaiwanNorth
metadata name = 'AzureArcInfrastructure.TaiwanNorth'
metadata description = 'This module contains all the service tag IP addresses of AzureArcInfrastructure.TaiwanNorth for Public.'
metadata author = ''
metadata author = ''

@description('AzureArcInfrastructure.TaiwanNorth service tag IP addresses for Public')
@export()
var AzureArcInfrastructure_TaiwanNorth = [
  '51.53.41.76/30'
  '51.53.43.104/29'
  '51.53.43.112/31'
  '51.53.110.138/32'
  '2603:1040:1302:2::620/124'
]
