// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureArcInfrastructure.CentralUS
metadata name = 'AzureArcInfrastructure.CentralUS'
metadata description = 'This module contains all the service tag IP addresses of AzureArcInfrastructure.CentralUS for Public.'
metadata author = ''
metadata author = ''

@description('AzureArcInfrastructure.CentralUS service tag IP addresses for Public')
@export()
var AzureArcInfrastructure_CentralUS = [
  '13.89.179.20/30'
  '13.89.179.24/32'
  '20.40.200.152/29'
  '20.40.224.52/30'
  '20.44.13.240/31'
  '52.182.141.60/31'
  '74.249.138.70/31'
  '74.249.138.88/29'
  '172.202.64.0/22'
  '2603:1030:13:200::/62'
]
