// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-21
// Source file  : ServiceTags_AzureGermany.json
// Cloud        : AzureGermany
// Change number: 193
// Service tag  : AppServiceManagement.GermanyCentral

var AppServiceManagement_GermanyCentral = [
  '51.8.234.128/26'
]
