// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-06-08
// Source file  : ServiceTags_China.json
// Cloud        : China
// Change number: 397
// Service tag  : AzureAttestation.ChinaEast

var AzureAttestation_ChinaEast = [
  '52.130.112.132/30'
]
