// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-21
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 396
// Service tag  : ServiceFabric.ItalyNorth

var ServiceFabric_ItalyNorth = [
  '4.232.106.76/30'
  '4.232.122.72/30'
  '4.232.194.72/30'
  '2603:1020:1204:400::58/125'
  '2603:1020:1204:800::10/125'
  '2603:1020:1204:c00::10/125'
]
