// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_China.json
// Cloud        : China
// Service tag  : AzureDataExplorerManagement.ChinaEast3
metadata name = 'AzureDataExplorerManagement.ChinaEast3'
metadata description = 'This module contains all the service tag IP addresses of AzureDataExplorerManagement.ChinaEast3 for China.'
metadata author = ''
metadata author = ''

@description('AzureDataExplorerManagement.ChinaEast3 service tag IP addresses for China')
@export()
var AzureDataExplorerManagement_ChinaEast3 = [
  '52.131.149.0/28'
  '163.228.53.208/29'
  '2406:e500:2402::100/121'
]
