// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_China.json
// Cloud        : China
// Service tag  : AzureDataExplorerManagement.ChinaNorth2
metadata name = 'AzureDataExplorerManagement.ChinaNorth2'
metadata description = 'This module contains all the service tag IP addresses of AzureDataExplorerManagement.ChinaNorth2 for China.'
metadata author = ''
metadata author = ''

@description('AzureDataExplorerManagement.ChinaNorth2 service tag IP addresses for China')
@export()
var AzureDataExplorerManagement_ChinaNorth2 = [
  '40.73.6.21/32'
  '40.73.139.176/28'
  '52.131.66.200/29'
  '139.217.60.6/32'
  '2404:7940:101:1::500/121'
  '2404:7940:101:402::950/124'
]
