// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_China.json
// Cloud        : China
// Service tag  : AzureDataExplorerManagement.ChinaEast
metadata name = 'AzureDataExplorerManagement.ChinaEast'
metadata description = 'This module contains all the service tag IP addresses of AzureDataExplorerManagement.ChinaEast for China.'
metadata author = ''
metadata author = ''

@description('AzureDataExplorerManagement.ChinaEast service tag IP addresses for China')
@export()
var AzureDataExplorerManagement_ChinaEast = [
  '40.72.169.136/29'
  '139.217.172.0/28'
  '2404:7940:201:1::500/121'
  '2404:7940:201:402::150/124'
]
