// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-06-01
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 402
// Service tag  : LogicApps.NortheastUS5

var LogicApps_NortheastUS5 = [
  '172.194.85.240/28'
  '172.194.86.0/27'
  '2603:1030:1602:3::600/124'
  '2603:1030:1602:3::620/123'
]
