// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : LogicApps.EastUS3
metadata name = 'LogicApps.EastUS3'
metadata description = 'This module contains all the service tag IP addresses of LogicApps.EastUS3 for Public.'
metadata author = ''
metadata author = ''

@description('LogicApps.EastUS3 service tag IP addresses for Public')
@export()
var LogicApps_EastUS3 = [
  '134.138.84.192/28'
  '134.138.84.224/27'
  '2603:1030:1402:3::2e0/124'
  '2603:1030:1402:3::300/123'
]
