// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 407
// Service tag  : LogicApps.IndiaSouthCentral

var LogicApps_IndiaSouthCentral = [
  '172.198.100.144/28'
  '172.198.100.160/27'
  '2603:1040:1904:4::10/124'
  '2603:1040:1904:4::80/123'
]
