// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : LogicApps.PolandCentral

var LogicApps_PolandCentral = [
  '20.215.75.240/28'
  '20.215.158.80/28'
  '20.215.158.96/27'
  '74.248.81.46/32'
  '74.248.81.64/32'
  '74.248.81.148/32'
  '74.248.81.204/32'
  '74.248.81.211/32'
  '74.248.81.229/32'
  '74.248.81.234/32'
  '74.248.81.255/32'
  '74.248.82.58/32'
  '74.248.82.188/31'
  '74.248.82.216/32'
  '74.248.82.221/32'
  '74.248.82.253/32'
  '74.248.83.27/32'
  '74.248.83.63/32'
  '74.248.173.160/28'
  '2603:1020:1302:400::3b0/124'
  '2603:1020:1302:400::3c0/123'
]
