// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_China.json
// Cloud        : China
// Change number: 393
// Service tag  : MicrosoftPurviewPolicyDistribution

var MicrosoftPurviewPolicyDistribution = [
  '40.162.70.188/30'
]
