// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_AzureGovernment.json
// Cloud        : AzureGovernment
// Change number: 390
// Service tag  : PowerQueryOnline.USGovTexas

var PowerQueryOnline_USGovTexas = [
  '20.140.56.116/31'
  '20.140.147.174/31'
  '20.140.151.64/29'
  '20.159.106.40/29'
  '20.159.106.48/28'
  '2001:489a:3403::200/123'
]
