// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_AzureGovernment.json
// Cloud        : AzureGovernment
// Change number: 390
// Service tag  : PowerQueryOnline.USDoDCentral

var PowerQueryOnline_USDoDCentral = [
  '20.140.72.116/31'
  '52.126.249.40/29'
  '52.126.249.48/28'
  '52.245.154.232/29'
  '2001:489a:3203::200/123'
]
