// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_AzureGermany.json
// Cloud        : AzureGermany
// Change number: 193
// Service tag  : AzureCognitiveSearch.GermanyNorthEast

var AzureCognitiveSearch_GermanyNorthEast = [
  '51.18.40.96/28'
]
