// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : PowerPlatformInfra.BrazilSoutheast

var PowerPlatformInfra_BrazilSoutheast = [
  '20.206.3.24/29'
  '20.206.3.32/27'
  '20.206.3.64/26'
  '20.206.3.128/25'
  '20.206.4.0/26'
  '108.140.87.192/29'
  '108.140.88.192/26'
  '2603:1061:2002:1000::/57'
]
