// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : PowerPlatformInfra.TaiwanNorthwest

@export()
var PowerPlatformInfra_TaiwanNorthwest = [
  '57.170.1.128/25'
  '57.170.2.0/24'
]
