// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : PowerPlatformInfra.EastUS2

var PowerPlatformInfra_EastUS2 = [
  '40.84.87.192/26'
  '40.84.88.0/23'
  '40.84.90.0/26'
  '57.162.15.128/25'
  '2603:1061:2002:300::/57'
]
