// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : PowerPlatformInfra.DenmarkEast

@export()
var PowerPlatformInfra_DenmarkEast = [
  '9.205.180.128/25'
  '9.205.181.0/24'
]
