// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-10
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 408
// Service tag  : PowerPlatformInfra.IsraelNorthwest

var PowerPlatformInfra_IsraelNorthwest = [
  '51.4.231.0/24'
  '51.58.144.0/25'
]
