// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-06-01
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 402
// Service tag  : PowerPlatformInfra.TaiwanNorthwest

var PowerPlatformInfra_TaiwanNorthwest = [
  '57.170.1.128/25'
  '57.170.2.0/24'
]
