// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureContainerRegistry.NorwayWest
metadata name = 'AzureContainerRegistry.NorwayWest'
metadata description = 'This module contains all the service tag IP addresses of AzureContainerRegistry.NorwayWest for Public.'
metadata author = ''
metadata author = ''

@description('AzureContainerRegistry.NorwayWest service tag IP addresses for Public')
@export()
var AzureContainerRegistry_NorwayWest = [
  '4.220.142.128/26'
  '51.13.128.128/25'
  '51.13.129.0/26'
  '51.120.182.128/26'
  '51.120.218.24/29'
  '2603:1020:f04:1::4b0/125'
  '2603:1020:f04:6::780/122'
  '2603:1020:f04:402::90/125'
  '2603:1020:f04:402::340/122'
  '2603:1020:f04:402::580/122'
  '2603:1020:f04:402::600/121'
]
