// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-21
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 396
// Service tag  : AzureContainerRegistry.SouthCentralUSSTG

var AzureContainerRegistry_SouthCentralUSSTG = [
  '20.44.2.24/29'
  '2603:1030:302:402::c0/122'
]
