// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-21
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 396
// Service tag  : AzureDataExplorerManagement.EastUSSTG

var AzureDataExplorerManagement_EastUSSTG = [
  '20.99.9.224/28'
  '2603:1030:104::600/121'
  '2603:1030:104:402::150/124'
]
