// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-06-22
// Source file  : ServiceTags_China.json
// Cloud        : China
// Change number: 400
// Service tag  : ServiceBus.ChinaNorth

var ServiceBus_ChinaNorth = [
  '52.130.48.192/26'
  '139.217.48.64/27'
  '2404:7940:1:1::700/120'
  '2404:7940:1:402::170/125'
]
