// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-10
// Source file  : ServiceTags_China.json
// Cloud        : China
// Service tag  : AzureMachineLearning.ChinaNorth

var AzureMachineLearning_ChinaNorth = [
  '2404:7940:1::240/122'
]
