// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_China.json
// Cloud        : China
// Service tag  : AzureMachineLearning.ChinaNorth2

@export()
var AzureMachineLearning_ChinaNorth2 = [
  '52.130.18.0/28'
  '159.27.147.144/28'
  '2404:7940:101::240/122'
]
