// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureCognitiveSearch.WestIndia

var AzureCognitiveSearch_WestIndia = [
  '52.136.48.128/26'
  '2603:1040:806::180/121'
]
