// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-10
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureCognitiveSearch.SoutheastUS

var AzureCognitiveSearch_SoutheastUS = [
  '57.151.208.192/26'
  '2603:1030:902::100/121'
]
