// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : AzureCognitiveSearch.MalaysiaWest

var AzureCognitiveSearch_MalaysiaWest = [
  '20.17.112.192/26'
  '2603:1040:1602::100/121'
]
