// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : AzureCognitiveSearch.NorthEurope

var AzureCognitiveSearch_NorthEurope = [
  '20.38.84.0/26'
  '52.155.216.245/32'
  '52.155.221.250/32'
  '52.155.222.56/32'
  '2603:1020:5:1::180/121'
]
