// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureCognitiveSearch.BrazilSouth

var AzureCognitiveSearch_BrazilSouth = [
  '191.235.225.64/26'
  '2603:1050:6:1::180/121'
]
