// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureCognitiveSearch.MalaysiaWest
metadata name = 'AzureCognitiveSearch.MalaysiaWest'
metadata description = 'This module contains all the service tag IP addresses of AzureCognitiveSearch.MalaysiaWest for Public.'
metadata author = ''
metadata author = ''

@description('AzureCognitiveSearch.MalaysiaWest service tag IP addresses for Public')
@export()
var AzureCognitiveSearch_MalaysiaWest = [
  '20.17.112.192/26'
  '2603:1040:1602::100/121'
]
