// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureCognitiveSearch.SwitzerlandWest
metadata name = 'AzureCognitiveSearch.SwitzerlandWest'
metadata description = 'This module contains all the service tag IP addresses of AzureCognitiveSearch.SwitzerlandWest for Public.'
metadata author = ''
metadata author = ''

@description('AzureCognitiveSearch.SwitzerlandWest service tag IP addresses for Public')
@export()
var AzureCognitiveSearch_SwitzerlandWest = [
  '51.107.144.128/26'
  '2603:1020:b04::180/121'
]
