// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-10
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureCognitiveSearch.NortheastUS5

var AzureCognitiveSearch_NortheastUS5 = [
  '172.194.64.192/26'
  '2603:1030:1602::100/121'
]
