// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureCognitiveSearch.IsraelNorthwest

@export()
var AzureCognitiveSearch_IsraelNorthwest = [
  '20.217.248.192/26'
  '2603:1040:1702::100/121'
]
