// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureCognitiveSearch.CentralIndia

var AzureCognitiveSearch_CentralIndia = [
  '52.140.105.64/26'
  '2603:1040:a06:1::180/121'
]
