// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureCognitiveSearch.JioIndiaWest
metadata name = 'AzureCognitiveSearch.JioIndiaWest'
metadata description = 'This module contains all the service tag IP addresses of AzureCognitiveSearch.JioIndiaWest for Public.'
metadata author = ''
metadata author = ''

@description('AzureCognitiveSearch.JioIndiaWest service tag IP addresses for Public')
@export()
var AzureCognitiveSearch_JioIndiaWest = [
  '20.192.161.0/26'
  '40.64.8.64/26'
  '2603:1040:d04::180/121'
]
