// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-10
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureCognitiveSearch.KoreaCentral

var AzureCognitiveSearch_KoreaCentral = [
  '20.41.65.64/26'
  '2603:1040:f05:1::180/121'
]
