// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureCognitiveSearch.SouthIndia
metadata name = 'AzureCognitiveSearch.SouthIndia'
metadata description = 'This module contains all the service tag IP addresses of AzureCognitiveSearch.SouthIndia for Public.'
metadata author = ''
metadata author = ''

@description('AzureCognitiveSearch.SouthIndia service tag IP addresses for Public')
@export()
var AzureCognitiveSearch_SouthIndia = [
  '20.41.193.64/26'
  '2603:1040:c06::180/121'
]
