// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureCognitiveSearch.GermanyNorth

var AzureCognitiveSearch_GermanyNorth = [
  '20.113.251.64/26'
  '51.116.48.96/28'
  '2603:1020:d04::180/121'
]
