// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureCognitiveSearch.FranceCentral

var AzureCognitiveSearch_FranceCentral = [
  '20.43.41.64/26'
  '2603:1020:805:1::180/121'
]
