// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureCognitiveSearch.SouthAfricaNorth

@export()
var AzureCognitiveSearch_SouthAfricaNorth = [
  '102.133.217.128/26'
  '2603:1000:104:1::180/121'
]
