// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureCognitiveSearch.AustriaEast

var AzureCognitiveSearch_AustriaEast = [
  '68.210.160.192/26'
  '2603:1020:104:3::780/121'
]
