// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureCognitiveSearch.UKWest

var AzureCognitiveSearch_UKWest = [
  '51.137.161.64/26'
  '2603:1020:605::180/121'
]
