// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureCognitiveSearch.SouthCentralUS

var AzureCognitiveSearch_SouthCentralUS = [
  '40.80.217.38/32'
  '40.119.11.0/26'
  '52.185.224.13/32'
  '2603:1030:807:1::180/121'
]
