// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureCognitiveSearch.AustraliaEast

var AzureCognitiveSearch_AustraliaEast = [
  '20.37.193.192/26'
  '20.40.123.36/32'
  '20.40.123.46/32'
  '2603:1010:6:1::180/121'
]
