// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : AzureCognitiveSearch.UKSouth

var AzureCognitiveSearch_UKSouth = [
  '51.104.25.64/26'
  '51.145.124.157/32'
  '51.145.124.158/32'
  '2603:1020:705:1::180/121'
]
