// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureCognitiveSearch.AustraliaCentral2
metadata name = 'AzureCognitiveSearch.AustraliaCentral2'
metadata description = 'This module contains all the service tag IP addresses of AzureCognitiveSearch.AustraliaCentral2 for Public.'
metadata author = ''
metadata author = ''

@description('AzureCognitiveSearch.AustraliaCentral2 service tag IP addresses for Public')
@export()
var AzureCognitiveSearch_AustraliaCentral2 = [
  '20.36.120.128/26'
  '2603:1010:404::180/121'
]
