// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-18
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 400
// Service tag  : AzureCognitiveSearch.EastUS

var AzureCognitiveSearch_EastUS = [
  '20.42.4.128/26'
  '2603:1030:210:1::180/121'
]
