// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-06-15
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 404
// Service tag  : AzureCognitiveSearch.IndiaSouthCentral

var AzureCognitiveSearch_IndiaSouthCentral = [
  '172.198.80.192/26'
  '2603:1040:1904::100/121'
]
