// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureCognitiveSearch.NewZealandNorth

@export()
var AzureCognitiveSearch_NewZealandNorth = [
  '172.204.152.192/26'
  '2603:1010:502::100/121'
]
