// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureCognitiveSearch.NorthCentralUS

var AzureCognitiveSearch_NorthCentralUS = [
  '23.100.238.37/32'
  '40.80.186.192/26'
  '2603:1030:608::180/121'
]
