// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-21
// Source file  : ServiceTags_China.json
// Cloud        : China
// Change number: 391
// Service tag  : ServiceBus.ChinaEast

var ServiceBus_ChinaEast = [
  '40.72.168.128/26'
  '139.217.168.64/27'
  '2404:7940:201:1::700/120'
  '2404:7940:201:402::170/125'
]
