// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_AzureGovernment.json
// Cloud        : AzureGovernment
// Change number: 390
// Service tag  : AzureSecurityCenter.USDoDEast

var AzureSecurityCenter_USDoDEast = [
  '52.181.46.0/23'
  '52.245.136.0/27'
]
