// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureFrontDoor.MicrosoftSecurity
metadata name = 'AzureFrontDoor.MicrosoftSecurity'
metadata description = 'This module contains all the service tag IP addresses of AzureFrontDoor.MicrosoftSecurity for Public.'
metadata author = ''
metadata author = ''

@description('AzureFrontDoor.MicrosoftSecurity service tag IP addresses for Public')
@export()
var AzureFrontDoor_MicrosoftSecurity = [
  '13.107.219.0/24'
  '13.107.227.0/24'
  '13.107.228.0/23'
  '150.171.97.0/24'
  '2620:1ec:40::/48'
  '2620:1ec:49::/48'
  '2620:1ec:4a::/47'
]
