// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_China.json
// Cloud        : China
// Service tag  : AzureIoTHub.ChinaNorth
metadata name = 'AzureIoTHub.ChinaNorth'
metadata description = 'This module contains all the service tag IP addresses of AzureIoTHub.ChinaNorth for China.'
metadata author = ''
metadata author = ''

@description('AzureIoTHub.ChinaNorth service tag IP addresses for China')
@export()
var AzureIoTHub_ChinaNorth = [
  '40.72.74.224/27'
  '40.72.75.0/25'
  '139.217.25.251/32'
  '139.217.52.128/27'
  '2404:7940:1:402::2e0/123'
]
