// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-10
// Source file  : ServiceTags_China.json
// Cloud        : China
// Service tag  : AzureIoTHub.ChinaNorth2

var AzureIoTHub_ChinaNorth2 = [
  '40.73.28.109/32'
  '40.73.28.135/32'
  '40.73.141.32/27'
  '40.162.128.48/29'
  '40.162.128.56/30'
  '40.162.128.60/31'
  '52.130.18.64/27'
  '52.130.18.128/25'
  '139.217.126.205/32'
  '2404:7940:101:3::668/125'
  '2404:7940:101:3::670/126'
  '2404:7940:101:3::674/127'
  '2404:7940:101:3::676/128'
  '2404:7940:101:402::ae0/123'
]
