// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-21
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 396
// Service tag  : AzureIoTHub.SwitzerlandWest

var AzureIoTHub_SwitzerlandWest = [
  '51.107.147.64/27'
  '51.107.147.128/25'
  '51.107.156.96/27'
  '2603:1020:b04:402::300/123'
]
