// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_China.json
// Cloud        : China
// Service tag  : StorageSyncService.ChinaNorth3
metadata name = 'StorageSyncService.ChinaNorth3'
metadata description = 'This module contains all the service tag IP addresses of StorageSyncService.ChinaNorth3 for China.'
metadata author = ''
metadata author = ''

@description('StorageSyncService.ChinaNorth3 service tag IP addresses for China')
@export()
var StorageSyncService_ChinaNorth3 = [
  '40.162.75.40/29'
  '40.162.75.64/29'
  '52.131.29.176/29'
  '2406:e500:2602:400::3a0/123'
]
