// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_China.json
// Cloud        : China
// Change number: 393
// Service tag  : StorageSyncService.ChinaEast3

var StorageSyncService_ChinaEast3 = [
  '52.131.157.176/29'
  '2406:e500:2402:400::3a0/123'
]
