// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_China.json
// Cloud        : China
// Change number: 393
// Service tag  : StorageSyncService.ChinaEast2

var StorageSyncService_ChinaEast2 = [
  '163.228.193.208/29'
  '2404:7940:301::220/123'
  '2404:7940:301:402::480/123'
]
