// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-21
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 396
// Service tag  : BatchNodeManagement.MalaysiaWest

var BatchNodeManagement_MalaysiaWest = [
  '20.17.113.64/27'
  '2603:1040:1602::300/122'
]
