// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-21
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 396
// Service tag  : BatchNodeManagement.WestUS3

var BatchNodeManagement_WestUS3 = [
  '20.150.161.224/27'
  '20.150.172.0/27'
  '20.150.179.96/27'
  '20.150.187.96/27'
  '2603:1030:504:1::340/122'
]
