// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_AzureGermany.json
// Cloud        : AzureGermany
// Change number: 193
// Service tag  : AzureBackup.GermanyNorthEast

var AzureBackup_GermanyNorthEast = [
  '51.8.227.0/26'
  '51.8.227.64/27'
]
