// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_China.json
// Cloud        : China
// Change number: 392
// Service tag  : GatewayManager.ChinaEast

var GatewayManager_ChinaEast = [
  '40.72.169.160/27'
  '52.130.8.72/29'
  '139.217.171.0/29'
  '2404:7940:201::40/122'
]
