// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_China.json
// Cloud        : China
// Change number: 393
// Service tag  : GatewayManager.ChinaNorth

var GatewayManager_ChinaNorth = [
  '40.72.72.72/29'
  '52.130.50.0/27'
  '139.217.51.0/29'
  '2404:7940:1::40/122'
]
