// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_China.json
// Cloud        : China
// Service tag  : GatewayManager.ChinaEast2
metadata name = 'GatewayManager.ChinaEast2'
metadata description = 'This module contains all the service tag IP addresses of GatewayManager.ChinaEast2 for China.'
metadata author = ''
metadata author = ''

@description('GatewayManager.ChinaEast2 service tag IP addresses for China')
@export()
var GatewayManager_ChinaEast2 = [
  '40.73.168.240/29'
  '52.130.0.72/29'
  '52.131.194.128/27'
  '2404:7940:301::40/122'
]
