// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_China.json
// Cloud        : China
// Service tag  : GatewayManager.ChinaEast2

@export()
var GatewayManager_ChinaEast2 = [
  '40.73.168.240/29'
  '52.130.0.72/29'
  '52.131.194.128/27'
  '2404:7940:301::40/122'
]
