// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : PowerQueryOnline.NorwayWest
metadata name = 'PowerQueryOnline.NorwayWest'
metadata description = 'This module contains all the service tag IP addresses of PowerQueryOnline.NorwayWest for Public.'
metadata author = ''
metadata author = ''

@description('PowerQueryOnline.NorwayWest service tag IP addresses for Public')
@export()
var PowerQueryOnline_NorwayWest = [
  '4.220.142.240/28'
  '4.220.152.16/29'
  '51.13.128.116/31'
  '51.120.176.224/29'
  '51.120.224.120/31'
  '2603:1020:f04::200/123'
  '2603:1020:f04:402::160/125'
]
