// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : PowerQueryOnline.SouthCentralUSSTG

var PowerQueryOnline_SouthCentralUSSTG = [
  '20.45.112.120/31'
  '23.100.217.20/31'
  '23.100.217.24/29'
  '23.100.223.8/29'
  '23.100.223.128/28'
  '2603:1030:302:402::a0/126'
]
