// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : PowerQueryOnline.EastUS2

var PowerQueryOnline_EastUS2 = [
  '20.36.150.44/31'
  '20.41.0.68/30'
  '20.65.1.124/31'
  '20.98.195.176/29'
  '52.179.200.128/31'
  '104.208.207.40/29'
  '104.208.207.48/28'
  '172.175.14.20/30'
  '172.175.14.24/29'
  '2603:1030:40c:1::200/123'
  '2603:1030:40c:23::1c0/122'
  '2603:1030:40c:402::160/125'
  '2603:1030:40c:802::140/125'
  '2603:1030:40c:c00::20/125'
]
