// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : PowerQueryOnline.SpainCentral

var PowerQueryOnline_SpainCentral = [
  '68.221.80.40/29'
  '68.221.98.114/31'
  '68.221.107.0/28'
  '68.221.107.216/29'
  '68.221.146.88/31'
  '68.221.157.72/31'
  '2603:1020:1403::1c0/123'
  '2603:1020:1403:400::108/125'
  '2603:1020:1403:800::18/125'
  '2603:1020:1403:c00::58/125'
]
