// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : PowerQueryOnline.DenmarkEast

var PowerQueryOnline_DenmarkEast = [
  '9.205.32.40/29'
  '2603:1020:1602::1c0/123'
]
