// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : PowerQueryOnline.IsraelNorthwest
metadata name = 'PowerQueryOnline.IsraelNorthwest'
metadata description = 'This module contains all the service tag IP addresses of PowerQueryOnline.IsraelNorthwest for Public.'
metadata author = ''
metadata author = ''

@description('PowerQueryOnline.IsraelNorthwest service tag IP addresses for Public')
@export()
var PowerQueryOnline_IsraelNorthwest = [
  '20.217.248.40/29'
  '51.4.159.224/27'
  '2603:1040:1702::1c0/123'
  '2603:1040:1702:5::200/122'
]
