// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : PowerQueryOnline.IsraelNorthwest

var PowerQueryOnline_IsraelNorthwest = [
  '20.217.248.40/29'
  '2603:1040:1702::1c0/123'
]
