// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-06-08
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 403
// Service tag  : PowerQueryOnline.NortheastUS5

var PowerQueryOnline_NortheastUS5 = [
  '172.194.64.32/29'
  '172.194.86.128/27'
  '2603:1030:1602::1a0/123'
  '2603:1030:1602:3::6c0/122'
]
