// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 407
// Service tag  : PowerQueryOnline.IsraelNorthwest

var PowerQueryOnline_IsraelNorthwest = [
  '20.217.248.40/29'
  '51.4.159.224/27'
  '2603:1040:1702::1c0/123'
  '2603:1040:1702:5::200/122'
]
