// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : PowerQueryOnline.BrazilSoutheast
metadata name = 'PowerQueryOnline.BrazilSoutheast'
metadata description = 'This module contains all the service tag IP addresses of PowerQueryOnline.BrazilSoutheast for Public.'
metadata author = ''
metadata author = ''

@description('PowerQueryOnline.BrazilSoutheast service tag IP addresses for Public')
@export()
var PowerQueryOnline_BrazilSoutheast = [
  '20.206.4.72/29'
  '108.140.6.112/28'
  '108.140.24.152/29'
  '191.233.8.20/31'
  '191.237.224.234/31'
  '2603:1050:403::200/123'
  '2603:1050:403:400::88/125'
]
