// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : PowerQueryOnline.BelgiumCentral
metadata name = 'PowerQueryOnline.BelgiumCentral'
metadata description = 'This module contains all the service tag IP addresses of PowerQueryOnline.BelgiumCentral for Public.'
metadata author = ''
metadata author = ''

@description('PowerQueryOnline.BelgiumCentral service tag IP addresses for Public')
@export()
var PowerQueryOnline_BelgiumCentral = [
  '9.160.40.40/29'
  '2603:1020:1502::1c0/123'
]
