// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : PowerQueryOnline.SouthCentralUSSTG
metadata name = 'PowerQueryOnline.SouthCentralUSSTG'
metadata description = 'This module contains all the service tag IP addresses of PowerQueryOnline.SouthCentralUSSTG for Public.'
metadata author = ''
metadata author = ''

@description('PowerQueryOnline.SouthCentralUSSTG service tag IP addresses for Public')
@export()
var PowerQueryOnline_SouthCentralUSSTG = [
  '20.45.112.120/31'
  '23.100.217.20/31'
  '23.100.217.24/29'
  '23.100.223.8/29'
  '23.100.223.128/28'
  '2603:1030:302:402::a0/126'
]
