// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : PowerQueryOnline.GermanyNorth
metadata name = 'PowerQueryOnline.GermanyNorth'
metadata description = 'This module contains all the service tag IP addresses of PowerQueryOnline.GermanyNorth for Public.'
metadata author = ''
metadata author = ''

@description('PowerQueryOnline.GermanyNorth service tag IP addresses for Public')
@export()
var PowerQueryOnline_GermanyNorth = [
  '4.184.2.16/29'
  '20.170.175.240/28'
  '51.116.48.70/31'
  '51.116.78.40/29'
  '2603:1020:d04::200/123'
  '2603:1020:d04:402::160/125'
]
