// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureConnectors.SpainCentral

var AzureConnectors_SpainCentral = [
  '68.221.92.64/26'
  '68.221.248.51/32'
  '68.221.248.79/32'
  '2603:1020:1403:2::80/122'
]
