// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureConnectors.MalaysiaSouth
metadata name = 'AzureConnectors.MalaysiaSouth'
metadata description = 'This module contains all the service tag IP addresses of AzureConnectors.MalaysiaSouth for Public.'
metadata author = ''
metadata author = ''

@description('AzureConnectors.MalaysiaSouth service tag IP addresses for Public')
@export()
var AzureConnectors_MalaysiaSouth = [
  '20.17.25.0/26'
  '20.17.67.0/26'
  '2603:1040:1503:2::580/122'
  '2603:1040:1503:400::c0/122'
]
