// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-21
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 396
// Service tag  : AzureConnectors.UAECentral

var AzureConnectors_UAECentral = [
  '20.37.74.192/28'
  '20.45.67.36/32'
  '20.45.67.45/32'
  '20.45.90.208/28'
  '20.45.90.224/27'
  '40.120.8.0/27'
  '40.125.1.213/32'
  '40.125.2.230/32'
  '2603:1040:b04:5::380/122'
  '2603:1040:b04:402::180/122'
]
