// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureConnectors.JioIndiaWest
metadata name = 'AzureConnectors.JioIndiaWest'
metadata description = 'This module contains all the service tag IP addresses of AzureConnectors.JioIndiaWest for Public.'
metadata author = ''
metadata author = ''

@description('AzureConnectors.JioIndiaWest service tag IP addresses for Public')
@export()
var AzureConnectors_JioIndiaWest = [
  '20.193.206.192/26'
  '20.244.242.190/32'
  '20.244.246.22/32'
  '40.64.8.48/28'
  '40.64.8.128/27'
  '2603:1040:d04:c02::80/122'
]
