// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureConnectors.SoutheastAsia
metadata name = 'AzureConnectors.SoutheastAsia'
metadata description = 'This module contains all the service tag IP addresses of AzureConnectors.SoutheastAsia for Public.'
metadata author = ''
metadata author = ''

@description('AzureConnectors.SoutheastAsia service tag IP addresses for Public')
@export()
var AzureConnectors_SoutheastAsia = [
  '13.67.8.240/28'
  '13.67.15.32/27'
  '20.195.82.240/28'
  '20.195.83.0/27'
  '20.198.148.72/32'
  '20.198.213.242/32'
  '20.198.215.60/32'
  '20.205.248.224/32'
  '52.187.68.19/32'
  '52.187.147.27/32'
  '2603:1040:5:402::180/122'
]
