// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureConnectors.CentralUSEUAP
metadata name = 'AzureConnectors.CentralUSEUAP'
metadata description = 'This module contains all the service tag IP addresses of AzureConnectors.CentralUSEUAP for Public.'
metadata author = ''
metadata author = ''

@description('AzureConnectors.CentralUSEUAP service tag IP addresses for Public')
@export()
var AzureConnectors_CentralUSEUAP = [
  '20.45.240.112/28'
  '20.45.241.128/27'
  '20.45.250.177/32'
  '20.228.37.79/32'
  '40.78.202.96/28'
  '52.180.164.214/32'
  '168.61.140.0/27'
  '168.61.143.64/26'
  '2603:1030:f:400::980/122'
]
