// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureConnectors.ItalyNorth
metadata name = 'AzureConnectors.ItalyNorth'
metadata description = 'This module contains all the service tag IP addresses of AzureConnectors.ItalyNorth for Public.'
metadata author = ''
metadata author = ''

@description('AzureConnectors.ItalyNorth service tag IP addresses for Public')
@export()
var AzureConnectors_ItalyNorth = [
  '4.232.13.98/32'
  '4.232.13.123/32'
  '4.232.98.192/26'
  '2603:1020:1204:1::6c0/122'
]
