// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : AzureConnectors.AustriaEast

var AzureConnectors_AustriaEast = [
  '68.210.170.192/26'
  '2603:1020:104:5::640/122'
]
