// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureConnectors.SpainCentral
metadata name = 'AzureConnectors.SpainCentral'
metadata description = 'This module contains all the service tag IP addresses of AzureConnectors.SpainCentral for Public.'
metadata author = ''
metadata author = ''

@description('AzureConnectors.SpainCentral service tag IP addresses for Public')
@export()
var AzureConnectors_SpainCentral = [
  '68.221.92.64/26'
  '68.221.248.51/32'
  '68.221.248.79/32'
  '2603:1020:1403:2::80/122'
]
