// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : AzureConnectors.AustraliaSoutheast

var AzureConnectors_AustraliaSoutheast = [
  '4.199.85.0/26'
  '13.70.136.174/32'
  '13.77.45.34/32'
  '13.77.50.240/28'
  '13.77.55.160/27'
  '20.70.73.76/32'
  '20.92.3.64/27'
  '20.92.3.96/28'
  '20.92.47.23/32'
  '52.255.48.202/32'
  '2603:1010:101:402::180/122'
  '2603:1010:207::6c0/122'
]
