// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-21
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 396
// Service tag  : DataFactory.CentralUSEUAP

var DataFactory_CentralUSEUAP = [
  '20.45.208.16/28'
  '20.228.5.112/28'
  '20.228.7.0/25'
  '20.228.7.128/26'
  '40.122.0.16/28'
  '52.176.232.16/28'
  '168.61.229.72/29'
  '172.215.36.224/27'
  '2603:1030:f:1::440/122'
  '2603:1030:f:1::500/121'
  '2603:1030:f:400::b30/124'
  '2603:1030:f:800::40/126'
]
