// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_China.json
// Cloud        : China
// Change number: 393
// Service tag  : PowerPlatformInfra.ChinaEast3

var PowerPlatformInfra_ChinaEast3 = [
  '163.228.59.64/26'
  '163.228.59.128/27'
  '163.228.66.162/32'
  '2406:e500:5501:900::/58'
]
