// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_China.json
// Cloud        : China
// Service tag  : AzureKeyVault.ChinaEast2
metadata name = 'AzureKeyVault.ChinaEast2'
metadata description = 'This module contains all the service tag IP addresses of AzureKeyVault.ChinaEast2 for China.'
metadata author = ''
metadata author = ''

@description('AzureKeyVault.ChinaEast2 service tag IP addresses for China')
@export()
var AzureKeyVault_ChinaEast2 = [
  '40.73.72.185/32'
  '40.73.72.187/32'
  '52.130.120.164/30'
  '52.131.192.64/29'
  '52.131.192.72/30'
  '2404:7940:301:2::2b0/125'
  '2404:7940:301:2::2b8/126'
  '2404:7940:301:402::80/125'
]
