// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_AzureGermany.json
// Cloud        : AzureGermany
// Service tag  : AzureKeyVault

@export()
var AzureKeyVault = [
  '51.4.145.57/32'
  '51.4.145.82/32'
  '51.5.144.216/32'
  '51.5.144.237/32'
]
