// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AppServiceManagement.CanadaEast
metadata name = 'AppServiceManagement.CanadaEast'
metadata description = 'This module contains all the service tag IP addresses of AppServiceManagement.CanadaEast for Public.'
metadata author = ''
metadata author = ''

@description('AppServiceManagement.CanadaEast service tag IP addresses for Public')
@export()
var AppServiceManagement_CanadaEast = [
  '40.69.106.128/26'
  '40.86.229.100/32'
  '52.242.40.112/28'
  '2603:1030:1005:1::4a0/123'
  '2603:1030:1005:402::100/122'
]
