// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : AppServiceManagement.TaiwanNorthwest

var AppServiceManagement_TaiwanNorthwest = [
  '51.53.139.0/26'
  '167.105.228.0/29'
  '2603:1040:1202:2::6a0/123'
]
