// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AppServiceManagement.SwedenSouth
metadata name = 'AppServiceManagement.SwedenSouth'
metadata description = 'This module contains all the service tag IP addresses of AppServiceManagement.SwedenSouth for Public.'
metadata author = ''
metadata author = ''

@description('AppServiceManagement.SwedenSouth service tag IP addresses for Public')
@export()
var AppServiceManagement_SwedenSouth = [
  '51.12.20.192/27'
  '51.12.22.224/28'
  '51.12.203.0/26'
  '2603:1020:1104:2::200/123'
  '2603:1020:1104:400::100/122'
]
