// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AppServiceManagement.SouthCentralUS2

var AppServiceManagement_SouthCentralUS2 = [
  '48.216.28.192/26'
  '48.216.60.0/29'
  '2603:1030:1102:2::240/122'
]
