// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AppServiceManagement.WestUS3
metadata name = 'AppServiceManagement.WestUS3'
metadata description = 'This module contains all the service tag IP addresses of AppServiceManagement.WestUS3 for Public.'
metadata author = ''
metadata author = ''

@description('AppServiceManagement.WestUS3 service tag IP addresses for Public')
@export()
var AppServiceManagement_WestUS3 = [
  '20.150.130.208/28'
  '20.150.248.2/32'
  '20.150.251.21/32'
  '135.234.22.240/28'
  '172.182.1.64/29'
  '2603:1030:504:2::740/123'
  '2603:1030:504:402::400/122'
  '2603:1030:504:802::80/122'
  '2603:1030:504:802::380/122'
  '2603:1030:504:c02::440/122'
]
