// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AppServiceManagement.NorwayEast
metadata name = 'AppServiceManagement.NorwayEast'
metadata description = 'This module contains all the service tag IP addresses of AppServiceManagement.NorwayEast for Public.'
metadata author = ''
metadata author = ''

@description('AppServiceManagement.NorwayEast service tag IP addresses for Public')
@export()
var AppServiceManagement_NorwayEast = [
  '20.100.2.0/28'
  '51.120.79.170/32'
  '51.120.99.0/26'
  '131.163.6.64/29'
  '2603:1020:e04:3::4c0/123'
  '2603:1020:e04:402::100/122'
  '2603:1020:e04:802::100/122'
  '2603:1020:e04:c02::100/122'
]
