// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AppServiceManagement.NorwayWest
metadata name = 'AppServiceManagement.NorwayWest'
metadata description = 'This module contains all the service tag IP addresses of AppServiceManagement.NorwayWest for Public.'
metadata author = ''
metadata author = ''

@description('AppServiceManagement.NorwayWest service tag IP addresses for Public')
@export()
var AppServiceManagement_NorwayWest = [
  '4.220.129.64/29'
  '51.13.143.16/28'
  '51.120.164.77/32'
  '51.120.219.0/26'
  '2603:1020:f04:1::480/123'
  '2603:1020:f04:6::500/122'
  '2603:1020:f04:402::100/122'
]
