// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AppServiceManagement.MexicoCentral
metadata name = 'AppServiceManagement.MexicoCentral'
metadata description = 'This module contains all the service tag IP addresses of AppServiceManagement.MexicoCentral for Public.'
metadata author = ''
metadata author = ''

@description('AppServiceManagement.MexicoCentral service tag IP addresses for Public')
@export()
var AppServiceManagement_MexicoCentral = [
  '68.155.250.0/29'
  '158.23.114.64/26'
  '2603:1030:702:2::7c0/123'
]
