// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AppServiceManagement.MexicoCentral

@export()
var AppServiceManagement_MexicoCentral = [
  '68.155.250.0/29'
  '158.23.114.64/26'
  '2603:1030:702:2::7c0/123'
]
