// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-06-22
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 405
// Service tag  : ActionGroup.UAENorth

var ActionGroup_UAENorth = [
  '172.164.208.220/30'
  '2603:1040:904:1::114/126'
  '2603:1040:904:402::178/125'
]
