// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : ActionGroup.MalaysiaSouth

var ActionGroup_MalaysiaSouth = [
  '20.17.63.212/30'
  '20.17.66.88/30'
  '2603:1040:1503:1::1c4/126'
  '2603:1040:1503:400::180/125'
]
