// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : ActionGroup.UKWest
metadata name = 'ActionGroup.UKWest'
metadata description = 'This module contains all the service tag IP addresses of ActionGroup.UKWest for Public.'
metadata author = ''
metadata author = ''

@description('ActionGroup.UKWest service tag IP addresses for Public')
@export()
var ActionGroup_UKWest = [
  '20.90.38.38/31'
  '51.140.215.184/30'
  '172.187.32.16/30'
  '2603:1020:605::128/126'
  '2603:1020:605:402::178/125'
]
