// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : ActionGroup.CanadaEast
metadata name = 'ActionGroup.CanadaEast'
metadata description = 'This module contains all the service tag IP addresses of ActionGroup.CanadaEast for Public.'
metadata author = ''
metadata author = ''

@description('ActionGroup.CanadaEast service tag IP addresses for Public')
@export()
var ActionGroup_CanadaEast = [
  '4.248.83.192/30'
  '40.69.111.196/30'
  '2603:1030:1005::10c/126'
  '2603:1030:1005:402::178/125'
]
