// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : ActionGroup.CentralUSEUAP
metadata name = 'ActionGroup.CentralUSEUAP'
metadata description = 'This module contains all the service tag IP addresses of ActionGroup.CentralUSEUAP for Public.'
metadata author = ''
metadata author = ''

@description('ActionGroup.CentralUSEUAP service tag IP addresses for Public')
@export()
var ActionGroup_CentralUSEUAP = [
  '168.61.142.52/30'
  '168.61.239.12/30'
  '2603:1030:f:4::39c/126'
  '2603:1030:f:400::978/125'
]
