// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : ActionGroup.FranceCentral

var ActionGroup_FranceCentral = [
  '98.66.132.188/30'
  '2603:1020:805:1::130/126'
  '2603:1020:805:402::178/125'
]
