// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : ActionGroup.NewZealandNorth
metadata name = 'ActionGroup.NewZealandNorth'
metadata description = 'This module contains all the service tag IP addresses of ActionGroup.NewZealandNorth for Public.'
metadata author = ''
metadata author = ''

@description('ActionGroup.NewZealandNorth service tag IP addresses for Public')
@export()
var ActionGroup_NewZealandNorth = [
  '172.204.177.28/30'
  '2603:1010:502:400::80/125'
]
