// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : ActionGroup.KoreaCentral

var ActionGroup_KoreaCentral = [
  '4.218.236.160/30'
  '2603:1040:f05:1::10c/126'
  '2603:1040:f05:402::178/125'
]
