// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : ActionGroup.NorthCentralUS
metadata name = 'ActionGroup.NorthCentralUS'
metadata description = 'This module contains all the service tag IP addresses of ActionGroup.NorthCentralUS for Public.'
metadata author = ''
metadata author = ''

@description('ActionGroup.NorthCentralUS service tag IP addresses for Public')
@export()
var ActionGroup_NorthCentralUS = [
  '13.106.38.142/32'
  '13.106.38.148/32'
  '20.135.70.51/32'
  '52.240.244.140/30'
  '104.47.217.151/32'
  '104.47.240.167/32'
  '172.183.4.112/30'
  '2603:1030:608::130/126'
  '2603:1030:608:402::178/125'
]
