// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : ActionGroup.QatarCentral

var ActionGroup_QatarCentral = [
  '4.171.31.152/30'
  '20.21.42.88/30'
  '2603:1040:1002:5::30c/126'
  '2603:1040:1002:400::180/125'
]
