// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 407
// Service tag  : ActionGroup.UAECentral

var ActionGroup_UAECentral = [
  '20.203.88.62/31'
  '20.203.93.200/30'
  '74.243.155.0/29'
  '2603:1040:b04::10c/126'
  '2603:1040:b04:402::178/125'
]
