// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : ActionGroup.EastUS2

var ActionGroup_EastUS2 = [
  '20.7.239.202/32'
  '20.10.122.64/32'
  '20.44.17.220/30'
  '52.184.145.166/32'
  '74.249.127.180/30'
  '2603:1030:40c:1::118/126'
  '2603:1030:40c:402::178/125'
]
