// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : ActionGroup.BrazilSoutheast

@export()
var ActionGroup_BrazilSoutheast = [
  '108.140.5.168/30'
  '191.233.50.4/30'
  '2603:1050:403::10c/126'
  '2603:1050:403:400::1f8/125'
]
