// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : ActionGroup.AustraliaCentral
metadata name = 'ActionGroup.AustraliaCentral'
metadata description = 'This module contains all the service tag IP addresses of ActionGroup.AustraliaCentral for Public.'
metadata author = ''
metadata author = ''

@description('ActionGroup.AustraliaCentral service tag IP addresses for Public')
@export()
var ActionGroup_AustraliaCentral = [
  '20.53.1.68/30'
  '20.213.228.120/30'
  '2603:1010:304::10c/126'
  '2603:1010:304:402::178/125'
]
