// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : ActionGroup.SoutheastUS3
metadata name = 'ActionGroup.SoutheastUS3'
metadata description = 'This module contains all the service tag IP addresses of ActionGroup.SoutheastUS3 for Public.'
metadata author = ''
metadata author = ''

@description('ActionGroup.SoutheastUS3 service tag IP addresses for Public')
@export()
var ActionGroup_SoutheastUS3 = [
  '74.7.80.24/30'
  '2603:1030:1302:400::40/125'
]
