// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : ActionGroup.CentralIndia
metadata name = 'ActionGroup.CentralIndia'
metadata description = 'This module contains all the service tag IP addresses of ActionGroup.CentralIndia for Public.'
metadata author = ''
metadata author = ''

@description('ActionGroup.CentralIndia service tag IP addresses for Public')
@export()
var ActionGroup_CentralIndia = [
  '20.43.121.124/30'
  '20.204.192.216/31'
  '20.204.199.124/30'
  '2603:1040:a06:1::128/126'
  '2603:1040:a06:402::178/125'
]
