// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : ActionGroup.SwitzerlandWest
metadata name = 'ActionGroup.SwitzerlandWest'
metadata description = 'This module contains all the service tag IP addresses of ActionGroup.SwitzerlandWest for Public.'
metadata author = ''
metadata author = ''

@description('ActionGroup.SwitzerlandWest service tag IP addresses for Public')
@export()
var ActionGroup_SwitzerlandWest = [
  '20.199.201.66/31'
  '20.199.207.184/30'
  '51.107.193.28/30'
  '2603:1020:b04:2::5b4/126'
  '2603:1020:b04:402::178/125'
]
