// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : ActionGroup.SwedenCentral
metadata name = 'ActionGroup.SwedenCentral'
metadata description = 'This module contains all the service tag IP addresses of ActionGroup.SwedenCentral for Public.'
metadata author = ''
metadata author = ''

@description('ActionGroup.SwedenCentral service tag IP addresses for Public')
@export()
var ActionGroup_SwedenCentral = [
  '51.12.101.172/30'
  '172.160.216.24/30'
  '2603:1020:1004::130/126'
  '2603:1020:1004:800::f8/125'
]
