// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : ActionGroup.AustraliaSoutheast
metadata name = 'ActionGroup.AustraliaSoutheast'
metadata description = 'This module contains all the service tag IP addresses of ActionGroup.AustraliaSoutheast for Public.'
metadata author = ''
metadata author = ''

@description('ActionGroup.AustraliaSoutheast service tag IP addresses for Public')
@export()
var ActionGroup_AustraliaSoutheast = [
  '4.200.251.84/30'
  '13.77.53.216/30'
  '20.92.5.114/31'
  '2603:1010:101::10c/126'
  '2603:1010:101:402::178/125'
]
