// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : ActionGroup.CanadaCentral

var ActionGroup_CanadaCentral = [
  '4.206.229.96/30'
  '20.38.149.132/30'
  '20.116.43.108/31'
  '2603:1030:f05:1::120/126'
  '2603:1030:f05:402::178/125'
]
