// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : ActionGroup.SouthIndia

var ActionGroup_SouthIndia = [
  '52.172.33.114/32'
  '52.172.87.0/30'
  '104.211.231.103/32'
  '2603:1040:c06::10c/126'
  '2603:1040:c06:402::178/125'
]
