// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-21
// Source file  : ServiceTags_China.json
// Cloud        : China
// Change number: 391
// Service tag  : MicrosoftContainerRegistry.ChinaEast

var MicrosoftContainerRegistry_ChinaEast = [
  '139.217.168.96/29'
  '2404:7940:201:402::88/125'
]
