// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-21
// Source file  : ServiceTags_China.json
// Cloud        : China
// Change number: 391
// Service tag  : WindowsVirtualDesktop.ChinaNorth2

var WindowsVirtualDesktop_ChinaNorth2 = [
  '2406:e500:5510:2::/117'
]
