// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-07
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 399
// Service tag  : Dynamics365ForMarketingEmail.SoutheastAsia

var Dynamics365ForMarketingEmail_SoutheastAsia = [
  '57.155.153.0/27'
]
