// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-06-15
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 404
// Service tag  : Dynamics365ForMarketingEmail.EastUS

var Dynamics365ForMarketingEmail_EastUS = [
  '48.211.37.0/26'
]
