// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : Dynamics365ForMarketingEmail.UKSouth
metadata name = 'Dynamics365ForMarketingEmail.UKSouth'
metadata description = 'This module contains all the service tag IP addresses of Dynamics365ForMarketingEmail.UKSouth for Public.'
metadata author = ''
metadata author = ''

@description('Dynamics365ForMarketingEmail.UKSouth service tag IP addresses for Public')
@export()
var Dynamics365ForMarketingEmail_UKSouth = [
  '51.140.147.0/24'
]
