// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : Dynamics365ForMarketingEmail.GermanyWestCentral

var Dynamics365ForMarketingEmail_GermanyWestCentral = [
  '48.201.168.32/27'
]
