// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : Dynamics365ForMarketingEmail.KoreaCentral

var Dynamics365ForMarketingEmail_KoreaCentral = [
  '4.230.126.192/27'
]
