// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : Dynamics365ForMarketingEmail.UAENorth

var Dynamics365ForMarketingEmail_UAENorth = [
  '40.120.64.224/27'
  '65.52.252.128/27'
]
