// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_China.json
// Cloud        : China
// Change number: 393
// Service tag  : AzureCognitiveSearch.ChinaEast2

var AzureCognitiveSearch_ChinaEast2 = [
  '40.73.109.207/32'
  '40.162.169.224/28'
  '52.130.0.112/28'
  '2404:7940:301::180/121'
  '2404:7940:301:3::220/123'
]
