// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-10
// Source file  : ServiceTags_AzureGermany.json
// Cloud        : AzureGermany
// Service tag  : MicrosoftContainerRegistry.GermanyNorthEast

var MicrosoftContainerRegistry_GermanyNorthEast = [
  '51.8.226.48/29'
]
