// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : AzureMachineLearning.AustraliaSoutheast

var AzureMachineLearning_AustraliaSoutheast = [
  '4.199.83.64/27'
  '13.77.50.224/28'
  '20.42.227.48/28'
  '48.215.169.154/31'
  '48.215.173.24/30'
  '48.215.173.28/32'
  '48.215.173.80/28'
  '48.215.173.96/27'
  '2603:1010:101::300/122'
  '2603:1010:207:4::4d5/128'
  '2603:1010:207:4::540/123'
  '2603:1010:207:4::560/124'
  '2603:1010:207:4::570/126'
  '2603:1010:207:4::574/127'
]
