// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureMachineLearning.SouthCentralUS2
metadata name = 'AzureMachineLearning.SouthCentralUS2'
metadata description = 'This module contains all the service tag IP addresses of AzureMachineLearning.SouthCentralUS2 for Public.'
metadata author = ''
metadata author = ''

@description('AzureMachineLearning.SouthCentralUS2 service tag IP addresses for Public')
@export()
var AzureMachineLearning_SouthCentralUS2 = [
  '48.216.17.0/27'
  '2603:1030:1102::200/122'
]
