// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : AzureMachineLearning.SwedenSouth

var AzureMachineLearning_SwedenSouth = [
  '51.12.198.224/28'
  '51.12.203.80/28'
  '2603:1020:1104::240/122'
]
