// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : AzureMachineLearning.AustraliaCentral

var AzureMachineLearning_AustraliaCentral = [
  '20.36.106.80/28'
  '20.213.226.160/28'
  '2603:1010:304::300/122'
]
