// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureMachineLearning.AustraliaCentral2
metadata name = 'AzureMachineLearning.AustraliaCentral2'
metadata description = 'This module contains all the service tag IP addresses of AzureMachineLearning.AustraliaCentral2 for Public.'
metadata author = ''
metadata author = ''

@description('AzureMachineLearning.AustraliaCentral2 service tag IP addresses for Public')
@export()
var AzureMachineLearning_AustraliaCentral2 = [
  '20.36.114.160/28'
  '2603:1010:404::300/122'
]
