// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureMachineLearning.IsraelCentral
metadata name = 'AzureMachineLearning.IsraelCentral'
metadata description = 'This module contains all the service tag IP addresses of AzureMachineLearning.IsraelCentral for Public.'
metadata author = ''
metadata author = ''

@description('AzureMachineLearning.IsraelCentral service tag IP addresses for Public')
@export()
var AzureMachineLearning_IsraelCentral = [
  '20.217.41.0/27'
  '51.58.59.247/32'
  '51.58.60.142/31'
  '51.58.60.176/28'
  '51.58.62.0/27'
  '51.58.62.32/30'
  '2603:1040:1402::200/122'
  '2603:1040:1402:8::5e6/127'
  '2603:1040:1402:8::688/126'
  '2603:1040:1402:8::68c/128'
  '2603:1040:1402:8::690/124'
  '2603:1040:1402:8::6a0/123'
]
