// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureMachineLearning.ChileCentral

var AzureMachineLearning_ChileCentral = [
  '68.211.1.128/27'
  '2603:1050:301::200/122'
]
