// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-06-22
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 405
// Service tag  : AzureMachineLearning.SoutheastUS

var AzureMachineLearning_SoutheastUS = [
  '57.151.209.0/27'
  '2603:1030:902::200/122'
]
