// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : AzureMachineLearning.FranceSouth

var AzureMachineLearning_FranceSouth = [
  '40.79.178.224/28'
  '51.105.88.224/28'
  '2603:1020:905::300/122'
]
