// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureSecurityCenter.IsraelNorthwest
metadata name = 'AzureSecurityCenter.IsraelNorthwest'
metadata description = 'This module contains all the service tag IP addresses of AzureSecurityCenter.IsraelNorthwest for Public.'
metadata author = ''
metadata author = ''

@description('AzureSecurityCenter.IsraelNorthwest service tag IP addresses for Public')
@export()
var AzureSecurityCenter_IsraelNorthwest = [
  '51.4.227.176/28'
]
