// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureSecurityCenter.NewZealandNorth
metadata name = 'AzureSecurityCenter.NewZealandNorth'
metadata description = 'This module contains all the service tag IP addresses of AzureSecurityCenter.NewZealandNorth for Public.'
metadata author = ''
metadata author = ''

@description('AzureSecurityCenter.NewZealandNorth service tag IP addresses for Public')
@export()
var AzureSecurityCenter_NewZealandNorth = [
  '172.196.57.128/25'
  '172.196.58.0/24'
  '172.196.59.0/26'
  '172.196.59.64/27'
  '172.196.59.96/28'
  '172.204.255.248/30'
]
