// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureSecurityCenter.SouthAfricaWest

var AzureSecurityCenter_SouthAfricaWest = [
  '102.37.64.64/27'
  '172.209.42.96/27'
  '172.209.43.0/24'
  '172.209.44.0/22'
  '172.209.48.0/23'
  '172.209.50.0/26'
]
