// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureSecurityCenter.JapanEast

var AzureSecurityCenter_JapanEast = [
  '40.79.190.128/27'
  '74.176.228.64/26'
  '74.176.230.0/23'
  '130.33.120.0/22'
  '130.33.124.0/24'
  '130.33.125.0/27'
]
