// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureSecurityCenter.AustraliaCentral2

var AzureSecurityCenter_AustraliaCentral2 = [
  '20.36.117.224/27'
  '20.167.164.160/27'
  '20.167.164.192/26'
  '20.167.166.0/23'
  '20.167.168.0/22'
  '20.167.172.0/24'
]
