// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureSecurityCenter.JapanWest

var AzureSecurityCenter_JapanWest = [
  '40.80.180.128/27'
  '74.226.43.96/27'
  '74.226.44.0/22'
  '74.226.80.0/23'
  '74.226.82.0/24'
  '74.226.83.0/26'
]
