// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureSecurityCenter.FranceSouth

var AzureSecurityCenter_FranceSouth = [
  '20.111.82.0/23'
  '20.111.84.0/22'
  '20.111.88.0/24'
  '20.111.89.0/26'
  '20.111.89.64/27'
  '51.138.160.32/27'
]
