// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureSecurityCenter.AustriaEast

var AzureSecurityCenter_AustriaEast = [
  '68.210.30.216/30'
  '68.210.30.240/28'
  '68.210.56.160/27'
  '68.210.56.192/26'
  '68.210.57.0/24'
  '68.210.58.0/25'
]
