// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureSecurityCenter.SoutheastUS

@export()
var AzureSecurityCenter_SoutheastUS = [
  '68.154.163.144/28'
]
