// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-06-08
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 403
// Service tag  : AzureSecurityCenter.SoutheastUS3

var AzureSecurityCenter_SoutheastUS3 = [
  '74.7.71.16/28'
]
