// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureSecurityCenter.EastUS2EUAP

@export()
var AzureSecurityCenter_EastUS2EUAP = [
  '40.89.121.128/27'
]
