// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureSecurityCenter.EastUS

var AzureSecurityCenter_EastUS = [
  '48.211.7.0/25'
  '48.211.8.0/23'
  '52.168.112.96/27'
  '57.152.113.128/26'
  '57.152.114.0/24'
  '128.203.53.128/25'
  '128.203.55.0/24'
  '128.203.56.0/23'
  '128.203.58.0/27'
]
