// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureSecurityCenter.CanadaEast
metadata name = 'AzureSecurityCenter.CanadaEast'
metadata description = 'This module contains all the service tag IP addresses of AzureSecurityCenter.CanadaEast for Public.'
metadata author = ''
metadata author = ''

@description('AzureSecurityCenter.CanadaEast service tag IP addresses for Public')
@export()
var AzureSecurityCenter_CanadaEast = [
  '4.229.91.192/26'
  '4.229.92.128/27'
  '4.229.93.0/24'
  '4.229.94.0/23'
  '4.229.96.0/22'
  '40.69.111.64/27'
]
