// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-06-22
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 405
// Service tag  : AzureSecurityCenter.IsraelNorthwest

var AzureSecurityCenter_IsraelNorthwest = [
  '51.4.227.176/28'
]
