// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureSecurityCenter.WestIndia
metadata name = 'AzureSecurityCenter.WestIndia'
metadata description = 'This module contains all the service tag IP addresses of AzureSecurityCenter.WestIndia for Public.'
metadata author = ''
metadata author = ''

@description('AzureSecurityCenter.WestIndia service tag IP addresses for Public')
@export()
var AzureSecurityCenter_WestIndia = [
  '20.38.132.32/27'
  '57.159.130.224/27'
  '57.159.131.128/26'
  '57.159.132.0/22'
  '57.159.136.0/23'
  '57.159.138.0/24'
]
