// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : AppService.IsraelNorthwest

var AppService_IsraelNorthwest = [
  '51.4.130.0/24'
  '2603:1040:1702:1::600/120'
]
