// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-06-08
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 403
// Service tag  : AppService.TaiwanNorthwest

var AppService_TaiwanNorthwest = [
  '51.53.179.0/24'
  '2603:1040:1202:2::/120'
]
