// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AppService.BelgiumCentral

@export()
var AppService_BelgiumCentral = [
  '9.160.50.0/24'
  '2603:1020:1502:1::600/120'
]
