// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AppService.UAECentral
metadata name = 'AppService.UAECentral'
metadata description = 'This module contains all the service tag IP addresses of AppService.UAECentral for Public.'
metadata author = ''
metadata author = ''

@description('AppService.UAECentral service tag IP addresses for Public')
@export()
var AppService_UAECentral = [
  '20.37.66.0/27'
  '20.37.74.96/27'
  '20.45.94.192/26'
  '20.45.95.0/26'
  '2603:1040:b04:2::400/120'
  '2603:1040:b04:402::a0/123'
]
