// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AppService.AustraliaCentral2

var AppService_AustraliaCentral2 = [
  '20.36.72.230/32'
  '20.36.117.0/27'
  '20.36.122.0/27'
  '20.53.60.96/27'
  '20.53.61.0/25'
  '2603:1010:404:2::300/120'
  '2603:1010:404:402::a0/123'
]
