// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AppService.MexicoCentral

var AppService_MexicoCentral = [
  '158.23.105.0/24'
  '2603:1030:702:1::700/120'
]
