// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AppService.TaiwanNorth
metadata name = 'AppService.TaiwanNorth'
metadata description = 'This module contains all the service tag IP addresses of AppService.TaiwanNorth for Public.'
metadata author = ''
metadata author = ''

@description('AppService.TaiwanNorth service tag IP addresses for Public')
@export()
var AppService_TaiwanNorth = [
  '51.53.100.0/24'
  '2603:1040:1302:1::/120'
]
