// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AppService.NewZealandNorth

var AppService_NewZealandNorth = [
  '172.204.161.0/24'
  '2603:1010:502:1::700/120'
]
