// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_China.json
// Cloud        : China
// Change number: 392
// Service tag  : EOPExternalPublishedIPs

var EOPExternalPublishedIPs = [
  '40.72.120.0/22'
  '42.159.33.192/27'
  '42.159.36.0/24'
  '42.159.161.192/27'
  '42.159.164.0/24'
  '139.219.16.0/23'
  '139.219.24.0/22'
  '139.219.145.0/24'
  '139.219.146.0/24'
  '139.219.156.0/22'
  '159.27.176.0/21'
  '2406:e500:4400::/39'
]
