// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-10
// Source file  : ServiceTags_China.json
// Cloud        : China
// Service tag  : AzureSecurityCenter.ChinaNorth2

var AzureSecurityCenter_ChinaNorth2 = [
  '52.130.40.96/27'
]
