// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_China.json
// Cloud        : China
// Change number: 393
// Service tag  : AzureSecurityCenter.ChinaEast3

var AzureSecurityCenter_ChinaEast3 = [
  '163.228.101.0/24'
  '163.228.102.0/26'
]
