// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_China.json
// Cloud        : China
// Change number: 393
// Service tag  : AzureSecurityCenter.ChinaNorth

var AzureSecurityCenter_ChinaNorth = [
  '52.130.128.96/27'
]
