// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-21
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 396
// Service tag  : ApiManagement.UKSouth

var ApiManagement_UKSouth = [
  '20.90.131.114/31'
  '51.140.146.60/31'
  '51.140.149.0/28'
  '51.145.56.125/32'
  '131.145.110.138/31'
  '2603:1020:705:402::140/124'
]
