// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-21
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 396
// Service tag  : ApiManagement.SoutheastUS3

var ApiManagement_SoutheastUS3 = [
  '74.7.44.0/28'
  '2603:1030:1302::520/124'
]
