// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-21
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 396
// Service tag  : ApiManagement.IsraelCentral

var ApiManagement_IsraelCentral = [
  '20.217.43.224/28'
  '2603:1040:1402::600/124'
]
