// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_China.json
// Cloud        : China
// Change number: 393
// Service tag  : WindowsVirtualDesktop.ChinaNorth3

var WindowsVirtualDesktop_ChinaNorth3 = [
  '40.73.220.160/28'
  '2406:e500:5510:4::/117'
]
