// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_China.json
// Cloud        : China
// Service tag  : AzureContainerRegistry.ChinaEast3
metadata name = 'AzureContainerRegistry.ChinaEast3'
metadata description = 'This module contains all the service tag IP addresses of AzureContainerRegistry.ChinaEast3 for China.'
metadata author = ''
metadata author = ''

@description('AzureContainerRegistry.ChinaEast3 service tag IP addresses for China')
@export()
var AzureContainerRegistry_ChinaEast3 = [
  '52.131.148.0/26'
  '52.131.154.128/26'
  '52.131.157.0/25'
  '163.228.100.64/26'
  '2406:e500:2402::7c0/125'
  '2406:e500:2402:3::140/122'
  '2406:e500:2402:400::48/125'
  '2406:e500:2402:400::180/121'
]
