// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-21
// Source file  : ServiceTags_China.json
// Cloud        : China
// Change number: 391
// Service tag  : AzureArcInfrastructure.ChinaNorth2

var AzureArcInfrastructure_ChinaNorth2 = [
  '40.73.141.152/32'
  '52.130.16.148/30'
  '52.130.21.232/30'
  '52.130.40.164/30'
  '52.130.40.176/29'
  '52.131.89.0/29'
  '139.217.122.56/29'
  '143.64.207.182/32'
  '159.27.147.212/31'
  '159.27.147.216/29'
  '2404:7940:101:3::275/128'
]
