// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureSignalR.SwedenCentral

var AzureSignalR_SwedenCentral = [
  '51.12.46.192/27'
  '51.12.101.192/27'
  '135.225.177.32/27'
  '2603:1020:1004:2::600/120'
]
