// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureSignalR.BrazilSoutheast
metadata name = 'AzureSignalR.BrazilSoutheast'
metadata description = 'This module contains all the service tag IP addresses of AzureSignalR.BrazilSoutheast for Public.'
metadata author = ''
metadata author = ''

@description('AzureSignalR.BrazilSoutheast service tag IP addresses for Public')
@export()
var AzureSignalR_BrazilSoutheast = [
  '20.206.5.192/26'
  '2603:1050:403:2::100/120'
]
