// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : AzureSignalR.AustraliaCentral

var AzureSignalR_AustraliaCentral = [
  '4.199.172.64/26'
  '2603:1010:304:2::100/120'
]
