// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureSignalR.SwedenSouth

var AzureSignalR_SwedenSouth = [
  '51.12.17.160/27'
  '51.12.168.0/27'
  '74.241.0.192/27'
  '2603:1020:1104:2::/120'
]
