// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureSignalR.UAECentral
metadata name = 'AzureSignalR.UAECentral'
metadata description = 'This module contains all the service tag IP addresses of AzureSignalR.UAECentral for Public.'
metadata author = ''
metadata author = ''

@description('AzureSignalR.UAECentral service tag IP addresses for Public')
@export()
var AzureSignalR_UAECentral = [
  '2603:1040:b04:2::100/120'
]
