// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureSignalR.CentralUSEUAP

var AzureSignalR_CentralUSEUAP = [
  '20.46.11.96/27'
  '40.78.204.96/27'
  '172.215.76.128/27'
  '2603:1030:f:3::500/120'
]
