// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureSignalR.SouthAfricaNorth
metadata name = 'AzureSignalR.SouthAfricaNorth'
metadata description = 'This module contains all the service tag IP addresses of AzureSignalR.SouthAfricaNorth for Public.'
metadata author = ''
metadata author = ''

@description('AzureSignalR.SouthAfricaNorth service tag IP addresses for Public')
@export()
var AzureSignalR_SouthAfricaNorth = [
  '4.253.53.128/27'
  '102.37.160.32/27'
  '102.133.126.96/27'
  '2603:1000:104:2::600/120'
]
