// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureSignalR.SouthAfricaWest

var AzureSignalR_SouthAfricaWest = [
  '2603:1000:4:2::100/120'
]
