// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-10
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureSignalR.AustraliaSoutheast

var AzureSignalR_AustraliaSoutheast = [
  '20.211.225.0/26'
  '2603:1010:101:2::/120'
]
