// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureSignalR.SwitzerlandNorth
metadata name = 'AzureSignalR.SwitzerlandNorth'
metadata description = 'This module contains all the service tag IP addresses of AzureSignalR.SwitzerlandNorth for Public.'
metadata author = ''
metadata author = ''

@description('AzureSignalR.SwitzerlandNorth service tag IP addresses for Public')
@export()
var AzureSignalR_SwitzerlandNorth = [
  '51.107.128.128/27'
  '51.107.242.192/27'
  '74.242.255.192/27'
  '2603:1020:a04:2::300/120'
]
