// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureSignalR.WestIndia

@export()
var AzureSignalR_WestIndia = [
  '20.38.132.96/27'
  '52.136.53.224/27'
  '57.159.128.128/27'
  '2603:1040:806:2::100/120'
]
