// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureSignalR.EastUS2

var AzureSignalR_EastUS2 = [
  '20.62.59.32/27'
  '40.84.76.64/26'
  '2603:1030:40c:4::/120'
]
