// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureSignalR.CentralUSEUAP
metadata name = 'AzureSignalR.CentralUSEUAP'
metadata description = 'This module contains all the service tag IP addresses of AzureSignalR.CentralUSEUAP for Public.'
metadata author = ''
metadata author = ''

@description('AzureSignalR.CentralUSEUAP service tag IP addresses for Public')
@export()
var AzureSignalR_CentralUSEUAP = [
  '20.46.11.96/27'
  '40.78.204.96/27'
  '172.215.76.128/27'
  '2603:1030:f:3::500/120'
]
