// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureSignalR.KoreaCentral

var AzureSignalR_KoreaCentral = [
  '4.181.42.224/27'
  '4.181.53.0/27'
  '20.194.73.192/27'
  '52.231.20.96/27'
  '52.231.20.192/26'
  '2603:1040:f05:2::700/120'
]
