// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureSignalR.WestEurope

@export()
var AzureSignalR_WestEurope = [
  '20.61.102.64/27'
  '20.86.94.128/25'
  '2603:1020:206:4::200/120'
]
