// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_China.json
// Cloud        : China
// Service tag  : AppService.ChinaNorth3
metadata name = 'AppService.ChinaNorth3'
metadata description = 'This module contains all the service tag IP addresses of AppService.ChinaNorth3 for China.'
metadata author = ''
metadata author = ''

@description('AppService.ChinaNorth3 service tag IP addresses for China')
@export()
var AppService_ChinaNorth3 = [
  '159.27.20.0/24'
  '159.27.21.176/28'
  '159.27.22.0/23'
  '159.27.240.0/24'
  '2406:e500:2602:2::100/120'
  '2406:e500:2602:2::400/118'
]
