// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_AzureGovernment.json
// Cloud        : AzureGovernment
// Service tag  : ServiceFabric.USGovVirginia
metadata name = 'ServiceFabric.USGovVirginia'
metadata description = 'This module contains all the service tag IP addresses of ServiceFabric.USGovVirginia for AzureGovernment.'
metadata author = ''
metadata author = ''

@description('ServiceFabric.USGovVirginia service tag IP addresses for AzureGovernment')
@export()
var ServiceFabric_USGovVirginia = [
  '13.72.49.213/32'
  '20.140.94.128/30'
  '20.140.133.152/30'
  '52.127.42.152/29'
  '2001:489a:3103:402::98/125'
  '2001:489a:3103:802::98/125'
  '2001:489a:3103:c04::18/125'
]
