// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_AzureGovernment.json
// Cloud        : AzureGovernment
// Service tag  : ServiceFabric.USGovTexas

@export()
var ServiceFabric_USGovTexas = [
  '52.127.34.184/29'
  '52.238.116.45/32'
  '2001:489a:3403:402::98/125'
]
