// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_AzureGovernment.json
// Cloud        : AzureGovernment
// Service tag  : ServiceFabric.USGovArizona
metadata name = 'ServiceFabric.USGovArizona'
metadata description = 'This module contains all the service tag IP addresses of ServiceFabric.USGovArizona for AzureGovernment.'
metadata author = ''
metadata author = ''

@description('ServiceFabric.USGovArizona service tag IP addresses for AzureGovernment')
@export()
var ServiceFabric_USGovArizona = [
  '20.158.88.72/30'
  '20.158.89.64/30'
  '52.127.2.184/29'
  '52.127.23.64/30'
  '52.244.48.45/32'
  '2001:489a:3604:402::98/125'
  '2001:489a:3604:802::98/125'
  '2001:489a:3604:c02::18/125'
]
