// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_AzureGermany.json
// Cloud        : AzureGermany
// Change number: 193
// Service tag  : AzureBotService.GermanyCentral

var AzureBotService_GermanyCentral = [
  '51.18.32.64/30'
]
