// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_AzureGovernment.json
// Cloud        : AzureGovernment
// Change number: 390
// Service tag  : AzureCognitiveSearch.USDoDCentral

var AzureCognitiveSearch_USDoDCentral = [
  '20.140.72.96/28'
  '20.158.153.192/26'
  '2001:489a:3203::180/121'
]
