// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_AzureGovernment.json
// Cloud        : AzureGovernment
// Change number: 390
// Service tag  : AzureArcInfrastructure.USGovTexas

var AzureArcInfrastructure_USGovTexas = [
  '20.140.57.112/30'
  '20.140.60.116/30'
  '20.140.138.0/29'
  '52.127.34.194/31'
  '52.127.38.196/30'
  '52.243.243.40/29'
  '52.243.243.48/31'
  '2001:489a:3403:6::5d0/124'
]
