// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-21
// Source file  : ServiceTags_AzureGovernment.json
// Cloud        : AzureGovernment
// Change number: 390
// Service tag  : AzureSecurityCenter.USDoDCentral

var AzureSecurityCenter_USDoDCentral = [
  '20.159.238.0/23'
  '52.245.128.0/27'
]
