#!/usr/bin/env python3
"""
Convert an Azure Service Tags JSON file into per-tag Bicep variable files.

Each service tag is written to its own .bicep file inside *output_dir*,
keeping the number of variables per file at exactly one and avoiding the
Bicep compiler limit of 512 variables per file.

Usage:
    python convert-to-bicep.py <input.json> <output_dir>
"""

import json
import re
import sys
import os
from datetime import datetime, timezone


def to_bicep_identifier(name: str) -> str:
    """Return a valid Bicep identifier derived from *name*.

    Rules applied:
    - Replace every character that is not a letter, digit, or underscore with
      an underscore.
    - If the resulting string starts with a digit, prepend an underscore so
      that the identifier starts with a letter or underscore (Bicep requires
      identifiers to begin with a letter or underscore).
    """
    sanitized = re.sub(r"[^A-Za-z0-9_]", "_", name)
    if sanitized and sanitized[0].isdigit():
        sanitized = "_" + sanitized
    return sanitized or "_"


def to_module_name(name: str) -> str:
    """Convert a service tag name to a kebab-case registry module name.

    Examples:
        ActionGroup          -> action-group
        AzureActiveDirectory -> azure-active-directory
        Sql.EastUS           -> sql-east-us
    """
    # Replace non-alphanumeric characters with hyphens
    clean = re.sub(r"[^A-Za-z0-9]", "-", name)
    # Insert a hyphen between a lowercase/digit character and an uppercase character
    clean = re.sub(r"([a-z0-9])([A-Z])", r"\1-\2", clean)
    # Insert a hyphen between a run of uppercase characters and the last uppercase+lowercase pair
    clean = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1-\2", clean)
    # Lowercase, deduplicate hyphens, strip leading/trailing hyphens
    clean = clean.lower()
    clean = re.sub(r"-+", "-", clean).strip("-")
    return clean


def json_to_bicep(input_path: str, output_dir: str) -> None:
    with open(input_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    cloud = data.get("cloud", "Unknown")
    change_number = data.get("changeNumber", "Unknown")
    values = data.get("values", [])

    source_filename = os.path.basename(input_path)
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    os.makedirs(output_dir, exist_ok=True)

    for entry in values:
        name = entry.get("name", "")
        props = entry.get("properties", {})
        prefixes = props.get("addressPrefixes", [])

        safe_name = to_bicep_identifier(name)

        # Region-specific tags contain a dot (e.g. ActionGroup.WestEurope).
        # Write those into a subfolder named after the base tag in kebab-case.
        if "." in name:
            base_tag = name.split(".")[0]
            subfolder = to_module_name(base_tag)
            file_dir = os.path.join(output_dir, subfolder, "region")
        else:
            subfolder = to_module_name(name)
            file_dir = os.path.join(output_dir, subfolder)

        os.makedirs(file_dir, exist_ok=True)

        lines = [
            "// Auto-generated file – do not edit manually.",
            "// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep",
            f"// Generated at : {generated_at}",
            f"// Source file  : {source_filename}",
            f"// Cloud        : {cloud}",
            f"// Change number: {change_number}",
            f"// Service tag  : {name}",
            "",
            f"var {safe_name} = [",
        ]
        for prefix in prefixes:
            lines.append(f"  '{prefix}'")
        lines.append("]")
        lines.append("")

        output_path = os.path.join(file_dir, f"{safe_name}.bicep")
        with open(output_path, "w", encoding="utf-8", newline="\n") as f:
            f.write("\n".join(lines))

    print(f"Written {len(values)} service-tag files to {output_dir}/")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: convert-to-bicep.py <input.json> <output_dir>", file=sys.stderr)
        sys.exit(1)

    json_to_bicep(sys.argv[1], sys.argv[2])
