// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_AzureGermany.json
// Cloud        : AzureGermany
// Service tag  : AzureResourceManager
metadata name = 'AzureResourceManager'
metadata description = 'This module contains all the service tag IP addresses of AzureResourceManager for AzureGermany.'
metadata author = ''
metadata author = ''

@description('AzureResourceManager service tag IP addresses for AzureGermany')
@export()
var AzureResourceManager = [
  '51.8.227.176/28'
  '51.8.230.0/23'
  '51.8.235.224/28'
  '51.8.238.0/23'
]
