// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_China.json
// Cloud        : China
// Service tag  : PowerQueryOnline.ChinaEast
metadata name = 'PowerQueryOnline.ChinaEast'
metadata description = 'This module contains all the service tag IP addresses of PowerQueryOnline.ChinaEast for China.'
metadata author = ''
metadata author = ''

@description('PowerQueryOnline.ChinaEast service tag IP addresses for China')
@export()
var PowerQueryOnline_ChinaEast = [
  '139.219.248.40/29'
  '139.219.248.48/28'
  '2404:7940:201::200/123'
]
