// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_China.json
// Cloud        : China
// Service tag  : PowerQueryOnline.ChinaNorth2
metadata name = 'PowerQueryOnline.ChinaNorth2'
metadata description = 'This module contains all the service tag IP addresses of PowerQueryOnline.ChinaNorth2 for China.'
metadata author = ''
metadata author = ''

@description('PowerQueryOnline.ChinaNorth2 service tag IP addresses for China')
@export()
var PowerQueryOnline_ChinaNorth2 = [
  '52.130.16.132/30'
  '52.131.70.128/29'
  '143.64.193.112/28'
  '143.64.194.0/29'
  '2404:7940:101::200/123'
]
