// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_China.json
// Cloud        : China
// Change number: 393
// Service tag  : PowerQueryOnline.ChinaNorth

var PowerQueryOnline_ChinaNorth = [
  '2404:7940:1::200/123'
]
