// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_AzureGovernment.json
// Cloud        : AzureGovernment
// Service tag  : AzureResourceManager.USGovTexas
metadata name = 'AzureResourceManager.USGovTexas'
metadata description = 'This module contains all the service tag IP addresses of AzureResourceManager.USGovTexas for AzureGovernment.'
metadata author = ''
metadata author = ''

@description('AzureResourceManager.USGovTexas service tag IP addresses for AzureGovernment')
@export()
var AzureResourceManager_USGovTexas = [
  '20.140.62.0/23'
  '20.140.136.0/24'
  '52.127.35.192/28'
  '52.127.39.0/24'
  '2001:489a:3403::6c0/122'
  '2001:489a:3403:1::200/120'
  '2001:489a:3403:402::280/122'
]
