// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_AzureGovernment.json
// Cloud        : AzureGovernment
// Service tag  : AzureResourceManager.USGovArizona
metadata name = 'AzureResourceManager.USGovArizona'
metadata description = 'This module contains all the service tag IP addresses of AzureResourceManager.USGovArizona for AzureGovernment.'
metadata author = ''
metadata author = ''

@description('AzureResourceManager.USGovArizona service tag IP addresses for AzureGovernment')
@export()
var AzureResourceManager_USGovArizona = [
  '20.140.54.0/23'
  '52.127.3.208/28'
  '52.127.6.0/23'
  '2001:489a:3604:1::180/122'
  '2001:489a:3604:1::400/120'
  '2001:489a:3604:402::280/122'
]
