// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-18
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 400
// Service tag  : AzureAttestation.IndiaSouthCentral

var AzureAttestation_IndiaSouthCentral = [
  '172.198.80.20/30'
  '172.198.109.200/29'
  '172.198.110.16/30'
  '2603:1040:1904::760/124'
]
