// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureAttestation.BrazilSoutheast
metadata name = 'AzureAttestation.BrazilSoutheast'
metadata description = 'This module contains all the service tag IP addresses of AzureAttestation.BrazilSoutheast for Public.'
metadata author = ''
metadata author = ''

@description('AzureAttestation.BrazilSoutheast service tag IP addresses for Public')
@export()
var AzureAttestation_BrazilSoutheast = [
  '4.238.11.112/29'
  '4.238.27.136/30'
  '4.238.27.192/27'
  '20.195.146.64/30'
  '191.233.51.220/30'
]
