// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureAttestation.EastUS2

@export()
var AzureAttestation_EastUS2 = [
  '20.44.19.164/30'
  '20.49.103.124/30'
  '57.167.180.212/30'
  '57.167.180.216/29'
  '172.175.111.120/29'
  '2603:1030:40c:29::5e0/124'
]
