// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-09
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 407
// Service tag  : AzureAttestation.SouthCentralUS

var AzureAttestation_SouthCentralUS = [
  '13.85.231.72/29'
  '13.85.231.80/30'
  '20.45.126.116/30'
  '20.65.130.92/30'
  '48.192.143.112/29'
]
