// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureAttestation.SoutheastUS3

var AzureAttestation_SoutheastUS3 = [
  '74.7.40.20/30'
  '2603:1030:1302::540/124'
]
