// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-06-22
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 405
// Service tag  : AzureAttestation.AustraliaSoutheast

var AzureAttestation_AustraliaSoutheast = [
  '4.199.42.232/29'
  '20.11.225.140/30'
  '20.11.225.160/29'
  '104.46.162.16/30'
  '104.46.179.240/30'
  '2603:1010:207::3e0/124'
]
