// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureAttestation.NorwayEast
metadata name = 'AzureAttestation.NorwayEast'
metadata description = 'This module contains all the service tag IP addresses of AzureAttestation.NorwayEast for Public.'
metadata author = ''
metadata author = ''

@description('AzureAttestation.NorwayEast service tag IP addresses for Public')
@export()
var AzureAttestation_NorwayEast = [
  '4.177.29.184/29'
  '4.219.29.176/29'
  '4.219.29.184/30'
  '51.120.100.244/30'
  '51.120.233.128/30'
  '2603:1020:e04::7a0/123'
]
