// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : AzureAttestation.SpainCentral

var AzureAttestation_SpainCentral = [
  '68.221.84.152/30'
  '70.156.172.240/29'
  '2603:1020:1403::5e0/124'
]
