// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureAttestation.EastUSSTG

var AzureAttestation_EastUSSTG = [
  '20.49.83.244/30'
  '40.67.52.116/30'
  '2603:1030:104::7a0/124'
]
