// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : AzureAttestation.CentralUSEUAP

var AzureAttestation_CentralUSEUAP = [
  '20.46.11.4/30'
  '168.61.140.108/30'
  '172.215.123.104/29'
  '2603:1030:f:2::4c0/123'
]
