// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : AzureAttestation.EastAsia

var AzureAttestation_EastAsia = [
  '4.144.15.72/29'
  '20.187.197.228/30'
  '104.214.164.108/30'
  '2603:1040:207:1::4c0/124'
]
