// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-06-15
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 404
// Service tag  : AzureAttestation.SouthCentralUSSTG

var AzureAttestation_SouthCentralUSSTG = [
  '20.44.4.248/30'
  '20.45.116.92/30'
  '57.152.147.56/29'
  '57.152.147.192/30'
]
