// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-25
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 400
// Service tag  : AzureAttestation.BelgiumCentral

var AzureAttestation_BelgiumCentral = [
  '9.160.40.20/30'
  '9.160.193.248/29'
  '9.160.195.128/30'
  '2603:1020:1502::540/124'
]
