// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureAttestation.MalaysiaSouth

var AzureAttestation_MalaysiaSouth = [
  '20.17.51.36/30'
  '85.211.94.232/29'
  '2603:1040:1503::620/124'
]
