// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureAttestation.NorthEurope
metadata name = 'AzureAttestation.NorthEurope'
metadata description = 'This module contains all the service tag IP addresses of AzureAttestation.NorthEurope for Public.'
metadata author = ''
metadata author = ''

@description('AzureAttestation.NorthEurope service tag IP addresses for Public')
@export()
var AzureAttestation_NorthEurope = [
  '4.209.98.40/29'
  '4.209.98.48/30'
  '4.209.250.176/29'
  '13.69.233.128/30'
  '52.146.132.244/30'
]
