// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : AzureAttestation.IsraelCentral

var AzureAttestation_IsraelCentral = [
  '20.217.40.44/30'
  '51.58.49.24/29'
  '2603:1040:1402::620/124'
]
