// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-06-22
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 405
// Service tag  : AzureAttestation.GermanyWestCentral

var AzureAttestation_GermanyWestCentral = [
  '4.185.224.248/29'
  '48.203.101.80/29'
  '48.203.101.88/30'
  '51.116.149.224/30'
  '51.116.246.16/30'
]
