// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureAttestation.JioIndiaCentral

var AzureAttestation_JioIndiaCentral = [
  '20.192.231.240/30'
  '20.192.238.188/30'
  '74.225.110.136/29'
  '2603:1040:1104:1::420/123'
  '2603:1040:1104:400::420/123'
]
