// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : AzureAttestation.SoutheastAsia

var AzureAttestation_SoutheastAsia = [
  '4.145.10.168/29'
  '23.98.109.52/30'
  '40.78.239.116/30'
]
