// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : AzureAttestation.TaiwanNorthwest

var AzureAttestation_TaiwanNorthwest = [
  '51.53.171.240/30'
  '167.105.220.112/29'
  '2603:1040:1202::600/124'
]
