// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_AzureGovernment.json
// Cloud        : AzureGovernment
// Change number: 390
// Service tag  : AppService.USGovIowa

var AppService_USGovIowa = [
  '20.140.152.224/27'
  '23.97.28.154/32'
  '52.127.27.192/27'
]
