// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-21
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 396
// Service tag  : AzurePortal.MexicoCentral

var AzurePortal_MexicoCentral = [
  '158.23.112.0/27'
  '2603:1030:702:2::300/121'
]
