// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-21
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 396
// Service tag  : AzurePortal.AustraliaCentral

var AzurePortal_AustraliaCentral = [
  '20.37.225.128/27'
  '20.37.226.56/30'
  '20.37.229.152/29'
  '2603:1010:304::700/121'
]
