// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : AzureDevOps.CanadaEast

var AzureDevOps_CanadaEast = [
  '20.200.34.0/26'
  '2603:1030:1005:c::2d8/125'
]
