// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureDevOps.CanadaCentral
metadata name = 'AzureDevOps.CanadaCentral'
metadata description = 'This module contains all the service tag IP addresses of AzureDevOps.CanadaCentral for Public.'
metadata author = ''
metadata author = ''

@description('AzureDevOps.CanadaCentral service tag IP addresses for Public')
@export()
var AzureDevOps_CanadaCentral = [
  '4.206.254.104/31'
  '4.206.254.112/28'
  '4.206.254.192/27'
  '52.228.82.0/24'
  '2603:1030:f05:b::700/120'
  '2603:1030:f05:1000::2/128'
]
