// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-06-22
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 405
// Service tag  : AzureDevOps.SoutheastAsia

var AzureDevOps_SoutheastAsia = [
  '4.145.0.106/31'
  '4.145.0.192/27'
  '20.195.68.0/24'
  '2603:1040:5:15::100/120'
  '2603:1040:5:1000::2/128'
]
