// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-06-22
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 405
// Service tag  : AzureDevOps.CentralUS

var AzureDevOps_CentralUS = [
  '20.37.158.0/23'
  '57.175.72.64/26'
  '57.175.72.128/27'
  '172.169.145.104/30'
  '2603:1030:10:1c::600/119'
  '2603:1030:10:1000::2/128'
]
