// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureDevOps.SoutheastAsia
metadata name = 'AzureDevOps.SoutheastAsia'
metadata description = 'This module contains all the service tag IP addresses of AzureDevOps.SoutheastAsia for Public.'
metadata author = ''
metadata author = ''

@description('AzureDevOps.SoutheastAsia service tag IP addresses for Public')
@export()
var AzureDevOps_SoutheastAsia = [
  '4.145.0.106/31'
  '4.145.0.192/27'
  '20.195.68.0/24'
  '2603:1040:5:15::100/120'
  '2603:1040:5:1000::2/128'
]
