// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureDevOps.UKSouth

var AzureDevOps_UKSouth = [
  '51.104.26.0/24'
  '2603:1020:705:13::600/120'
]
