// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureDevOps.WestUS2

var AzureDevOps_WestUS2 = [
  '20.42.134.0/23'
  '2603:1030:c06:1f::400/119'
]
