// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : AzureDevOps.WestUS

var AzureDevOps_WestUS = [
  '40.82.252.0/24'
  '2603:1030:a07:15::3d2/127'
  '2603:1030:a07:15::3d8/125'
  '2603:1030:a07:1e::26e/127'
  '2603:1030:a07:1f::340/122'
  '2603:1030:a07:1f::380/121'
  '2603:1030:a07:1f::400/123'
  '2603:1030:a07:1f::420/124'
  '2603:1030:a07:1f::430/126'
]
