// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureDevOps.WestCentralUS

var AzureDevOps_WestCentralUS = [
  '52.150.138.0/24'
  '2603:1030:b04:d::200/120'
]
