// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-06-22
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 405
// Service tag  : AzureDevOps.NorthCentralUS

var AzureDevOps_NorthCentralUS = [
  '40.80.187.0/24'
  '130.213.112.120/30'
  '2603:1030:608:12::600/120'
  '2603:1030:608:1000::a/128'
]
