// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_China.json
// Cloud        : China
// Change number: 393
// Service tag  : PowerBI.ChinaNorth2

var PowerBI_ChinaNorth2 = [
  '52.130.16.68/30'
  '52.130.16.120/29'
  '52.130.16.128/31'
  '52.130.20.248/29'
  '139.217.121.0/29'
  '143.64.204.20/30'
  '143.64.204.44/30'
  '143.64.204.48/29'
  '2404:7940:101::6a0/123'
  '2404:7940:101::6c0/122'
]
