// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_AzureGermany.json
// Cloud        : AzureGermany
// Service tag  : Sql.GermanyNorthEast
metadata name = 'Sql.GermanyNorthEast'
metadata description = 'This module contains all the service tag IP addresses of Sql.GermanyNorthEast for AzureGermany.'
metadata author = ''
metadata author = ''

@description('Sql.GermanyNorthEast service tag IP addresses for AzureGermany')
@export()
var Sql_GermanyNorthEast = [
  '51.5.144.179/32'
  '51.5.144.185/32'
  '51.5.240.174/32'
  '51.5.246.239/32'
  '51.8.224.0/27'
  '51.8.225.0/27'
]
