// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_AzureGermany.json
// Cloud        : AzureGermany
// Service tag  : AppConfiguration
metadata name = 'AppConfiguration'
metadata description = 'This module contains all the service tag IP addresses of AppConfiguration for AzureGermany.'
metadata author = ''
metadata author = ''

@description('AppConfiguration service tag IP addresses for AzureGermany')
@export()
var AppConfiguration = [
  '51.8.227.232/29'
  '51.8.227.240/29'
  '51.8.236.8/29'
  '51.8.236.24/29'
  '51.8.236.64/28'
  '51.8.242.64/29'
  '51.8.242.88/29'
  '51.8.242.128/28'
  '51.8.250.96/29'
  '51.8.250.120/29'
  '51.8.250.128/28'
]
