// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureBackup.CanadaEast

var AzureBackup_CanadaEast = [
  '40.69.107.32/27'
  '40.69.107.64/26'
  '52.139.107.128/26'
  '2603:1030:1005:3::280/121'
  '2603:1030:1005:402::200/121'
]
