// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureBackup.IsraelNorthwest

var AzureBackup_IsraelNorthwest = [
  '20.217.252.0/26'
  '2603:1040:1702::600/121'
]
