// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureBackup.FranceSouth

var AzureBackup_FranceSouth = [
  '40.79.179.32/27'
  '40.79.179.64/26'
  '52.136.185.192/26'
  '2603:1020:905:5::/121'
  '2603:1020:905:402::200/121'
]
