// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureBackup.EastUS3
metadata name = 'AzureBackup.EastUS3'
metadata description = 'This module contains all the service tag IP addresses of AzureBackup.EastUS3 for Public.'
metadata author = ''
metadata author = ''

@description('AzureBackup.EastUS3 service tag IP addresses for Public')
@export()
var AzureBackup_EastUS3 = [
  '134.138.70.80/28'
  '134.138.70.128/26'
  '2603:1030:1402:1::/121'
]
