// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureBackup.CanadaEast
metadata name = 'AzureBackup.CanadaEast'
metadata description = 'This module contains all the service tag IP addresses of AzureBackup.CanadaEast for Public.'
metadata author = ''
metadata author = ''

@description('AzureBackup.CanadaEast service tag IP addresses for Public')
@export()
var AzureBackup_CanadaEast = [
  '40.69.107.32/27'
  '40.69.107.64/26'
  '52.139.107.128/26'
  '2603:1030:1005:3::280/121'
  '2603:1030:1005:402::200/121'
]
