// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureBackup.AustraliaCentral2

var AzureBackup_AustraliaCentral2 = [
  '20.36.114.224/27'
  '20.36.115.0/26'
  '20.53.56.192/26'
  '2603:1010:404:5::/121'
  '2603:1010:404:402::200/121'
]
