// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureBackup.CentralIndia

var AzureBackup_CentralIndia = [
  '20.192.44.128/26'
  '20.192.99.80/28'
  '20.192.99.128/26'
  '40.80.51.0/27'
  '40.80.53.192/26'
  '104.211.82.0/26'
  '104.211.82.64/27'
  '2603:1040:a06:2::300/121'
  '2603:1040:a06:402::200/121'
  '2603:1040:a06:802::180/121'
  '2603:1040:a06:c02::180/121'
]
