// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureBackup.WestUS
metadata name = 'AzureBackup.WestUS'
metadata description = 'This module contains all the service tag IP addresses of AzureBackup.WestUS for Public.'
metadata author = ''
metadata author = ''

@description('AzureBackup.WestUS service tag IP addresses for Public')
@export()
var AzureBackup_WestUS = [
  '13.86.218.0/25'
  '13.86.218.128/26'
  '20.66.4.0/25'
  '20.66.4.128/26'
  '20.168.163.0/26'
  '2603:1030:a07:4::300/121'
  '2603:1030:a07:402::180/121'
  '2603:1030:a07:c00::100/121'
]
