// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : AzureBackup.SouthCentralUS2

var AzureBackup_SouthCentralUS2 = [
  '48.216.20.0/26'
  '2603:1030:1102::600/121'
]
