// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : AzureBackup.SoutheastUS3

var AzureBackup_SoutheastUS3 = [
  '74.7.44.16/28'
  '74.7.44.64/26'
  '2603:1030:1302::600/121'
]
