// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureBackup.UKWest
metadata name = 'AzureBackup.UKWest'
metadata description = 'This module contains all the service tag IP addresses of AzureBackup.UKWest for Public.'
metadata author = ''
metadata author = ''

@description('AzureBackup.UKWest service tag IP addresses for Public')
@export()
var AzureBackup_UKWest = [
  '20.58.67.128/25'
  '51.140.211.32/27'
  '51.140.211.64/26'
  '2603:1020:605:3::480/121'
  '2603:1020:605:402::200/121'
]
