// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-18
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 400
// Service tag  : AzureBackup.IndiaSouthCentral

var AzureBackup_IndiaSouthCentral = [
  '172.198.86.80/28'
  '172.198.86.128/26'
  '2603:1040:1904:1::/121'
]
