// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureBackup.KoreaSouth
metadata name = 'AzureBackup.KoreaSouth'
metadata description = 'This module contains all the service tag IP addresses of AzureBackup.KoreaSouth for Public.'
metadata author = ''
metadata author = ''

@description('AzureBackup.KoreaSouth service tag IP addresses for Public')
@export()
var AzureBackup_KoreaSouth = [
  '52.147.113.0/26'
  '52.231.147.32/27'
  '52.231.147.64/26'
  '2603:1040:e05:5::300/121'
]
