// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_AzureGovernment.json
// Cloud        : AzureGovernment
// Service tag  : AzureMonitorForSAP
metadata name = 'AzureMonitorForSAP'
metadata description = 'This module contains all the service tag IP addresses of AzureMonitorForSAP for AzureGovernment.'
metadata author = ''
metadata author = ''

@description('AzureMonitorForSAP service tag IP addresses for AzureGovernment')
@export()
var AzureMonitorForSAP = [
  '51.54.119.240/31'
  '62.11.179.222/31'
  '2001:489a:3103:7::60a/127'
  '2001:489a:3604:8::8/127'
]
