// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_AzureGermany.json
// Cloud        : AzureGermany
// Service tag  : AppService.GermanyCentral
metadata name = 'AppService.GermanyCentral'
metadata description = 'This module contains all the service tag IP addresses of AppService.GermanyCentral for AzureGermany.'
metadata author = ''
metadata author = ''

@description('AppService.GermanyCentral service tag IP addresses for AzureGermany')
@export()
var AppService_GermanyCentral = [
  '51.8.234.96/27'
]
