// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : SCCservice.UAENorth

var SCCservice_UAENorth = [
  '40.120.64.104/29'
  '74.243.224.0/27'
  '2603:1040:904:6::200/123'
]
