// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : SCCservice.NorthEurope

var SCCservice_NorthEurope = [
  '13.69.233.48/29'
  '74.178.86.160/27'
  '2603:1020:5:12::640/123'
]
