// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : SCCservice.CanadaCentral

var SCCservice_CanadaCentral = [
  '4.248.139.192/27'
  '13.71.175.192/29'
  '2603:1030:f05:8::380/123'
]
