// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : SCCservice.JapanWest

@export()
var SCCservice_JapanWest = [
  '40.80.180.112/29'
]
