// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : SCCservice.EastUS

var SCCservice_EastUS = [
  '52.168.116.0/26'
  '72.152.254.0/24'
  '2603:1030:210:18::400/120'
]
