// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : SCCservice.SouthCentralUS

@export()
var SCCservice_SouthCentralUS = [
  '13.73.244.200/29'
  '135.233.156.96/27'
  '2603:1030:807:e::5a0/123'
]
