// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : SCCservice.CanadaEast

var SCCservice_CanadaEast = [
  '4.229.81.128/27'
  '40.69.111.96/29'
  '2603:1030:1005:8::420/123'
]
