// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-06-01
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 402
// Service tag  : SCCservice.JioIndiaCentral

var SCCservice_JioIndiaCentral = [
  '20.192.238.176/29'
]
