// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-09
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 407
// Service tag  : SCCservice.SwitzerlandWest

var SCCservice_SwitzerlandWest = [
  '51.107.192.136/29'
]
