// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 407
// Service tag  : SCCservice.GermanyNorth

var SCCservice_GermanyNorth = [
  '51.116.60.248/29'
]
