// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : SCCservice.SwedenSouth

var SCCservice_SwedenSouth = [
  '51.12.204.232/29'
]
