// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : SCCservice.UAECentral
metadata name = 'SCCservice.UAECentral'
metadata description = 'This module contains all the service tag IP addresses of SCCservice.UAECentral for Public.'
metadata author = ''
metadata author = ''

@description('SCCservice.UAECentral service tag IP addresses for Public')
@export()
var SCCservice_UAECentral = [
  '40.120.8.160/29'
  '74.243.65.64/27'
  '2603:1040:b04:6::600/123'
]
