// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : SCCservice.SoutheastAsia

var SCCservice_SoutheastAsia = [
  '40.78.239.104/29'
  '172.188.180.160/27'
  '2603:1040:5:d::80/123'
]
