// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : SCCservice.SwedenCentral

var SCCservice_SwedenCentral = [
  '51.12.101.160/29'
]
