// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureDataExplorerManagement.TaiwanNorthwest
metadata name = 'AzureDataExplorerManagement.TaiwanNorthwest'
metadata description = 'This module contains all the service tag IP addresses of AzureDataExplorerManagement.TaiwanNorthwest for Public.'
metadata author = ''
metadata author = ''

@description('AzureDataExplorerManagement.TaiwanNorthwest service tag IP addresses for Public')
@export()
var AzureDataExplorerManagement_TaiwanNorthwest = [
  '51.53.174.128/28'
  '2603:1040:1202:1::1c0/123'
]
