// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureDataExplorerManagement.ChileCentral
metadata name = 'AzureDataExplorerManagement.ChileCentral'
metadata description = 'This module contains all the service tag IP addresses of AzureDataExplorerManagement.ChileCentral for Public.'
metadata author = ''
metadata author = ''

@description('AzureDataExplorerManagement.ChileCentral service tag IP addresses for Public')
@export()
var AzureDataExplorerManagement_ChileCentral = [
  '68.211.7.0/28'
  '2603:1050:301:1::1c0/123'
]
