// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureDataExplorerManagement.BrazilSoutheast

var AzureDataExplorerManagement_BrazilSoutheast = [
  '108.140.7.144/28'
  '191.233.50.208/28'
  '2603:1050:403:1::400/121'
  '2603:1050:403:400::2b0/124'
]
