// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : AzureDataExplorerManagement.ItalyNorth

var AzureDataExplorerManagement_ItalyNorth = [
  '4.232.30.160/28'
  '2603:1020:1204:1::220/123'
]
