// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureDataExplorerManagement.NortheastUS5
metadata name = 'AzureDataExplorerManagement.NortheastUS5'
metadata description = 'This module contains all the service tag IP addresses of AzureDataExplorerManagement.NortheastUS5 for Public.'
metadata author = ''
metadata author = ''

@description('AzureDataExplorerManagement.NortheastUS5 service tag IP addresses for Public')
@export()
var AzureDataExplorerManagement_NortheastUS5 = [
  '172.194.73.128/28'
  '2603:1030:1602:1::400/123'
]
