// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureDataExplorerManagement.UAECentral

var AzureDataExplorerManagement_UAECentral = [
  '20.203.91.112/28'
  '2603:1040:b04:1::380/121'
  '2603:1040:b04:402::150/124'
]
