// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureDataExplorerManagement.AustriaEast

var AzureDataExplorerManagement_AustriaEast = [
  '68.210.166.128/28'
  '2603:1020:104:5::20/123'
]
