// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureDataExplorerManagement.UAENorth

var AzureDataExplorerManagement_UAENorth = [
  '20.46.146.7/32'
  '20.74.195.16/28'
  '2603:1040:904::600/121'
  '2603:1040:904:402::150/124'
]
