// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 407
// Service tag  : AzureDataExplorerManagement.TaiwanNorthwest

var AzureDataExplorerManagement_TaiwanNorthwest = [
  '51.53.174.128/28'
  '2603:1040:1202:1::1c0/123'
]
