// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureDataExplorerManagement.SoutheastUS3
metadata name = 'AzureDataExplorerManagement.SoutheastUS3'
metadata description = 'This module contains all the service tag IP addresses of AzureDataExplorerManagement.SoutheastUS3 for Public.'
metadata author = ''
metadata author = ''

@description('AzureDataExplorerManagement.SoutheastUS3 service tag IP addresses for Public')
@export()
var AzureDataExplorerManagement_SoutheastUS3 = [
  '74.7.47.16/28'
  '2603:1030:1302:1::1e0/123'
]
