// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureDataExplorerManagement.MalaysiaWest

@export()
var AzureDataExplorerManagement_MalaysiaWest = [
  '20.17.118.208/28'
  '2603:1040:1602:1::240/123'
]
