// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureDataExplorerManagement.IndonesiaCentral

var AzureDataExplorerManagement_IndonesiaCentral = [
  '70.153.158.208/28'
  '2603:1040:1802::760/123'
]
