// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureDataExplorerManagement.BrazilSoutheast
metadata name = 'AzureDataExplorerManagement.BrazilSoutheast'
metadata description = 'This module contains all the service tag IP addresses of AzureDataExplorerManagement.BrazilSoutheast for Public.'
metadata author = ''
metadata author = ''

@description('AzureDataExplorerManagement.BrazilSoutheast service tag IP addresses for Public')
@export()
var AzureDataExplorerManagement_BrazilSoutheast = [
  '108.140.7.144/28'
  '191.233.50.208/28'
  '2603:1050:403:1::400/121'
  '2603:1050:403:400::2b0/124'
]
