// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : AzureDataExplorerManagement.KoreaSouth

var AzureDataExplorerManagement_KoreaSouth = [
  '20.200.166.48/28'
  '40.80.234.9/32'
  '52.231.148.16/28'
  '2603:1040:e05::180/121'
]
