// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : AzureDataExplorerManagement.EastUS3

var AzureDataExplorerManagement_EastUS3 = [
  '134.138.73.80/28'
  '2603:1030:1402:1::400/123'
]
