// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureDataExplorerManagement.SouthAfricaNorth
metadata name = 'AzureDataExplorerManagement.SouthAfricaNorth'
metadata description = 'This module contains all the service tag IP addresses of AzureDataExplorerManagement.SouthAfricaNorth for Public.'
metadata author = ''
metadata author = ''

@description('AzureDataExplorerManagement.SouthAfricaNorth service tag IP addresses for Public')
@export()
var AzureDataExplorerManagement_SouthAfricaNorth = [
  '4.222.193.128/28'
  '102.133.130.206/32'
  '102.133.156.16/28'
  '2603:1000:104:2::100/121'
  '2603:1000:104:402::150/124'
]
