// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureDataExplorerManagement.NorwayEast

var AzureDataExplorerManagement_NorwayEast = [
  '51.120.99.80/28'
  '51.120.235.224/28'
  '2603:1020:e04::600/121'
  '2603:1020:e04:402::150/124'
]
