// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : AzureDataExplorerManagement.SouthCentralUS

var AzureDataExplorerManagement_SouthCentralUS = [
  '13.73.240.96/28'
  '20.45.3.60/32'
  '40.119.3.195/32'
  '172.215.131.64/28'
  '2603:1030:807::600/121'
  '2603:1030:807:402::150/124'
]
