// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureDataExplorerManagement.SwitzerlandNorth

var AzureDataExplorerManagement_SwitzerlandNorth = [
  '51.107.59.160/28'
  '51.107.247.128/28'
  '2603:1020:a04::600/121'
  '2603:1020:a04:402::150/124'
]
