// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureDataExplorerManagement.DenmarkEast
metadata name = 'AzureDataExplorerManagement.DenmarkEast'
metadata description = 'This module contains all the service tag IP addresses of AzureDataExplorerManagement.DenmarkEast for Public.'
metadata author = ''
metadata author = ''

@description('AzureDataExplorerManagement.DenmarkEast service tag IP addresses for Public')
@export()
var AzureDataExplorerManagement_DenmarkEast = [
  '9.205.38.192/28'
  '2603:1020:1602:1::1e0/123'
]
