// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureDataExplorerManagement.JapanWest
metadata name = 'AzureDataExplorerManagement.JapanWest'
metadata description = 'This module contains all the service tag IP addresses of AzureDataExplorerManagement.JapanWest for Public.'
metadata author = ''
metadata author = ''

@description('AzureDataExplorerManagement.JapanWest service tag IP addresses for Public')
@export()
var AzureDataExplorerManagement_JapanWest = [
  '20.210.144.96/28'
  '40.74.101.208/28'
  '40.81.184.86/32'
  '2603:1040:606:1::380/121'
  '2603:1040:606:402::150/124'
]
