// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : AzureDataExplorerManagement.DenmarkEast

var AzureDataExplorerManagement_DenmarkEast = [
  '9.205.38.192/28'
  '2603:1020:1602:1::1e0/123'
]
