// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_China.json
// Cloud        : China
// Change number: 392
// Service tag  : Scuba

var Scuba = [
  '159.27.248.184/30'
  '163.228.195.180/30'
]
