// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_AzureGermany.json
// Cloud        : AzureGermany
// Service tag  : AppServiceManagement.GermanyNorthEast
metadata name = 'AppServiceManagement.GermanyNorthEast'
metadata description = 'This module contains all the service tag IP addresses of AppServiceManagement.GermanyNorthEast for AzureGermany.'
metadata author = ''
metadata author = ''

@description('AppServiceManagement.GermanyNorthEast service tag IP addresses for AzureGermany')
@export()
var AppServiceManagement_GermanyNorthEast = [
  '51.8.226.64/26'
]
