// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-21
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 396
// Service tag  : AzureEventGrid.FranceCentral

var AzureEventGrid_FranceCentral = [
  '20.40.152.128/27'
  '20.43.42.128/25'
  '2603:1020:805:1::380/121'
]
