// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-21
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 396
// Service tag  : AzureEventGrid.NewZealandNorth

var AzureEventGrid_NewZealandNorth = [
  '172.204.153.128/25'
  '2603:1010:502::280/121'
]
