// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-21
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 396
// Service tag  : AzureEventGrid.SoutheastUS

var AzureEventGrid_SoutheastUS = [
  '57.151.209.128/25'
  '2603:1030:902::280/121'
]
