// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-21
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 396
// Service tag  : MicrosoftContainerRegistry.SwedenSouth

var MicrosoftContainerRegistry_SwedenSouth = [
  '51.12.202.16/29'
  '2603:1020:1104:400::88/125'
]
