// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_AzureGovernment.json
// Cloud        : AzureGovernment
// Service tag  : SCCservice.USGovArizona

@export()
var SCCservice_USGovArizona = [
  '20.158.112.16/28'
  '2001:489a:2209::/117'
]
