// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_AzureGovernment.json
// Cloud        : AzureGovernment
// Change number: 390
// Service tag  : SCCservice.USGovArizona

var SCCservice_USGovArizona = [
  '20.158.112.16/28'
  '2001:489a:2209::/117'
]
