// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-21
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 396
// Service tag  : AzureDevOps.NorthCentralUS

var AzureDevOps_NorthCentralUS = [
  '40.80.187.0/24'
  '2603:1030:608:12::600/120'
]
