// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-21
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 396
// Service tag  : AzureDevOps.SoutheastAsia

var AzureDevOps_SoutheastAsia = [
  '20.195.68.0/24'
  '2603:1040:5:15::100/120'
]
