// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_AzureGermany.json
// Cloud        : AzureGermany
// Change number: 193
// Service tag  : AzureSiteRecovery

var AzureSiteRecovery = [
  '51.4.225.99/32'
  '51.5.242.106/32'
  '51.18.32.80/28'
  '51.18.40.80/28'
]
