// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : ServiceBus.IsraelNorthwest

@export()
var ServiceBus_IsraelNorthwest = [
  '20.217.254.0/25'
  '51.4.160.16/29'
  '51.4.160.32/28'
  '2603:1040:1702::780/121'
]
