// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : ServiceBus.BelgiumCentral

var ServiceBus_BelgiumCentral = [
  '9.160.46.0/25'
  '9.160.80.16/29'
  '2603:1020:1502::780/121'
]
