// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : ServiceBus.SwitzerlandNorth
metadata name = 'ServiceBus.SwitzerlandNorth'
metadata description = 'This module contains all the service tag IP addresses of ServiceBus.SwitzerlandNorth for Public.'
metadata author = ''
metadata author = ''

@description('ServiceBus.SwitzerlandNorth service tag IP addresses for Public')
@export()
var ServiceBus_SwitzerlandNorth = [
  '20.208.18.80/29'
  '20.208.18.96/28'
  '51.103.202.80/29'
  '51.103.202.96/28'
  '51.107.58.8/29'
  '51.107.128.192/26'
  '51.107.244.128/25'
  '74.242.150.192/26'
  '2603:1020:a04::700/120'
  '2603:1020:a04:1::220/123'
  '2603:1020:a04:402::170/125'
  '2603:1020:a04:802::150/125'
  '2603:1020:a04:c02::150/125'
]
