// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : ServiceBus.TaiwanNorth

var ServiceBus_TaiwanNorth = [
  '51.53.30.0/25'
  '51.53.106.80/29'
  '51.53.106.96/28'
  '2603:1040:1302::780/121'
]
