// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : ServiceBus.AustriaEast
metadata name = 'ServiceBus.AustriaEast'
metadata description = 'This module contains all the service tag IP addresses of ServiceBus.AustriaEast for Public.'
metadata author = ''
metadata author = ''

@description('ServiceBus.AustriaEast service tag IP addresses for Public')
@export()
var ServiceBus_AustriaEast = [
  '68.210.152.16/29'
  '68.210.152.32/28'
  '68.210.166.0/25'
  '68.210.192.16/29'
  '68.210.192.32/28'
  '68.210.208.16/29'
  '68.210.208.32/28'
  '2603:1020:104:4::580/121'
]
