// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : ServiceBus.WestIndia
metadata name = 'ServiceBus.WestIndia'
metadata description = 'This module contains all the service tag IP addresses of ServiceBus.WestIndia for Public.'
metadata author = ''
metadata author = ''

@description('ServiceBus.WestIndia service tag IP addresses for Public')
@export()
var ServiceBus_WestIndia = [
  '4.187.93.128/26'
  '20.192.82.128/25'
  '104.211.146.16/28'
  '2603:1040:806::220/123'
  '2603:1040:806:1::500/120'
  '2603:1040:806:402::170/125'
]
