// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : ServiceBus.SpainCentral

var ServiceBus_SpainCentral = [
  '68.221.85.128/25'
  '68.221.98.80/29'
  '68.221.98.96/28'
  '68.221.146.80/29'
  '68.221.146.96/28'
  '68.221.154.80/29'
  '68.221.154.96/28'
  '2603:1020:1403:1::100/121'
]
