// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : ServiceBus.SouthAfricaWest
metadata name = 'ServiceBus.SouthAfricaWest'
metadata description = 'This module contains all the service tag IP addresses of ServiceBus.SouthAfricaWest for Public.'
metadata author = ''
metadata author = ''

@description('ServiceBus.SouthAfricaWest service tag IP addresses for Public')
@export()
var ServiceBus_SouthAfricaWest = [
  '102.37.64.192/26'
  '102.37.84.0/25'
  '102.133.26.8/29'
  '2603:1000:4::220/123'
  '2603:1000:4:1::500/120'
  '2603:1000:4:402::170/125'
]
