// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : ServiceBus.JioIndiaCentral
metadata name = 'ServiceBus.JioIndiaCentral'
metadata description = 'This module contains all the service tag IP addresses of ServiceBus.JioIndiaCentral for Public.'
metadata author = ''
metadata author = ''

@description('ServiceBus.JioIndiaCentral service tag IP addresses for Public')
@export()
var ServiceBus_JioIndiaCentral = [
  '20.192.32.240/28'
  '20.192.55.64/26'
  '20.192.55.128/26'
  '20.192.225.56/29'
  '20.192.234.8/29'
  '2603:1040:1104:1::700/120'
  '2603:1040:1104:400::170/125'
]
