// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-10
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : ServiceBus.IndiaSouthCentral

var ServiceBus_IndiaSouthCentral = [
  '172.198.89.0/25'
  '2603:1040:1904:1::180/121'
]
