// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_AzureGovernment.json
// Cloud        : AzureGovernment
// Service tag  : WindowsVirtualDesktop
metadata name = 'WindowsVirtualDesktop'
metadata description = 'This module contains all the service tag IP addresses of WindowsVirtualDesktop for AzureGovernment.'
metadata author = ''
metadata author = ''

@description('WindowsVirtualDesktop service tag IP addresses for AzureGovernment')
@export()
var WindowsVirtualDesktop = [
  '20.140.236.0/22'
  '20.159.80.0/24'
  '2001:489a:2104::/48'
  '2001:489a:2105::/48'
]
