// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 407
// Service tag  : EventHub.IndiaSouthCentral

var EventHub_IndiaSouthCentral = [
  '172.198.88.0/24'
  '2603:1040:1904:1::200/120'
]
