// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : EventHub.SpainCentral

var EventHub_SpainCentral = [
  '68.221.86.0/24'
  '68.221.99.64/26'
  '68.221.147.64/26'
  '68.221.154.192/26'
  '2603:1020:1403:1::/120'
]
