// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-06-22
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 405
// Service tag  : EventHub.SouthCentralUSSTG

var EventHub_SouthCentralUSSTG = [
  '20.44.2.128/26'
  '20.45.117.128/26'
  '2603:1030:302::200/120'
]
