// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : EventHub.SwitzerlandWest

var EventHub_SwitzerlandWest = [
  '51.107.154.128/27'
  '51.107.193.192/26'
  '51.107.253.0/24'
  '2603:1020:b04::240/122'
  '2603:1020:b04:2::/120'
  '2603:1020:b04:402::1c0/123'
]
