// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : EventHub.NorthEurope
metadata name = 'EventHub.NorthEurope'
metadata description = 'This module contains all the service tag IP addresses of EventHub.NorthEurope for Public.'
metadata author = ''
metadata author = ''

@description('EventHub.NorthEurope service tag IP addresses for Public')
@export()
var EventHub_NorthEurope = [
  '13.69.227.0/26'
  '13.69.239.0/26'
  '13.74.107.0/26'
  '20.50.72.64/26'
  '20.50.80.64/26'
  '20.82.245.0/24'
  '51.104.165.162/32'
  '52.138.226.0/26'
  '134.149.88.0/23'
  '2603:1020:5:1::240/122'
  '2603:1020:5:9::/119'
  '2603:1020:5:402::1c0/123'
  '2603:1020:5:802::160/123'
  '2603:1020:5:c02::160/123'
  '2603:10e1:100:2::3368:a5a2/128'
]
