// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : EventHub.ChileCentral

var EventHub_ChileCentral = [
  '68.211.6.0/24'
  '68.211.152.128/26'
  '68.211.168.128/26'
  '68.211.184.128/26'
  '2603:1050:301::700/120'
]
