// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : EventHub.NorwayEast
metadata name = 'EventHub.NorwayEast'
metadata description = 'This module contains all the service tag IP addresses of EventHub.NorwayEast for Public.'
metadata author = ''
metadata author = ''

@description('EventHub.NorwayEast service tag IP addresses for Public')
@export()
var EventHub_NorwayEast = [
  '4.177.24.0/24'
  '4.177.25.0/26'
  '20.100.0.0/26'
  '51.13.0.192/26'
  '51.120.98.128/27'
  '51.120.106.64/26'
  '51.120.210.64/26'
  '131.163.111.208/29'
  '131.163.111.216/30'
  '131.163.111.224/27'
  '2603:1020:e04:1::240/122'
  '2603:1020:e04:3::600/120'
  '2603:1020:e04:402::1c0/123'
  '2603:1020:e04:802::160/123'
  '2603:1020:e04:c02::160/123'
]
