// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : EventHub.MexicoCentral
metadata name = 'EventHub.MexicoCentral'
metadata description = 'This module contains all the service tag IP addresses of EventHub.MexicoCentral for Public.'
metadata author = ''
metadata author = ''

@description('EventHub.MexicoCentral service tag IP addresses for Public')
@export()
var EventHub_MexicoCentral = [
  '158.23.11.64/26'
  '158.23.102.0/24'
  '158.23.123.64/26'
  '158.23.195.64/26'
  '2603:1030:702:1::/120'
]
