// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : EventHub.AustraliaSoutheast

var EventHub_AustraliaSoutheast = [
  '13.77.50.32/27'
  '20.92.2.0/24'
  '2603:1010:101::240/122'
  '2603:1010:101:2::600/119'
  '2603:1010:101:402::1c0/123'
]
