// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : DataFactory.AustraliaCentral
metadata name = 'DataFactory.AustraliaCentral'
metadata description = 'This module contains all the service tag IP addresses of DataFactory.AustraliaCentral for Public.'
metadata author = ''
metadata author = ''

@description('DataFactory.AustraliaCentral service tag IP addresses for Public')
@export()
var DataFactory_AustraliaCentral = [
  '20.37.228.16/28'
  '20.37.228.192/26'
  '20.37.229.0/25'
  '20.53.0.48/28'
  '2603:1010:304::440/122'
  '2603:1010:304::500/121'
  '2603:1010:304:402::330/124'
]
