// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : DataFactory.WestUS
metadata name = 'DataFactory.WestUS'
metadata description = 'This module contains all the service tag IP addresses of DataFactory.WestUS for Public.'
metadata author = ''
metadata author = ''

@description('DataFactory.WestUS service tag IP addresses for Public')
@export()
var DataFactory_WestUS = [
  '13.86.219.208/28'
  '20.59.84.168/29'
  '20.168.163.208/28'
  '40.82.249.64/26'
  '40.82.250.0/23'
  '52.250.228.0/29'
  '57.154.147.160/27'
  '2603:1030:a07::440/122'
  '2603:1030:a07::500/121'
  '2603:1030:a07:402::9b0/124'
  '2603:1030:a07:c00::2c0/124'
]
