// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : DataFactory.WestIndia

var DataFactory_WestIndia = [
  '4.187.66.0/23'
  '20.38.133.192/28'
  '2603:1040:806::440/122'
  '2603:1040:806::500/121'
  '2603:1040:806:402::330/124'
]
