// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-06-01
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 402
// Service tag  : DataFactory.NortheastUS5

var DataFactory_NortheastUS5 = [
  '172.194.81.112/28'
  '172.194.82.32/27'
  '172.194.83.0/24'
  '2603:1030:1602:3::/120'
]
