// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : DataFactory.SouthCentralUS2

var DataFactory_SouthCentralUS2 = [
  '48.216.10.208/28'
  '48.216.30.0/23'
  '2603:1030:1102:2::300/121'
  '2603:1030:1102:400::150/124'
]
