// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : DataFactory.WestIndia
metadata name = 'DataFactory.WestIndia'
metadata description = 'This module contains all the service tag IP addresses of DataFactory.WestIndia for Public.'
metadata author = ''
metadata author = ''

@description('DataFactory.WestIndia service tag IP addresses for Public')
@export()
var DataFactory_WestIndia = [
  '4.187.66.0/23'
  '20.38.133.192/28'
  '2603:1040:806::440/122'
  '2603:1040:806::500/121'
  '2603:1040:806:402::330/124'
]
