// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : DataFactory.EastUS2EUAP
metadata name = 'DataFactory.EastUS2EUAP'
metadata description = 'This module contains all the service tag IP addresses of DataFactory.EastUS2EUAP for Public.'
metadata author = ''
metadata author = ''

@description('DataFactory.EastUS2EUAP service tag IP addresses for Public')
@export()
var DataFactory_EastUS2EUAP = [
  '20.39.8.96/27'
  '20.39.8.128/26'
  '20.39.15.0/29'
  '20.221.136.72/29'
  '40.74.149.64/28'
  '40.75.35.144/28'
  '52.138.92.128/28'
  '68.220.82.112/28'
  '72.147.54.32/28'
  '172.173.46.160/27'
  '2603:1030:40b:1::480/121'
  '2603:1030:40b:1::500/122'
  '2603:1030:40b:400::b30/124'
  '2603:1030:40b:800::210/124'
  '2603:1030:40b:c00::210/124'
  '2603:1030:40b:1000::e0/124'
]
