// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : DataFactory.EastUS3
metadata name = 'DataFactory.EastUS3'
metadata description = 'This module contains all the service tag IP addresses of DataFactory.EastUS3 for Public.'
metadata author = ''
metadata author = ''

@description('DataFactory.EastUS3 service tag IP addresses for Public')
@export()
var DataFactory_EastUS3 = [
  '51.57.137.192/28'
  '51.57.137.224/27'
  '134.138.80.0/23'
  '134.138.98.224/28'
  '2603:1030:1402:2::500/121'
  '2603:1030:1402:5::80/121'
  '2603:1030:1402:400::200/124'
]
