// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : DataFactory.ItalyNorth
metadata name = 'DataFactory.ItalyNorth'
metadata description = 'This module contains all the service tag IP addresses of DataFactory.ItalyNorth for Public.'
metadata author = ''
metadata author = ''

@description('DataFactory.ItalyNorth service tag IP addresses for Public')
@export()
var DataFactory_ItalyNorth = [
  '4.232.44.160/28'
  '4.232.44.192/26'
  '4.232.45.0/25'
  '4.232.102.0/23'
  '4.232.111.0/28'
  '4.232.123.208/28'
  '4.232.195.208/28'
  '172.213.201.32/27'
  '2603:1020:1204:2::100/121'
  '2603:1020:1204:4::5e0/124'
  '2603:1020:1204:400::380/124'
  '2603:1020:1204:800::280/124'
  '2603:1020:1204:c00::280/124'
]
