// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : PowerBI.SoutheastUS

var PowerBI_SoutheastUS = [
  '57.151.220.224/31'
  '57.151.220.228/30'
  '57.151.220.232/29'
  '2603:1030:902:2::400/122'
  '2603:1030:902:2::440/123'
]
