// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : PowerBI.WestUS3

var PowerBI_WestUS3 = [
  '20.14.120.8/29'
  '20.14.121.160/29'
  '20.14.121.184/29'
  '20.125.157.32/31'
  '20.150.160.110/31'
  '20.150.160.124/30'
  '20.150.161.144/29'
  '172.182.152.168/29'
  '172.182.174.208/28'
  '172.182.174.224/28'
  '2603:1030:504::/122'
  '2603:1030:504::40/123'
  '2603:1030:504:1::5e0/123'
  '2603:1030:504:1::600/122'
]
