// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : PowerBI.DenmarkEast

@export()
var PowerBI_DenmarkEast = [
  '9.205.43.240/31'
  '9.205.43.244/30'
  '9.205.43.248/29'
  '9.205.58.176/28'
  '9.205.58.192/28'
  '2603:1020:1602:2::1a0/123'
  '2603:1020:1602:2::300/122'
]
