// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : PowerBI.IndonesiaCentral
metadata name = 'PowerBI.IndonesiaCentral'
metadata description = 'This module contains all the service tag IP addresses of PowerBI.IndonesiaCentral for Public.'
metadata author = ''
metadata author = ''

@description('PowerBI.IndonesiaCentral service tag IP addresses for Public')
@export()
var PowerBI_IndonesiaCentral = [
  '70.153.64.48/28'
  '70.153.64.64/28'
  '70.153.165.90/31'
  '70.153.165.92/30'
  '70.153.165.104/29'
  '70.153.173.120/29'
  '70.153.173.128/27'
  '2603:1040:1802:2::a0/123'
  '2603:1040:1802:2::c0/122'
]
