// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : PowerBI.AustraliaCentral2

var PowerBI_AustraliaCentral2 = [
  '20.36.120.122/31'
  '20.36.120.124/30'
  '20.36.120.208/29'
  '2603:1010:404::620/123'
  '2603:1010:404::640/122'
]
