// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : PowerBI.EastUS3

var PowerBI_EastUS3 = [
  '134.138.76.126/31'
  '134.138.79.84/30'
  '134.138.82.0/29'
  '2603:1030:1402:2::3e0/123'
  '2603:1030:1402:2::440/122'
]
