// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : PowerBI.BrazilSoutheast
metadata name = 'PowerBI.BrazilSoutheast'
metadata description = 'This module contains all the service tag IP addresses of PowerBI.BrazilSoutheast for Public.'
metadata author = ''
metadata author = ''

@description('PowerBI.BrazilSoutheast service tag IP addresses for Public')
@export()
var PowerBI_BrazilSoutheast = [
  '20.195.146.200/30'
  '20.206.0.96/29'
  '191.233.8.22/31'
  '191.233.10.32/30'
  '191.233.10.40/29'
  '2603:1050:403::5e0/123'
  '2603:1050:403::600/122'
]
