// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureKeyVault.CentralUSEUAP
metadata name = 'AzureKeyVault.CentralUSEUAP'
metadata description = 'This module contains all the service tag IP addresses of AzureKeyVault.CentralUSEUAP for Public.'
metadata author = ''
metadata author = ''

@description('AzureKeyVault.CentralUSEUAP service tag IP addresses for Public')
@export()
var AzureKeyVault_CentralUSEUAP = [
  '20.45.208.8/30'
  '20.45.241.176/29'
  '20.46.11.248/29'
  '20.46.12.192/30'
  '2603:1030:f:1::100/124'
  '2603:1030:f:1::110/125'
  '2603:1030:f:1::2a0/125'
  '2603:1030:f:400::880/125'
]
