// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureKeyVault.WestCentralUS
metadata name = 'AzureKeyVault.WestCentralUS'
metadata description = 'This module contains all the service tag IP addresses of AzureKeyVault.WestCentralUS for Public.'
metadata author = ''
metadata author = ''

@description('AzureKeyVault.WestCentralUS service tag IP addresses for Public')
@export()
var AzureKeyVault_WestCentralUS = [
  '13.71.194.112/30'
  '20.69.1.104/29'
  '20.69.1.112/30'
  '57.151.155.72/30'
  '172.215.206.216/30'
  '2603:1030:b04::108/125'
  '2603:1030:b04::110/126'
  '2603:1030:b04::2a0/125'
  '2603:1030:b04:402::80/125'
  '2603:1030:b04:800::50/125'
  '2603:1030:b04:c00::18/125'
]
