// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureKeyVault.UKWest
metadata name = 'AzureKeyVault.UKWest'
metadata description = 'This module contains all the service tag IP addresses of AzureKeyVault.UKWest for Public.'
metadata author = ''
metadata author = ''

@description('AzureKeyVault.UKWest service tag IP addresses for Public')
@export()
var AzureKeyVault_UKWest = [
  '20.58.67.48/29'
  '20.58.67.56/30'
  '51.140.210.80/30'
  '2603:1020:605::104/126'
  '2603:1020:605::108/125'
  '2603:1020:605::2a0/125'
  '2603:1020:605:402::80/125'
]
