// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureKeyVault.DenmarkEast
metadata name = 'AzureKeyVault.DenmarkEast'
metadata description = 'This module contains all the service tag IP addresses of AzureKeyVault.DenmarkEast for Public.'
metadata author = ''
metadata author = ''

@description('AzureKeyVault.DenmarkEast service tag IP addresses for Public')
@export()
var AzureKeyVault_DenmarkEast = [
  '9.205.39.24/30'
  '9.205.50.136/29'
  '9.205.75.52/30'
  '9.205.99.4/30'
  '9.205.115.4/30'
  '2603:1020:1602:1::1c8/125'
  '2603:1020:1602:400::18/125'
  '2603:1020:1602:800::18/125'
  '2603:1020:1602:c00::18/125'
]
