// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureKeyVault.SwedenCentral
metadata name = 'AzureKeyVault.SwedenCentral'
metadata description = 'This module contains all the service tag IP addresses of AzureKeyVault.SwedenCentral for Public.'
metadata author = ''
metadata author = ''

@description('AzureKeyVault.SwedenCentral service tag IP addresses for Public')
@export()
var AzureKeyVault_SwedenCentral = [
  '51.12.25.204/30'
  '51.12.28.32/29'
  '51.12.98.0/30'
  '51.12.229.24/30'
  '51.12.237.24/30'
  '2603:1020:1004::10c/126'
  '2603:1020:1004::110/125'
  '2603:1020:1004:1::1f8/125'
  '2603:1020:1004:400::80/125'
  '2603:1020:1004:400::2f8/125'
  '2603:1020:1004:800::140/125'
]
