// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-21
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 396
// Service tag  : StorageSyncService.AustriaEast

var StorageSyncService_AustriaEast = [
  '68.210.62.32/29'
  '68.210.152.48/29'
  '2603:1020:104:800::120/123'
]
