// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureDigitalTwins.WestIndia

var AzureDigitalTwins_WestIndia = [
  '52.136.52.248/29'
  '52.136.53.64/27'
  '2603:1040:806:3::200/121'
]
