// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureDigitalTwins.PolandCentral

var AzureDigitalTwins_PolandCentral = [
  '20.215.3.192/27'
  '2603:1020:1302::580/121'
]
