// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureDigitalTwins.TaiwanNorth

var AzureDigitalTwins_TaiwanNorth = [
  '51.53.27.192/27'
  '2603:1040:1302::580/121'
]
