// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-10
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 407
// Service tag  : AzureDigitalTwins.CanadaCentral

var AzureDigitalTwins_CanadaCentral = [
  '20.48.193.128/27'
  '20.48.193.160/29'
]
