// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureDigitalTwins.GermanyWestCentral

var AzureDigitalTwins_GermanyWestCentral = [
  '51.116.148.120/29'
  '51.116.148.192/27'
]
