// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-10
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 408
// Service tag  : AzureDigitalTwins.AustraliaCentral

var AzureDigitalTwins_AustraliaCentral = [
  '20.53.48.0/27'
  '20.53.48.32/29'
  '2603:1010:304:2::700/121'
]
