// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureDigitalTwins.IndiaSouthCentral
metadata name = 'AzureDigitalTwins.IndiaSouthCentral'
metadata description = 'This module contains all the service tag IP addresses of AzureDigitalTwins.IndiaSouthCentral for Public.'
metadata author = ''
metadata author = ''

@description('AzureDigitalTwins.IndiaSouthCentral service tag IP addresses for Public')
@export()
var AzureDigitalTwins_IndiaSouthCentral = [
  '172.198.84.152/29'
  '172.198.86.32/27'
  '2603:1040:1904::780/121'
]
