// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureDigitalTwins.NortheastUS5

@export()
var AzureDigitalTwins_NortheastUS5 = [
  '172.194.70.0/29'
  '172.194.70.32/27'
  '2603:1030:1602::700/121'
]
