// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureDigitalTwins.AustraliaSoutheast
metadata name = 'AzureDigitalTwins.AustraliaSoutheast'
metadata description = 'This module contains all the service tag IP addresses of AzureDigitalTwins.AustraliaSoutheast for Public.'
metadata author = ''
metadata author = ''

@description('AzureDigitalTwins.AustraliaSoutheast service tag IP addresses for Public')
@export()
var AzureDigitalTwins_AustraliaSoutheast = [
  '104.46.178.120/29'
  '104.46.178.160/27'
  '2603:1010:101:7::600/121'
]
