// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureDigitalTwins.EastUSSTG

var AzureDigitalTwins_EastUSSTG = [
  '40.67.52.104/29'
  '40.67.52.192/27'
  '2603:1030:104::700/121'
]
