// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-21
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 396
// Service tag  : AzureDigitalTwins.FranceSouth

var AzureDigitalTwins_FranceSouth = [
  '52.136.184.80/29'
  '52.136.184.96/27'
  '2603:1020:905:2::780/121'
]
