// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureDigitalTwins.CentralUS
metadata name = 'AzureDigitalTwins.CentralUS'
metadata description = 'This module contains all the service tag IP addresses of AzureDigitalTwins.CentralUS for Public.'
metadata author = ''
metadata author = ''

@description('AzureDigitalTwins.CentralUS service tag IP addresses for Public')
@export()
var AzureDigitalTwins_CentralUS = [
  '20.40.225.48/29'
  '20.40.225.128/27'
]
