// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureDigitalTwins.NorwayEast

var AzureDigitalTwins_NorwayEast = [
  '51.120.232.40/29'
  '51.120.232.128/27'
  '2603:1020:e04::700/121'
]
