// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureDigitalTwins.CentralIndia
metadata name = 'AzureDigitalTwins.CentralIndia'
metadata description = 'This module contains all the service tag IP addresses of AzureDigitalTwins.CentralIndia for Public.'
metadata author = ''
metadata author = ''

@description('AzureDigitalTwins.CentralIndia service tag IP addresses for Public')
@export()
var AzureDigitalTwins_CentralIndia = [
  '52.140.111.112/29'
  '52.140.111.192/27'
  '2603:1040:a06:2::200/121'
]
