// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureDigitalTwins.AustriaEast
metadata name = 'AzureDigitalTwins.AustriaEast'
metadata description = 'This module contains all the service tag IP addresses of AzureDigitalTwins.AustriaEast for Public.'
metadata author = ''
metadata author = ''

@description('AzureDigitalTwins.AustriaEast service tag IP addresses for Public')
@export()
var AzureDigitalTwins_AustriaEast = [
  '68.210.163.192/27'
  '68.210.179.32/29'
  '2603:1020:104:4::380/121'
]
