// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureDigitalTwins.SwitzerlandNorth
metadata name = 'AzureDigitalTwins.SwitzerlandNorth'
metadata description = 'This module contains all the service tag IP addresses of AzureDigitalTwins.SwitzerlandNorth for Public.'
metadata author = ''
metadata author = ''

@description('AzureDigitalTwins.SwitzerlandNorth service tag IP addresses for Public')
@export()
var AzureDigitalTwins_SwitzerlandNorth = [
  '51.107.241.64/27'
  '51.107.241.96/29'
  '2603:1020:a04:2::580/121'
]
