// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureDigitalTwins.ItalyNorth
metadata name = 'AzureDigitalTwins.ItalyNorth'
metadata description = 'This module contains all the service tag IP addresses of AzureDigitalTwins.ItalyNorth for Public.'
metadata author = ''
metadata author = ''

@description('AzureDigitalTwins.ItalyNorth service tag IP addresses for Public')
@export()
var AzureDigitalTwins_ItalyNorth = [
  '4.232.26.224/27'
  '2603:1020:1204::600/121'
]
