// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-10
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 407
// Service tag  : AzureDigitalTwins.SwitzerlandNorth

var AzureDigitalTwins_SwitzerlandNorth = [
  '51.107.241.64/27'
  '51.107.241.96/29'
  '2603:1020:a04:2::580/121'
]
