// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureDigitalTwins.IsraelCentral

@export()
var AzureDigitalTwins_IsraelCentral = [
  '20.217.43.192/27'
  '2603:1040:1402::580/121'
]
