// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureDigitalTwins.SouthAfricaNorth

@export()
var AzureDigitalTwins_SouthAfricaNorth = [
  '102.133.221.16/29'
  '102.133.221.32/27'
]
