// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureBotService.SwedenSouth

@export()
var AzureBotService_SwedenSouth = [
  '51.12.192.64/26'
  '2603:1020:1104::20/123'
]
