// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureBotService.IsraelNorthwest
metadata name = 'AzureBotService.IsraelNorthwest'
metadata description = 'This module contains all the service tag IP addresses of AzureBotService.IsraelNorthwest for Public.'
metadata author = ''
metadata author = ''

@description('AzureBotService.IsraelNorthwest service tag IP addresses for Public')
@export()
var AzureBotService_IsraelNorthwest = [
  '20.217.248.16/30'
  '2603:1040:1702::20/123'
]
