// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-10
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureBotService.SouthCentralUS

var AzureBotService_SouthCentralUS = [
  '13.73.248.0/30'
  '20.45.123.112/30'
  '2603:1030:807:1::20/123'
]
