// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureBotService.IndonesiaCentral

var AzureBotService_IndonesiaCentral = [
  '70.153.152.16/30'
  '2603:1040:1802:2::740/123'
]
