// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureBotService.UAENorth

var AzureBotService_UAENorth = [
  '20.38.136.64/30'
  '65.52.252.104/30'
  '2603:1040:904:1::20/123'
]
