// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureBotService.SoutheastUS

@export()
var AzureBotService_SoutheastUS = [
  '57.151.208.16/30'
  '2603:1030:902::20/123'
]
