// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureBotService.SwedenCentral

@export()
var AzureBotService_SwedenCentral = [
  '51.12.40.64/26'
  '2603:1020:1004::20/123'
]
