// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : AzureBotService.KoreaCentral

var AzureBotService_KoreaCentral = [
  '20.41.64.64/30'
  '20.44.27.208/30'
  '2603:1040:f05:1::20/123'
]
