// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureBotService.BelgiumCentral

var AzureBotService_BelgiumCentral = [
  '9.160.40.16/30'
  '2603:1020:1502::20/123'
]
