// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 407
// Service tag  : AzureBotService.JapanWest

var AzureBotService_JapanWest = [
  '40.80.56.64/30'
  '40.80.176.32/30'
  '2603:1040:606::20/123'
]
