// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : AzureBotService.TaiwanNorth

var AzureBotService_TaiwanNorth = [
  '51.53.24.16/30'
  '2603:1040:1302::20/123'
]
