// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureBotService.AustraliaCentral2

@export()
var AzureBotService_AustraliaCentral2 = [
  '20.36.115.240/30'
  '20.36.120.64/30'
  '2603:1010:404::20/123'
]
