// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-04
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureBotService.EastUSSTG

var AzureBotService_EastUSSTG = [
  '40.67.48.64/30'
  '40.67.58.4/30'
  '2603:1030:104:1::20/123'
]
