// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-07-12
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Service tag  : AzureBotService.SouthCentralUSSTG

@export()
var AzureBotService_SouthCentralUSSTG = [
  '20.44.4.72/30'
  '20.45.112.64/30'
]
