// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-27
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 397
// Service tag  : AzureBotService.BrazilSoutheast

var AzureBotService_BrazilSoutheast = [
  '191.233.8.16/30'
  '2603:1050:403::20/123'
]
