// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureBotService.SouthIndia

var AzureBotService_SouthIndia = [
  '20.41.192.64/30'
  '40.78.196.56/30'
  '2603:1040:c06::20/123'
]
