// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-21
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 396
// Service tag  : AzureBotService.TaiwanNorthwest

var AzureBotService_TaiwanNorthwest = [
  '51.53.168.16/30'
  '2603:1040:1202::20/123'
]
