// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-04-21
// Source file  : ServiceTags_China.json
// Cloud        : China
// Change number: 391
// Service tag  : AzureBotService.ChinaNorth3

var AzureBotService_ChinaNorth3 = [
  '52.131.16.16/30'
  '2406:e500:2602::1a0/123'
]
