// Auto-generated file – do not edit manually.
// Generated by : https://github.com/rdeveen/azure-ip-addresses-bicep
// Generated at : 2026-05-06
// Source file  : ServiceTags_Public.json
// Cloud        : Public
// Change number: 398
// Service tag  : AzureUpdateDelivery.WestCentralUS

var AzureUpdateDelivery_WestCentralUS = [
  '20.165.191.133/32'
  '20.165.241.177/32'
]
